### ISSUE TITLE
aint workin =(

### ISSUE THREAD

**Issue by czif** [pylerSM/YouTubeBackgroundPlayback#1]
it is not working at all, it's just making bugs to YT app

**Comment by pylerSM** [comment]
At least screen off playback should work. On 4.2.2 background playing too. I don't know yet why on 4.4.4 it doesn't work. Damn it.

Making bugs? You are funny, since it can't crash app. There are two supported YT versions (I tested module with them). Try to post some useful info.

**Comment by matan129** [comment]
Hey,  I can testify that screen off playback works for me perfectly.  But the playback stops when I put the YouTube app in the background (switch to another app)

**Comment by Teoatl** [comment]
You are half way there my friend. Screen off saves battery. Hope you can get it working on 4.4. Thank you.

**Comment by newzealandpaul** [comment]
Firstly let me say THANK YOU THANK YOU THANK YOU. This is desperately needed.

On 4.4.4 on my Galaxy S4 only screen off / lock screen playback works ... but ....

I can induce it to play in the background  for a limited period of time by swiping down on the notification drawer and then after it comes all the way down, by hitting the home button on my S4 (the hardware key). I am them taken to my homescreen and playback continues.

After 30 seconds or so background playback stops. Looking at the notification in the drawer, the play button is either replaced by an "!" or a reloading animation. (my memory may be slightly off ... I am at work without my phone and I tried this a few hours ago). I hope this helps ...

Can't wait for it to work on 4.4.4. Thanks again @pylerSM you are LEGEND!!!!

**Comment by renovatio2** [comment]
In trying on thl4000. KitKat almost stock version. 

Screen off ok, not the rest. Thanks for your job.

**Comment by marcinsu** [comment]
Yes, only background playing not work.
Android: 4.4.4 (CM11)

**Comment by taaem** [comment]
doesn't work at all :(
Android 4.4.2
Huawei P6 Stock 
Xposed without resource hooks

**Comment by DieterHolvoet** [comment]
Not working here either, nor background playback, nor screen off playback.
Running stock 4.2.2 on a Wiko Rainbow.
Also, your module isn't appearing in the in-app repository, but it is on the website. Strange.

**Comment by pylerSM** [comment]
Update youtube app. Screen off playback works well.

**Comment by DieterHolvoet** [comment]
I updated it, and it doesn't work.
Op 7 feb. 2015 12:31 schreef "pyler" <notifications@github.com>:

**Comment by pylerSM** [comment]
I tried to fix background playback but still shitty "!" icon. Damn. I am angry, since it works well on Samsung G S2 Plus (TW 4.2.2). On newer android versions no luck :(

**Comment by pylerSM** [comment]
Renamed module in repo.

**Comment by renovatio2** [comment]
Yes, would like to have jelly bean right now. Are you looking for solutions
or can't find the problem? Still hoping!
Il 07/feb/2015 14:29 "pyler" <notifications@github.com> ha scritto:

**Comment by pylerSM** [comment]
I tried to find what's wrong... But very hard since code is obfuscated.

Maybe @GermainZ or @theknut come with great idea since they deal with obfuscation too.

**Comment by GermainZ** [comment]
No time, sorry. I don't know what you mean by the "!" icon (string or drawable?), but I guess you can see what's using it and go from there.

**Comment by pylerSM** [comment]
Yes, I went that way today. I found out that "!" in notification is imageview with id "error".  I got res id for this resource. Then I found some results for the res id in code.. Now I take a rest, maybe tomorrow I can look on it.

**Comment by theknut** [comment]
Welcome to the wonderful world of obfuscation!
Am 07.02.2015 18:07 schrieb "pyler" <notifications@github.com>:

**Comment by Teoatl** [comment]
I used to use other youtube apps that can play in background such as viral youtube and than they said google told them to take that feature off to remain in playstore. Wow. Its obvious they have other agendas that aren't in public interest.  Why should your screen be on all the time to play audio or why can't you do anything else while playing. They want your eyes on their ads all the freaking time.  Very greedy. Android is awesome but i am starting to believe in cyanogenmod remarks calling them tyrannical. Anyway thank you for your work on youtube I will gladly donate once i figure out how github works i just signed up to leave you comment on progress.

**Comment by theknut** [comment]
CM is not greedy at all...
Am 07.02.2015 18:12 schrieb "Teoatl" <notifications@github.com>:

**Comment by Teoatl** [comment]
No i agree with tyranny part.  I know they screwed over one plus one to expand their business with another phone maker. But they also give me unlimited hotspot and a lot more freedom with their rom compared to stock android.

**Comment by renovatio2** [comment]
Why? To make the paid version. Off course. It's something like dlc of the
console games.
On xda then, you can try to make YouTube run on background, but if you put
hand on the paid app code, for them you can't.

But lol.
Il 07/feb/2015 18:12 "Teoatl" <notifications@github.com> ha scritto:

**Comment by renovatio2** [comment]
You can have everything of cyanogen in different ways and more, I guess.
Il 07/feb/2015 18:23 "Teoatl" <notifications@github.com> ha scritto:

**Comment by newzealandpaul** [comment]
Gentlemen, please do not derail this bug report with a discussion about CM or XDA.

**Comment by newzealandpaul** [comment]
@pylerSM do you think the YouTube app is trying to detect if it is running in the background, and then automatically disconnecting?

Is it possible to make the app think it is still running in the foreground?

**Comment by pylerSM** [comment]
Using "error" string I found that it could be something with network. But I am confused. How on 4.2.2 it works and on 4.4 not?

**Comment by pylerSM** [comment]
´´´else if ((str2.contains("net.timeout")) || (str2.contains("net.closed")))
      {
        localgsl2 = localgsl1;
        i3 = 2131362068;
        bool1 = true;
      }´´´

**Comment by pylerSM** [comment]
Worked on it yday. I found that exo player somehow crashes when we put app to the background. Let's see what can be done...

**Comment by pylerSM** [comment]
Now I know where it fails. android.exo IllegalStateException

http://pastebin.com/naF72JqY line 1292


@GermainZ ?

**Comment by pylerSM** [comment]
E/ExoPlayerImplInternal(25316): Internal runtime error.

E/ExoPlayerImplInternal(25316): java.lang.IllegalStateException

E/ExoPlayerImplInternal(25316): 	at android.media.MediaCodec.dequeueInputBuffer(Native Method)

E/ExoPlayerImplInternal(25316): 	at dpn.a(SourceFile:527)

E/ExoPlayerImplInternal(25316): 	at dpn.a(SourceFile:451)

E/ExoPlayerImplInternal(25316): 	at dpf.handleMessage(SourceFile:203)

E/ExoPlayerImplInternal(25316): 	at android.os.Handler.dispatchMessage(Handler.java:98)

E/ExoPlayerImplInternal(25316): 	at android.os.Looper.loop(Looper.java:136)

E/ExoPlayerImplInternal(25316): 	at android.os.HandlerThread.run(HandlerThread.java:61)

E/ExoPlayerImplInternal(25316): 	at dvd.run(SourceFile:40)

**Comment by GermainZ** [comment]
I can't figure out what's wrong with just the error and the class where it's being thrown. Other than the exact code you're trying, I'd also need some time to check and understand what you're trying to do and how to do that by modifying YouTube. At the moment, however, I simply don't have the time for this, sorry.

**Comment by renovatio2** [comment]
Well, I'm sorry I can't help but if you can suggest the point to someone
would be appreciate. Thanks a lot
Il 11/feb/2015 19:59 "Germain Z." <notifications@github.com> ha scritto:

**Comment by pylerSM** [comment]
Well, I already know what's wrong and why youtube (outside app) background playback fails. I try to fix it, but I really don't know how. I will study older versions of YouTube.

**Comment by pylerSM** [comment]
Update: Some guy from XDA contacted me & he may help me since he is also "youtube smali hacking guy". Will work with him and *maybe* we can find fix.

**Comment by renovatio2** [comment]
Glad to hear that. Good work both of use and if he wants to say his
nickname we're here to thank him
Il 12/feb/2015 19:09 "pyler" <notifications@github.com> ha scritto:

**Comment by pylerSM** [comment]
Issue fixed. New build soon. Yaaaay!

Since I had to build my own workaround to make it fully working, can I post module on XDA now, @GermainZ?

**Comment by theknut** [comment]
So this module will enable me to start a music video on YouTube and let me
switch apps and still play the music? That would be awesome. Did you write
it yourself or continue someone else's module, or why did you ask?
Am 13.02.2015 19:02 schrieb "pyler" <notifications@github.com>:

**Comment by GermainZ** [comment]
Possibly, please contact me on XDA if we need to discuss this. Cheers.
On Fri, Feb 13, 2015 at 8:02 PM, pyler <notifications@github.com> wrote:Issue fixed. New build soon. Yaaaay!

Since I had to build my own workaround to make it fully working, can I post module on XDA now, @GermainZ?

**Comment by pylerSM** [comment]
@theknut, yes, you understood it well. I wrote it myself (Michael Groth helped me with fix for 4.4, gave me idea. Then I found fix for it.)

I posted thread on XDA some time ago, bug was removed since it enables Music Key Premium feature.. So we will talk about it again with germainz.

**Comment by theknut** [comment]
I see, since I don't use the service, I'll fork it if it will not be
allowed on XDA.
Am 13.02.2015 19:26 schrieb "pyler" <notifications@github.com>:

**Comment by pylerSM** [comment]
Still in xposed repo, no need to fork/build custom versions. But contributions are welcomed! :)

**Comment by theknut** [comment]
If it's breaking rules it'll be kicked from the repo as well. So just let
me know what's the result of your discussion.
Am 13.02.2015 20:04 schrieb "pyler" <notifications@github.com>:

**Comment by pylerSM** [comment]
Ok, i will give you know. Module should stay in repo, many people use it. If it was removed from repo, I would cease development. Some other modules are also on the edge of (il)legality, so... Let's not make double standards, okay?

**Comment by theknut** [comment]
Which modules are these. People also like pirating software, doesn't mean
it's legal.
Am 13.02.2015 21:07 schrieb "pyler" <notifications@github.com>:

**Comment by Teoatl** [comment]
Wow  Knut.  I pirate everything digital. People get ripped off "legally"  every day in many ways. Are you nsa? Are you online police? Pyler is not selling crack to kids. He is making youtube app better. He is not stealing any content. He is just adding a feature that should have been there to begin with. Why do you need screen on while playing audio?   Why don't you let pyler do what he wants if he is making a more useful app thats much better than what google force feeds everyone. Kinda like Facebook did with messenger. PYLER please continue with development and i will fund you if you need it. And knut, you can suck it.

**Comment by renovatio2** [comment]
I downloaded 1.1 version and still doesn't work for me. Screen off only
goes well.

2015-02-13 21:15 GMT+01:00 Teoatl <notifications@github.com>:

**Comment by theknut** [comment]
I can't remember asking for your advice.

The Xposed framework must not be known by other companies as something
which violates their business strategy. Some apps are explicitly checking
if the Xposed framework is installed and will not start. That's how far it
already got.

You are not only hurting rovos reputation but if restrictions go even
further it might lead to the end of Xposed. There are several people who
are making a good amount of money or let's say do this for their living.
There is a reason why YouTube doesn't allow background playback. It might
not make sense to your to you but that's the least problem.

My point was: There is a strict line which must not be crossed. Only
because people like it does not make it legit. Working around a paid
service is pirating. If it can't be posted on XDA it shouldn't be posted to
the repo as well.
Am 13.02.2015 21:15 schrieb "Teoatl" <notifications@github.com>:

**Comment by Teoatl** [comment]
Yeah they might associate it with illegal if you keep mentioning it in comments.  Let the man do what he wants if he gets a notice from higher ups to take it down he can. You're the type to report to Google that someone is doing their job better.

**Comment by theknut** [comment]
Seems like you don't know who I am.

So you want pyler to get mail from Googles lawyers, just like KeepChat dev?
Anyways, end of discussion.
Am 13.02.2015 21:35 schrieb "Teoatl" <notifications@github.com>:

**Comment by Teoatl** [comment]
Im sure he will wipe his butt with the google papers.

**Comment by Teoatl** [comment]
And he is right what about the app that blocks ads on YouTube isn't that actually worse than what he is trying to do here?  If he xposed becomes liability to developers than move xposed to Tor.

**Comment by theknut** [comment]
I don't know this module. Please report it here
<http://repo.xposed.info/contact>, choose the category "Report abusive
module" and put the link of the module in the description. Thank you.

2015-02-13 21:46 GMT+01:00 Teoatl <notifications@github.com>:

**Comment by Teoatl** [comment]
Oh yeah i will report something useful.  Ok i get it you're the mod here or some type of authority and  my comments are too open you are welcome to delete them.  I didn't buy android for itunes. PYLER you're the man.

**Comment by renovatio2** [comment]
Knut, Google makes its app with limits, then some people do it better as
some other developers makes better similar app.
Then you know what? Google makes the pay version app, for free. And we're
all happy. But it's the way google makes things.

Pyler it's a drop in the ocen to speedup the natural process. That's over.

2015-02-13 21:48 GMT+01:00 theknut <notifications@github.com>:

**Comment by pylerSM** [comment]
Guys, no drama here. 

If you want, feel free to report this module to rovo, to Google, to NSA, to everyone. Say Google they should do better apps and then we all will be happy.

**Comment by pylerSM** [comment]
theknut, you blame me but.. you hacks Google app too. You basically also enable/add features which Google doesn't want. You do amazing work, hats off. But please don't make double standards, ya?

**Comment by theknut** [comment]
I'm not blaming you plus GNL is completely free. No double standards.

2015-02-13 22:07 GMT+01:00 pyler <notifications@github.com>:

**Comment by pylerSM** [comment]
btw @theknut, maybe you know solution for this issue: http://forum.xda-developers.com/xposed/class-using-boot-class-loader-stack-t3030446?

**Comment by someone7** [comment]
It works perfectly in every way, background, screen off, multitask, you name it (4.4.2). Thanks man, great work. God bless.
