### ISSUE TITLE
playlists supported in latest version? 

### ISSUE THREAD

**Issue by sebastienbo** [pylerSM/YouTubeBackgroundPlayback#10]
For some reason, it now only plays one song of a playlist and then stops, is the auto play next song of YouTube not working with the adaway extension?

**Comment by sebastienbo** [comment]
Sorry I ment the background play instead of adaway

**Comment by dillalade** [comment]
I'm encountering the same issue. Only able to play one song from the playlist. If screen goes off the playback will finish after the current clip. You have to go back into your tube for the next clip to follow manually.

When this is resolved what a rich feature we will have. Brilliant module

**Comment by Syl0s** [comment]
I find, you can also just hit the "Next"-Button on music controls around your phone, and it will start playing the next song. This is especially useful with for example CyanogenMod, where you can just long-press the "Up"-side of your volume-rocker, while the screen's off, to start playing the next song. Should also work via headsets with built-in media-buttons.

**Comment by Syl0s** [comment]
This issue seems to be resolved as of version 1.3.4. At least, it works for me now. Maybe check back, if it now works for you, too. Also, I don't know how important that is, but I'm using version 10.10.52 of YouTube.
