### ISSUE TITLE
feature request - Support YouTube Music

### ISSUE THREAD

**Issue by FlourishFlora** [pylerSM/YouTubeBackgroundPlayback#100]
This tweak doesn't seem to support the YouTube Music app (https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.music). It would be great if it did. The YouTube Music app is pretty similar to the regular YouTube app functionality-wise, but I'd prefer to use it since the interface is better for listening to music.

**Comment by esgie** [comment]
The app is only displaying an information that the YouTube Music service is not available in my country atm.
So, I have no easy possibility to test it .
