### ISSUE TITLE
Smali edit

### ISSUE THREAD

**Issue by pylerSM** [pylerSM/YouTubeBackgroundPlayback#102]
Any skilled Smali hacker here?

I was wondering if we could do modified version of YT with our changes.

**Comment by iHelp101** [comment]
I just wanted to give you a warning about this approach. When you decompile an APK and modify the code to your liking you are technically committing copyright infringement. You are using Youtube's logo, images, etc. without permission to make your own version. This is the reason solutions such as SnapMod shutdown (Snapchat lawyers contacted them). I wanted to give you a heads up, so you don't get in any serious trouble Google.

**Comment by pylerSM** [comment]
Aha ok then. So only for personal use, it seems :D

**Comment by PwnicornDev** [comment]
[OGYouTube](http://ogmods.net/home/OGYouTube) is a modded version of the official app thats distributed [on XDA](http://forum.xda-developers.com/showthread.php?t=2213945) for quite some time now. Better leave the risky stuff to Mr. OG and focus on Xposed :smile:
