### ISSUE TITLE
new versions after 1.7.3, YT version 10.47.55 not working

### ISSUE THREAD

**Issue by ertmuirm** [pylerSM/YouTubeBackgroundPlayback#106]
tried new versions with the exact youtube versions they were supposed to match, but background play is not functioning

reverting back to 10.47.55

**Comment by esgie** [comment]
Did you reboot between module updates?

**Comment by ertmuirm** [comment]
Yes, of course. Tried different yt versions all within, couldn't get it to work still 

-------- Original Message --------

**Comment by ertmuirm** [comment]
i've tried the new versions of YTBP and matched them to the specific release of YT, but it's still not working for me

only 10.47.55 and 1.7.3 work. did something change on the YT end (e.g. restricting background play to youtube red / youtube music subscribers) after 10.47.55?

does anyone else have this problem? I'm on Xperia Z1 compact stock 5.1.1, no youtube red or youtube music, using the service outside the US

**Comment by esgie** [comment]
Any restrictions should not affect the work of the module.
Can you install the newest YouTube as well as module, reboot and try it
again, then post the xposed log here?

pzdr
es
6 lut 2016 01:32 "ertmuirm" <notifications@github.com> napisał(a):

**Comment by ertmuirm** [comment]
thanks for the tip to look at the logs. i finally figured out what was wrong

the xposed framework was trying to load the class at data/app/com.pyler.youtubebackgroundplayback-1/base.apk, but it was installed in my system as youtubebackgroundplayback-2/base.apk

when i changed it back to -1/base.apk, it loaded perfectly. not sure why the module does not detect the updated status of -2/base.apk, but at least i found a simple workaround which i'm guessing i will need to do everytime i update the YTBP module

**Comment by esgie** [comment]
That means that Xposed Installer app isn't updating its configuration when
installing modules. Something must have stuck.
Guess you could try to clear Xposed Installer data and re-enable all the
modules.

pzdr
es
6 lut 2016 14:35 "ertmuirm" <notifications@github.com> napisał(a):

**Comment by ertmuirm** [comment]
that worked for me, thanks much!

**Comment by abenchi** [comment]
I uninstalled/installed again XPoser and restart my telephone and it works again

**Comment by abenchi** [comment]
This ticket should be marked as solved and a new ticket is to be created for xposed framwork
