### ISSUE TITLE
Not working since last update

### ISSUE THREAD

**Issue by ionutalexe** [pylerSM/YouTubeBackgroundPlayback#107]
not working since 11.01.53, rebooted after update and everything

**Comment by esgie** [comment]
11.01.53 is arm64 only atm, are you sure you have proper hardware to run it?

**Comment by ionutalexe** [comment]
well it autoupdated so i guess i have

**Comment by brusyev** [comment]
I have note 4 which is not a 64 bit device and my YouTube has also updated to 11.01.53 and the background play module no longer works...

**Comment by esgie** [comment]
I have just received an update from play store and indeed, background play stopped working.
After some code analysis i figured out that google changed obfuscation method ENTIRELY. It will require more work to make module working again.
What is strange is that universal version of 11.01.53 which can be downloaded here:
http://www.apkmirror.com/apk/google-inc/youtube/youtube-11-01-53-nodpi-android-apk-download/
is obfuscated in an old way, thus working perfectly!
I have to recommend to stick with 10.xx line or install 11.01.53 from the link above and NOT from the Play Store, at least until we deal with the new code and update the module.

**Comment by brusyev** [comment]
Wow. I am curious to why they made such changes. One strange thing is that
at one point I noticed that I was able to quickly rewind back and forth on
my youtube player and then it stopped working again. Have you seen these
gesture controls in the new code? Reminds me of the gesture controls in
good old Viral Player I was involved with at one point...by the way thanks
for the link.

Eugene

**Comment by esgie** [comment]
x86 play store version has the same issue.
I'll try to fix things up @ weekend.

**Comment by brusyev** [comment]
Yeah. I tried it and it didnt work for me. Is there a way to add gesture
controls (swipe left and write) to rewind video?

Eugene

**Comment by esgie** [comment]
Hi guys
I have just got background play working again on Play Store version.
Expect update in the repo in no more than a hour.

**Comment by esgie** [comment]
@ionutalexe 
@brusyev 
please confirm if the recent version work

**Comment by brusyev** [comment]
Where is this current version? Its noy showing being available in xposed
..

**Comment by esgie** [comment]
I sometime suffer of updates not refreshing in xposed installer, too.
I recommend to clear xposed installer data.
Anyway, you can always manually download from here, too.
http://repo.xposed.info/module/com.pyler.youtubebackgroundplayback

**Comment by brusyev** [comment]
If I clear xposed installer data will that wile my module settings?

Eugene

**Comment by brusyev** [comment]
I just tried it and it is not working....

Eugene

**Comment by brusyev** [comment]
Tried version 1.8.1 on Xposed v75

Eugene

**Comment by brusyev** [comment]
As soon as minimize playing video it stops playing...

Eugene

**Comment by brusyev** [comment]
My android version is 5.0.1 with v75 of Xposed...

Eugene

**Comment by brusyev** [comment]
I am available to try the new version once you fix it...

**Comment by brusyev** [comment]
By the way latest module still works with the 10.xx version of
youtube...but there is a bug that shows two icons for the running app in
top left....please see screenshot

As soon as minimize playing video it stops playing...

Eugene

**Comment by brusyev** [comment]
Another question. Is it normal to have the Chrome cast icon instead of a
regular youtube one in the top left when playing in background and not
streaming? I am using a blueooth headset could that be why?

**Comment by esgie** [comment]
If you wipe xposed installer data only the settings of the installer will be lost (you will have to tick enabled modules again on modules list!); the settings of your specific modules will be preserved.
The module definetely works for me on three separate devices.
I assume you have ticked the module on the module list and rebooted after 1.8.1 update.
Can you run the youtube app, play any mivie and then post a log from xposed installer?

**Comment by danbrag** [comment]
Not the guy before, but I just cleared the xposed log, ran youtube, then refreshed and saved the log:

[error.txt](https://github.com/pylerSM/YouTubeBackgroundPlayback/files/100361/error.txt)

Thanks so much for your work!

**Comment by esgie** [comment]
Can you post your youtube apk?
(/data/app/com.google.android.youtube-1/base.apk)
Where did you get it, e.g. from the play store?

**Comment by danbrag** [comment]
Yes, play store. Running 6.0.1 on a Nexus 6p.

I did edit above, but the global app you posted does not work with 1.8.1 as well (at least for me)

[base.zip](https://github.com/pylerSM/YouTubeBackgroundPlayback/files/100372/base.zip)

**Comment by danbrag** [comment]
CAN CONFIRM -- 1.8.0 works with the newest version of the youtube app. 1.8.1 does not (at least for me)

**Comment by ionutalexe** [comment]
the last version works for me

**Comment by brusyev** [comment]
I wiped the installer data, uninstalled youtube app and module, wipped
cache and davlik cache and installed latest version of youtube from play
store as well as the latest module designed for playstore version 1.8.1.
The background play still did not work....aince then I got back to 10.49 as
I did not have a lot of time on my hands...

Eugene

**Comment by danbrag** [comment]
I'd suggest using 1.8.0 for now

**Comment by brusyev** [comment]
I thought 1.8.0 is for non play version of Youtube?

Eugene

**Comment by danbrag** [comment]
I tried with play version last night. Didn't work with 1.8.1 but still
worked with 1.8.0...nexus 6p 6.0.1

**Comment by brusyev** [comment]
11.01.55 Play version of x86 youtube is now out...

**Comment by brusyev** [comment]
By the way on 5.0.1 x86 neither 1.8.0 or 1.8.1 are working....

**Comment by esgie** [comment]
Please check 1.8.2
If still not working please post xposed log.

**Comment by brusyev** [comment]
Working perfectly with latest Play version and module. Thank you for all of
your work

**Comment by esgie** [comment]
I'm trying ;)
Thank you for your feedback, also.

**Comment by danbrag** [comment]
Works for me as well with 1.8.3

**Comment by brusyev** [comment]
FYI

11.04.56 is now out for x86.

**Comment by brusyev** [comment]
YouTube version 11.24.56 for x86 is out on Play..

Eugene

**Comment by brusyev** [comment]
YouTube 11.25.55 is now out for x86 on Play.

Eugene
On Jun 16, 2016 4:59 PM, <brusyev@comcast.net> wrote:

YouTube version 11.24.56 for x86 is out on Play..

Eugene
