### ISSUE TITLE
Not working on X86

### ISSUE THREAD

**Issue by Abbiiddd** [pylerSM/YouTubeBackgroundPlayback#109]
Not working on x86 based processor after last update.

**Comment by esgie** [comment]
Duplicate
https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/107
It is indeed the same issue - x86s have received "new" version so more work will be needed.

**Comment by esgie** [comment]
@Abbiiddd is it fixed now?

**Comment by brusyev** [comment]
A new version 11.05.55 has just been released fon Play for x86. I havent tested it to see if it is working with 1.8.1 or not

**Comment by brusyev** [comment]
My appology the version,is 11.01.55
