### ISSUE TITLE
Small tweaks?

### ISSUE THREAD

**Issue by nerunexus** [pylerSM/YouTubeBackgroundPlayback#11]
Just slapped android L on my HTC one and snagged this module.  Mad props works mint. Just one small issue/question.  When I leave YouTube to another application and this module takes over there is a three to four second pause. I know lots of users are having real issues but this is the ONLY issue I can find. keep up the great work look forward to seeing progress in the future.

**Comment by pylerSM** [comment]
Well, without that pause we lose background playback at all.

**Comment by nerunexus** [comment]
Oh no doubt there needs to be a hook. But what would it take to hook the
video into background player right when we load it and use background
player to replace the normal front end? Am I just crazy but I think users
wouldn't notice the delay when initializing.
