### ISSUE TITLE
Problem with the notification staying around

### ISSUE THREAD

**Issue by ConnorTheFox** [pylerSM/YouTubeBackgroundPlayback#110]
If I leave a video playing and close the app the notification stays around and won't close.

**Comment by PwnicornDev** [comment]
I have the same problem sometimes, it seems to be a bug in the YouTube app itself though. If someone has YouTube Red they could test this with the module disabled.

**Comment by wasdennnoch** [comment]
The whole video keeps playing in the background, this is implemented in the YT app, not the module. It's annoying though.

**Comment by raku-cat** [comment]
If I force close the app instead of just swiping it away it makes the notification not stay,
