### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by yelkarama** [pylerSM/YouTubeBackgroundPlayback#112]
Hi

I would like to report the following exception I spot in my Logcat:

E/Xposed  (11066): java.lang.ClassNotFoundException: Didn't find class "com.google.android.libraries.youtube.player.background.BackgroundTransitioner" on path: DexPathList[[zip file "/data/app/com.google.android.youtube-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.youtube-1/lib/arm, /vendor/lib, /system/lib]]
E/Xposed  (11066): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java)
E/Xposed  (11066): 	at java.lang.ClassLoader.loadClass(ClassLoader.java)
E/Xposed  (11066): 	at java.lang.ClassLoader.loadClass(ClassLoader.java)
E/Xposed  (11066): 	at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback.handleLoadPackage(YouTubeBackgroundPlayback.java:45)
E/Xposed  (11066): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
E/Xposed  (11066): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
E/Xposed  (11066): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
E/Xposed  (11066): 	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:182)
E/Xposed  (11066): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:667)
E/Xposed  (11066): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
E/Xposed  (11066): 	at android.app.ActivityThread.access$1700(ActivityThread.java)
E/Xposed  (11066): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
E/Xposed  (11066): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/Xposed  (11066): 	at android.os.Looper.loop(Looper.java:145)
E/Xposed  (11066): 	at android.app.ActivityThread.main(ActivityThread.java)
E/Xposed  (11066): 	at java.lang.reflect.Method.invoke(Native Method)
E/Xposed  (11066): 	at java.lang.reflect.Method.invoke(Method.java)
E/Xposed  (11066): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
E/Xposed  (11066): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
E/Xposed  (11066): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:116)
E/Xposed  (11066): 	Suppressed: java.lang.ClassNotFoundException: com.google.android.libraries.youtube.player.background.BackgroundTransitioner
E/Xposed  (11066): 		at java.lang.Class.classForName(Native Method)
E/Xposed  (11066): 		at java.lang.BootClassLoader.findClass(ClassLoader.java)
E/Xposed  (11066): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java)
E/Xposed  (11066): 		... 19 more
E/Xposed  (11066): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by esgie** [comment]
Does the module work?
If yes - then there is nothing to worry about.
Google is releasing two parallel revisions of YouTube app atm, so the
module code checks if a class name specific to one of this revisions exist.
In an exception is thrown (the one you possibly see in logcat) then the
module switches to mode specific for the other revision.
So it is probably good that you see the exception being thrown.
31 sty 2016 21:42 "yelkarama" <notifications@github.com> napisał(a):

**Comment by esgie** [comment]
Fixed in the recent version.
Logcat shall be no longer flooded.
