### ISSUE TITLE
Errors in the log

### ISSUE THREAD

**Issue by terrorist96** [pylerSM/YouTubeBackgroundPlayback#113]
The module works, but I hate seeing these errors in the log

02-02 19:50:57.095 E/Xposed  (15295): java.lang.ClassNotFoundException: Didn't find class "com.google.android.libraries.youtube.player.background.BackgroundTransitioner" on path: DexPathList[[zip file "/data/app/com.google.android.youtube-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.youtube-1/lib/arm64, /data/app/com.google.android.youtube-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
02-02 19:50:57.095 E/Xposed  (15295): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
02-02 19:50:57.095 E/Xposed  (15295): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
02-02 19:50:57.095 E/Xposed  (15295): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
02-02 19:50:57.095 E/Xposed  (15295): 	at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback.handleLoadPackage(YouTubeBackgroundPlayback.java:45)
02-02 19:50:57.095 E/Xposed  (15295): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
02-02 19:50:57.095 E/Xposed  (15295): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
02-02 19:50:57.095 E/Xposed  (15295): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
02-02 19:50:57.095 E/Xposed  (15295): 	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:173)
02-02 19:50:57.095 E/Xposed  (15295): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)
02-02 19:50:57.095 E/Xposed  (15295): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
02-02 19:50:57.095 E/Xposed  (15295): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
02-02 19:50:57.095 E/Xposed  (15295): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
02-02 19:50:57.095 E/Xposed  (15295): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-02 19:50:57.095 E/Xposed  (15295): 	at android.os.Looper.loop(Looper.java:148)
02-02 19:50:57.095 E/Xposed  (15295): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
02-02 19:50:57.095 E/Xposed  (15295): 	at java.lang.reflect.Method.invoke(Native Method)
02-02 19:50:57.095 E/Xposed  (15295): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-02 19:50:57.095 E/Xposed  (15295): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-02 19:50:57.095 E/Xposed  (15295): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
02-02 19:50:57.095 E/Xposed  (15295): 	Suppressed: java.lang.ClassNotFoundException: com.google.android.libraries.youtube.player.background.BackgroundTransitioner
02-02 19:50:57.095 E/Xposed  (15295): 		at java.lang.Class.classForName(Native Method)
02-02 19:50:57.095 E/Xposed  (15295): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
02-02 19:50:57.095 E/Xposed  (15295): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
02-02 19:50:57.095 E/Xposed  (15295): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
02-02 19:50:57.095 E/Xposed  (15295): 		... 17 more
02-02 19:50:57.095 E/Xposed  (15295): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by terrorist96** [comment]
02-02 19:38:36.472 E/Xposed  ( 9341): java.lang.ClassNotFoundException: Didn't find class "com.google.android.libraries.youtube.player.background.BackgroundTransitioner" on path: DexPathList[[zip file "/data/app/com.google.android.youtube-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.youtube-1/lib/arm64, /data/app/com.google.android.youtube-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
02-02 19:38:36.472 E/Xposed  ( 9341): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback.handleLoadPackage(YouTubeBackgroundPlayback.java:45)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:173)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at android.os.Looper.loop(Looper.java:148)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at java.lang.reflect.Method.invoke(Native Method)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-02 19:38:36.472 E/Xposed  ( 9341): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
02-02 19:38:36.472 E/Xposed  ( 9341): 	Suppressed: java.lang.ClassNotFoundException: com.google.android.libraries.youtube.player.background.BackgroundTransitioner
02-02 19:38:36.472 E/Xposed  ( 9341): 		at java.lang.Class.classForName(Native Method)
02-02 19:38:36.472 E/Xposed  ( 9341): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
02-02 19:38:36.472 E/Xposed  ( 9341): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
02-02 19:38:36.472 E/Xposed  ( 9341): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
02-02 19:38:36.472 E/Xposed  ( 9341): 		... 17 more
02-02 19:38:36.472 E/Xposed  ( 9341): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by iHelp101** [comment]
Add try and catches for the method hooks. That way instead of getting 25+ lines of error you get a simple "X Hook Failed". It makes everything look pretty and of course helps when debugging.

try {
   findAndHookMethod(CLASS_1[i], loader, METHOD_1[i], new XC_MethodHook() {
            @Override
            protected void beforeHookedMethod(final MethodHookParam param) throws Throwable {
                setBooleanField(getObjectField(param.thisObject, FIELD_1[i]), SUBFIELD_1[i], true);
            }
        });
} catch (Throwable t) {
   XposedBridge.log("Class 1 Hooks Failed")
}

**Comment by terrorist96** [comment]
In English, please? ☺️

**Comment by iHelp101** [comment]
@terrorist96 It is a note for Pyler or Esgie. We are just making sure the module catches exceptions, which means you won't get the crazy long list of error in the log. It is a code change, but it is very simple.

**Comment by esgie** [comment]
@iHelp101  @terrorist96 
Uh sorry I just realized that I have left log(e); uncommented in the latest release build.
And that was the fault.
Will be fixed in the new version.
