### ISSUE TITLE
Use StorePrefs to prevent YouTube update to incompatible version

### ISSUE THREAD

**Issue by PwnicornDev** [pylerSM/YouTubeBackgroundPlayback#114]
[StorePrefs](http://forum.xda-developers.com/xposed/modules/app-storeprefs-t3306801) is a new module by @stirante which prevents apps from auto-updating and warns te user on manually updating if the new version of an app is incompatible with an enabled Xposed module. It seems pretty straightforward to implement and should require nearly no effort to maintain once implemented.
If you want, I will try it myself and submit a pull request when I'm done, just tell me if you'd prefer that :)

By the way, thanks to you guys for keeping this awesome module alive!

**Comment by esgie** [comment]
Why not ;)

**Comment by PwnicornDev** [comment]
I'm closing this since StorePrefs is dead and the new hook update method makes it pretty much unnecessary anyways. Thanks for your continued efforts jeeping this awesome module alive :)
