### ISSUE TITLE
Auto looping 

### ISSUE THREAD

**Issue by sonejizrelax** [pylerSM/YouTubeBackgroundPlayback#116]
I would love to have the possibility to let it automatically loop a certain video in the background. Many thanks! Love the app!!

**Comment by esgie** [comment]
This module concentrates only on enabling the background playback feature
which already exist in the code, so at least for now no such a features
will be added.
Please also note that loop feature was even unavailable on desktop YouTube
until last month (without some browser addons or workarounds like creating
one-video playlist).
That is why I feel they'll introduce it into the Android version soon, too.

pzdr
es

I would love to have the possibility to let it automatically loop a certain
video in the background Many thanks! Love the app!!

—
Reply to this email directly or view it on GitHub
<https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/116>.

**Comment by sonejizrelax** [comment]
Okay thanks for your help!! Still love the app! Couldn't live without the mod 😂 
On 9 Feb 2016 5:44 am, esgie <notifications@github.com> wrote:This module concentrates only on enabling the background playback feature
which already exist in the code, so at least for now no such a features
will be added.
Please also note that loop feature was even unavailable on desktop YouTube
until last month (without some browser addons or workarounds like creating
one-video playlist).
That is why I feel they'll introduce it into the Android version soon, too.

pzdr
es

I would love to have the possibility to let it automatically loop a certain
video in the background Many thanks! Love the app!!

—
Reply to this email directly or view it on GitHub
<https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/116>.
