### ISSUE TITLE
Is video loaded as well?

### ISSUE THREAD

**Issue by BramVanroy** [pylerSM/YouTubeBackgroundPlayback#117]
I am simply wondering if, when running in the background, de video is also downloaded. Or is the app smart enough to only download the audio track? (I'm not even sure that's possible. Probably not. I just thought it'd be nice for us mobile users.)

**Comment by esgie** [comment]
So ure asking about the bandwidth usage when in background.
Hmm I dont really know.
Maybe someone can perform some tests or something?

pzdr
es
8 lut 2016 20:54 "Bram Vanroy" <notifications@github.com> napisał(a):

**Comment by rahul003** [comment]
By playing a few HD videos in background, I observed that it only downloads ~3MB for a video song. So it looks like only the audio is being downloaded. Curious does this use the YouTube red music playback feature in anyway, or was this only-audio download working even before YouTube introduced the music playback option.

**Comment by esgie** [comment]
The background playback code had been present even before first release of this module, although it wasn't triggered until the introduction of YouTube Red.
So it had probably been planned to work this way from the beginning.
Also it is a very good information that the background playback does not consume more bandwith than needed for audio playback. Thank you for checking it.
