### ISSUE TITLE
New update youtube 11.04.55

### ISSUE THREAD

**Issue by YOGaKrite** [pylerSM/YouTubeBackgroundPlayback#118]
http://www.apkmirror.com/apk/google-inc/youtube/youtube-11-04-55-arm-480dpi-android-apk-download/

**Comment by esgie** [comment]
This build is not proguarded so should be still compatibile with the recent
module.

pzdr
es
12 lut 2016 21:06 "YOGaKrite" <notifications@github.com> napisał(a):

**Comment by YOGaKrite** [comment]
it didn't work on my note 4 so i had to reinstalled the previous youtube version 11.03.54 and it is now working fine. thanks

**Comment by esgie** [comment]
Hmmm

Ok. I will check this specific build you posted in spare time tomorrow.

pzdr
es
13 lut 2016 16:59 "YOGaKrite" <notifications@github.com> napisał(a):

**Comment by Manuel1948** [comment]
For me  YT 11.3.54 is also Not Working :( (OnePlus One)

**Comment by esgie** [comment]
Again, I have tested with 11.04.55 build posted above and I am still pretty sure that YouTubeBackgroundPlayback 1.8.4 IS working very good with it.
Can you post the xposed log?

**Comment by Manuel1948** [comment]
Hi, I only see 1.8.1 as last version. So the problem is, that i do not have
the last version.

Why is the Xposed store on an old version?

Kind Regards,
Manuel Himmler
Am 15.02.2016 14:04 schrieb "esgie" <notifications@github.com>:

**Comment by esgie** [comment]
Sometimes Xposed installer get stuck with updates of some modules. It's an issue of Xposed Installer.
Just clear the data of Xposed Installer and re-enable all the modules.
And you can always check for the new version manually here:
http://repo.xposed.info/module/com.pyler.youtubebackgroundplayback

**Comment by YOGaKrite** [comment]
http://pastebin.com/kXzDsAW4
http://webm.host/6bb09/

**Comment by esgie** [comment]
I can see nothing related to this module. Only YouTube AdAway entries.
What exact version of the YouTubeBackgroundPlayback are you using?
Are you sure that xposed installer hasn't stuck on displaying the update like in @Manuel1948 case?

**Comment by YOGaKrite** [comment]
oh ok i reinstalled the module through the website and it works fine now. Thanks.

**Comment by Manuel1948** [comment]
Thank you for the quick reply.
Am 15.02.2016 17:55 schrieb "esgie" <notifications@github.com>:
