### ISSUE TITLE
Not obfuscated release

### ISSUE THREAD

**Issue by pylerSM** [pylerSM/YouTubeBackgroundPlayback#119]
Hello, does anybody have " 11.01.53 Google Play version " which has no obfuscation? :)

**Comment by esgie** [comment]
http://www.apkmirror.com/apk/google-inc/youtube/youtube-11-04-55-arm-480dpi-android-apk-download/

This is not exactly 11.01.53, but the most recent one, still deobfuscated
though.
They release obfuscated/deobfuscated revisions in some random pattern (ie.
i am receiving proguarded builds from the Play Store on my mobile, while
still receiving not proguarded on my tablet...) which i won't be even
trying to understand.

pzdr
es
13 lut 2016 11:03 "pyler" <notifications@github.com> napisał(a):

**Comment by pylerSM** [comment]
Do you know whether Youtube Music is obfuscated or not?

**Comment by pylerSM** [comment]
Okej, sources guys: http://www37.zippyshare.com/v/OsjYIhXo/file.html


Are we gonna start to work on Offline Playback, Ads removing, Resolution Max, Default tabs? :D
