### ISSUE TITLE
update

### ISSUE THREAD

**Issue by reyscott1968** [pylerSM/YouTubeBackgroundPlayback#122]
youtube app updated

**Comment by esgie** [comment]
11.04.56 is fully supported with 1.8.5.
11.05.55 has been released in non-proguarded variants so far so it is supported with 1.8.5, too.

**Comment by bukhamsin** [comment]
When should it hit xposed? I still didn't receive the update.

**Comment by brusyev** [comment]
I do not see 1.8.5 being available for download.

**Comment by pylerSM** [comment]
Module update is not required if non-protected (non-proguarded) release.

**Comment by brusyev** [comment]
So I do not need 1.8.5 for Play version 11.04.56?

**Comment by reyscott1968** [comment]
the update doesnt allow me to allow youtube background playback
updated as of 2/162016

**Comment by esgie** [comment]
I do not really know why the updates stuck sometime in Xposed Installer.
I can see 1.8.5 in repo absolutely without any problems.
I recommend clearing Xposed Installer data, refresh module list and re-enable all the modules.
Also you can always download the latest version from here:
http://repo.xposed.info/module/com.pyler.youtubebackgroundplayback

**Comment by bukhamsin** [comment]
Thank you, clearing xposed cache made the update appear.

**Comment by reyscott1968** [comment]
thats it. can be closed now
