### ISSUE TITLE
v1.8.5 doesn't seem to work for me

### ISSUE THREAD

**Issue by sen2** [pylerSM/YouTubeBackgroundPlayback#123]
This version should support the running yt version 11.04.56 on my phone, but for some reason it doesn't.
I am not sure what the prerequisites are (didn't find them here), for instance, my phone (android 5.1.1. S6 Edge Plus) is not rooted.

I tried couple times to reinstall and rebooting the device again but nothing seems to work.
As soon as I press home button, yt stops streaming
Thanks guys!

**Comment by esgie** [comment]
Xposed Framework is required to run the module.
Installation of Xposed may be NOT trivial for beginner users (especially on  Samsung devices which require special version) and it requires ingerention in the system, including flashing custom recovery.
It may also result in tripping Knox flag (= warranty void).
Please search on xda for details.

**Comment by sen2** [comment]
many thanks esgie for your reply
