### ISSUE TITLE
YouTube version 11.04.56 not working 

### ISSUE THREAD

**Issue by SolidSnakeAJ** [pylerSM/YouTubeBackgroundPlayback#125]
On 6.0.1 with xposed (N5X)
The xposed logs show "your version of the YouTube app is not yet supported". 

Either turning screen off or pressing home button stops playing the video. However other modules work, so it might not be related to xposed.
Same goes for the module that is certainly loaded. ("loading class xxx and loading modules from xxx" with no errors)

Anything I can do?
Thanks for your wonderful work.
Thanks for your help.

**Comment by SolidSnakeAJ** [comment]
I forgot to mention, xposed v80 and module v1.8.4

**Comment by esgie** [comment]
Just update the module to 1.8.5!
If the update isn't shown in xposed installer you should clear its data. Please read this topic for more info:
https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/122

**Comment by SolidSnakeAJ** [comment]
Indeed, clearing data fixed it and made the update appear.
Sorry for the duplicate.
