### ISSUE TITLE
No notification shown

### ISSUE THREAD

**Issue by Deaddecoit** [pylerSM/YouTubeBackgroundPlayback#126]
Youtube version 11.04.56 and Module version 1.8.5  (all latest)

No Notification is shown. FYI, I have changed build prop to Android 5.0.0 (mine's jellybean 4.2.2)

**Comment by esgie** [comment]
Please note that the most recent YouTube is 11.05.55. You can download it on apkmirror.com.
However you must have received obfuscated version of 11.04.56 which may be not supported as i haven't seen one in the wild yet.
Can you please post your youtube apk file?

**Comment by Deaddecoit** [comment]
I've downloaded the 10.05.55 as you said from ApkMirror. ( http://www.apkmirror.com/apk/google-inc/youtube/youtube-11-05-55-release/youtube-11-05-55-3-android-apk-download/) 

I restarted my phone after unchecking the module and checked it again. The case wasn't solved. 

Still no notification shown.

**Comment by Mayurmirwani** [comment]
Am using youtube version 11.04.56 and module version 1.8.3 and am facing same problem :(
