### ISSUE TITLE
Bug and feature

### ISSUE THREAD

**Issue by TheDarkEyed** [pylerSM/YouTubeBackgroundPlayback#128]
1. ‘Previous’ and ‘next’ buttons [notification bar] don't work!
2. Notification panel priority should be set manually.

Thanks!

**Comment by esgie** [comment]
1. They do work perfectly when playing a playlist, don't they? This is how it was designed.
2. What do you mean? I have a tiny cross "x" in the upper right corner of the notification and I can easily dismiss the notification and close the background play.

**Comment by TheDarkEyed** [comment]
❌ button works fine but ⏪ & ⏩ buttons don't respond.
