### ISSUE TITLE
Problem with the notification

### ISSUE THREAD

**Issue by skizz98** [pylerSM/YouTubeBackgroundPlayback#129]
I have just tried running this module with some version of YouTube (from 11.01.53 to 11.06.54) and I get always the same problem: instead of the Background Player notification I get one of Youtube Red saying "With YouTube Red you can play videos in background: change you settings in the app" or something similar. Videos are still played in background but I can't have the control notification back. I'm using the 1.8.5 version of the module on Android 6.0.1

**Comment by esgie** [comment]
This is interesting one...
AFAIR when i played YouTube video along with the YTBP module for the first time, it asked me if I want to enable background playback in a popup window. I selected "yes".
Maybe you have selected "no"?
This option may not be easy to change after that, as the setting is not visible in the menu at all.
I think that cleaning YouTube data should be helpful.
Then, after running background playback for the first time it might ask you again, so choose to enable background playback then.
Please report back if possible.
Thank you.

**Comment by skizz98** [comment]
I tried with your method but It didn't work. 
Then I tried to uninstall both YouTube and module and then reinstall them in few different way (the app before the module,  vice versa, from play store and from apkmirror, etc) but it didn't work too.
I also tried to install 1.7.6 version of the module with YouTube 10.49.59 but it's not working.
I hope to find a fix and in that way I'll try to be useful for you

**Comment by esgie** [comment]
Ok.
Before I try to look into the code I have thought of two options:
1) try to disable all the notifications in YouTube settings
2) maybe it's some kind of ad? Did you try to combine it with YouTube AdAway module by Wanam?

**Comment by skizz98** [comment]
I tried both methods but they did't work out. 
Now I've installed the latest version of Youtube from APKMirror (11.07.59 Arm 320dpi) and I'm keep facing the same issue.
![screenshot_20160303-181534](https://cloud.githubusercontent.com/assets/15785157/13540954/bd711b92-e259-11e5-84f2-a1162810c428.png)
![screenshot_20160303-181558](https://cloud.githubusercontent.com/assets/15785157/13540955/bd75ad88-e259-11e5-8ef8-2905cae97ce7.png)

**Comment by esgie** [comment]
And after clicking "ok" nothing changes, hm?
I may not see it because I live in a country with no YouTube Red support.
I'll check deeper and be back.

**Comment by skizz98** [comment]
Yes. If I click "ok" or I just ignore the message, it never reappears again. 
P.S. I noticed only today that in the app's settings there is no more the "YouTube Red" section: the one in which I should have been able to set up the background playback offered by YouTube Red
