### ISSUE TITLE
bg-playback issue with a video

### ISSUE THREAD

**Issue by freddie46** [pylerSM/YouTubeBackgroundPlayback#131]
everything works perfectly, except for some videos (not all of them) of a channel.
I just noticed it, you can try for yourselves, the channel name is "Shapeless Sphere".
Most of the songs stop playing when I put youtube in bg, while the "full album" video hasn't this problem.

**Comment by esgie** [comment]
Cannot reproduce the error.
You sure that videos didn't just stop streaming due to low bandwidth?

**Comment by freddie46** [comment]
yes, I'm sure :)
I tried in different times and conditions (my lte and 2 different wifi connections). Once the playing stops, if i pull down the notification bar i can see an exclamation mark instead of the play/pause button in the youtube bg box. 
Anyway if this happens to me only, it's really no big deal, as I'm able to play 100% of the other yt videos in background.

**Comment by freddie46** [comment]
just to be extremely precise, this video keeps playing --> https://youtu.be/cR5EGkpge7Y
while this one (and few others) stops -->  https://youtu.be/StE2vCxd6a8
