### ISSUE TITLE
Feature request - support for YouTube music

### ISSUE THREAD

**Issue by ConfessedCandy** [pylerSM/YouTubeBackgroundPlayback#134]
Would it be possible to make this also work with the YouTube music app because it would be useful to listen to music without having the app opened

**Comment by Steve5451** [comment]
I too would love this. Support for offline mixtape as well please. Would it be easy just to make yt music think you've got YouTube Red?

**Comment by pylerSM** [comment]
@iHelp101 @esgie guys, did you check it? :)

**Comment by layanto** [comment]
Support for YouTube please
