### ISSUE TITLE
Notification design issues

### ISSUE THREAD

**Issue by pcroland** [pylerSM/YouTubeBackgroundPlayback#135]
Can i suggest that the color of module's notification equals with the system color?
As you can see: http://i.imgur.com/8ho86VP.png , the grey color doesn't really meet the Flux White theme :( If I use the YouTube notification seek bar [L-M] module I can set the color of the notification, but can't set the color of the texts.

And the top of the notification you can see a 3px margin and a 1px margin on the bottom which I find annoying.

And if I click on any of the notification buttons the highlight will be blue which is totally different from everything else.

**Comment by iHelp101** [comment]
@pcroland The module does not create the notification. YouTube creates the notification, which to my knowledge is based on material design. Material design only allows notifications to be black on white. In terms of the margin issue that is Youtube's issue. The highlight issue is Youtube as well.

**Comment by pcroland** [comment]
@iHelp101 So should I suggest those design modifications to the YouTube notification seek bar [L-M]'s developers? And basicly YouTube Red users whould have those "bugs" as well in spite the payd for it? :S

**Comment by iHelp101** [comment]
@pcroland You can suggest it to the developer of that module. After looking at the module it appears they have a way of editing the background color of the notification. I was unaware of this ability. In terms of this being a bug for official YouTube Red users I believe this is the case.

**Comment by pcroland** [comment]
@iHelp101 Well, thanks for the quick replies, I will suggest them :D
