### ISSUE TITLE
YouTube 11.10.57 on lollipop 

### ISSUE THREAD

**Issue by 7ala** [pylerSM/YouTubeBackgroundPlayback#136]
The 1.8.8 module version is not working with the latest version of YouTube (11.10.57) on lollipop, and I can't stay without it.
Please update the module.

**Comment by giokupreishvili** [comment]
Same Problem, Please Update Module.

**Comment by esgie** [comment]
Sorry for being lazy this time, it won't happen again ;)
1.8.9 is up in the repo.
26 mar 2016 21:33 "giokupreishvili" <notifications@github.com> napisał(a):

**Comment by giokupreishvili** [comment]
Thanks :)

**Comment by 7ala** [comment]
Thanks
