### ISSUE TITLE
YouTubeBackgroundPlayback.java update?

### ISSUE THREAD

**Issue by socraticbliss** [pylerSM/YouTubeBackgroundPlayback#137]
Hi,

The java file hasn't been updated in quite a while (I was trying to learn how you guys did it to help me with developing other Xposed mods), so I just ended up de-compiling the APK and looking at it from there, seems like the java source file is a bit out of date, could you guys upload the latest? If not, I can commit my version that has all the new values...

Thanks again :)

**Comment by iHelp101** [comment]
I personally don't have the updated version. @esgie would need to upload it. Do you have any specific issues with the module you are developing? I am glad to help you out.

**Comment by socraticbliss** [comment]
Well it looks like there has been some changes since the last upload (according to the decompiled version)...

The logic for the de-obfuscated version is now removed, along with the de-obfuscated specific methods, which I guess makes sense since most people will be upgrading their YouTube applications... and of course the new versions methods/classes names

I was basically looking at your mod as a kind of tutorial to see how one goes about changing a parameter/variable in a stock file, kinda easing my way into the whole Xposed thing, as I will be trying to create something for the Moto devices to allow them to use some of the features that the future phones have already (Chop Chop gesture and Lift gesture for Moto Actions)

If I have further questions I'll be sure to bug you about it :)

**Comment by esgie** [comment]
I will upload actual values today.

pzdr
es
27 mar 2016 22:08 "socraticbliss" <notifications@github.com> napisał(a):

**Comment by esgie** [comment]
updated
