### ISSUE TITLE
Not working with youtube 11.13.56

### ISSUE THREAD

**Issue by zhoubug** [pylerSM/YouTubeBackgroundPlayback#142]
Not working with youtube 11.13.56.

**Comment by jakky567** [comment]
It is not working with 11.13.56 or 11.13.55 for me as well for the 1.8.14 or 1.8.13 update. Whenever I exit the video, audio stops, and the video skips to some time beyond the length of the video (i.e. 27:03:13), then to the last few seconds of the video when I reenter youtube. Also, I get the sign up for youtube red notification.

**Comment by kovasp** [comment]
Agreed using the same config as above post doesn't seem to work

**Comment by HaoCherHong** [comment]
Same, using version 1.8.14 and YouTube 11.13.56, not working.
OS: Android 5.0.2
Model: ASUS_Z00LD

**Comment by esgie** [comment]
I will look into the issue this weekend.
Btw can you please post your YouTube apk files? There may be some
differences between builds...

pzdr
es
22 kwi 2016 12:13 "Hao-Cher Hong" <notifications@github.com> napisał(a):

**Comment by HaoCherHong** [comment]
[base.zip](https://github.com/pylerSM/YouTubeBackgroundPlayback/files/232150/base.zip)

**Comment by kovasp** [comment]
What version is it?

**Comment by ianmacd** [comment]
Not working on my S7 Edge with YouTube 11.16.62 and YTBP 1.8.15.

**Comment by freddie46** [comment]
Hi, I solved issue with 11.13.56 not working by moving YouTube app from /system to /data and uninstalling/reinstalling
