### ISSUE TITLE
"Connection to server lost. Touch to retry” Issue.

### ISSUE THREAD

**Issue by njeri123** [pylerSM/YouTubeBackgroundPlayback#145]
It makes me crazy. I deleted the app and the mod but without success. Sometimes i can watch hours without problem but then it suddenly comes. I can fix it just with a phone reboot. i try almost every version. I try "cache clear", "data clear" etc. without success.

**Comment by CoCoKasper** [comment]
I have this issue for the last few months on ALL versions of mod and YouTube.  It makes the mod garbage and worthless to me. 
How can we fix this issue? Sometimes it works for a day, but most of the time as soon as I go into background playback it says "no connection" or "connect error click to retry."

**Comment by njeri123** [comment]
I change the DNS to google DNS on my phone and i uninstall Youtube AdAway and Yourtube, but without success. The mod is really useless with this issue.

**Comment by th3an7** [comment]
It works on mine... waht device do you have? Android version, YT app version?

**Comment by njeri123** [comment]
I have Android 6.0 Build-Number: 32.1.A.1.163

My phone is a Sony Xperia Z5 Compact Modelnumber: E5823
The App-Version is: 11.29.55 but i have this issue with all versions of YT.

2016-08-21 20:35 GMT+02:00 Łukasz Ordon <notifications@github.com>:

**Comment by th3an7** [comment]
IDK... try factory reset your phone, maybe it will help.

**Comment by CoCoKasper** [comment]
I have the issue on all 4 of my android devices with Roms based on lollipop or Marshmallow.
Galaxy S3/S4/S5 & Alcatel Onetouch fierce XL 
Any of the YouTube version's for the past 9 months give me this issue.

**Comment by th3an7** [comment]
On mine it happens only on reboot but when I wait a minute or two it's OK. I think that's Google fault...
They are changing YT app code lately...

Can you try uninstalling Xposed Framework completely (using uninstaller .zip)?

**Comment by njeri123** [comment]
@CoCoKasper Can you give me your App-List? Maybe we have same Apps who
makes conflict. (Maybe Lucky Patcher or apps like that which are known for
problems)

2016-08-22 17:30 GMT+02:00 CoCoKasper <notifications@github.com>:

**Comment by th3an7** [comment]
@njeri123 I have Lucky Patcher installed too and it works... I guess it may be some kind of host blocker od ad blocker...

**Comment by CoCoKasper** [comment]
I don't use lucky patcher, but i do have xposed mods "ad blocker" and "YouTube ad away"

**Comment by th3an7** [comment]
@CoCoKasper Try uninstalling them and clearing YT app data (remember to reboot phone after uninstalling modules)

**Comment by njeri123** [comment]
I haven't "ad blocker" and i tested the mod 1 week without "Youtube Ad
Away" but same issue.

2016-08-22 17:46 GMT+02:00 CoCoKasper <notifications@github.com>:

**Comment by th3an7** [comment]
So it could be Google's fault... Try sending them feedback (which they probably don't read) or going to they products forum and posting something there...

**Comment by njeri123** [comment]
I try many times "clear data" and even re-flashing gapps but without
success.

2016-08-22 17:48 GMT+02:00 Łukasz Ordon <notifications@github.com>:

**Comment by th3an7** [comment]
What about deleting Google accounts from phone and adding them again?
Deleting Google Play services app data could help too...

**Comment by njeri123** [comment]
I don't think is a google fault because YT works without the mod. I try to
delete the Google Play services app data before i reflash the gapps.

2016-08-22 17:52 GMT+02:00 njeri123 . <njeri12345@gmail.com>:

**Comment by th3an7** [comment]
So I don't know... everything works here...

**Comment by CoCoKasper** [comment]
Maybe greenify is causing issue?

**Comment by njeri123** [comment]
Wow i was writing the same question right now o.O

**Comment by njeri123** [comment]
Do you have the donate version? I could not find YT.

**Comment by njeri123** [comment]
greenify isn't i uninstall and reboot. still same issue.

Am 22.08.2016 18:49 schrieb "njeri123 ." <njeri12345@gmail.com>:

> Do you have the donate version? I could not find YT.
>

**Comment by CoCoKasper** [comment]
Yea i tried on my GS4 after a factory reset, without greenify. Same issue.  I only have this problem on android 5.x.x and up...

**Comment by njeri123** [comment]
Do you restore your apps before trying? Maybe "3C Toolbox" makes trouble?

Am 22.08.2016 19:12 schrieb "CoCoKasper" <notifications@github.com>:

**Comment by CoCoKasper** [comment]
Here's my app list on my Galaxy S5 
AdBlocker
	pl.cinek.adblocker
AlarmDroid
	com.splunchy.android.alarmclock
Angry Birds
	com.rovio.angrybirds
Chrome
	com.android.chrome
CM Backup
	com.ijinshan.kbackup
Device Id Changer Free
	com.phoneinfo.changer
Drive
	com.google.android.apps.docs
DroidEdit
	com.aor.droidedit.pro
EFS Backup
	ma.wanam.efs
ES File Explorer
	com.estrongs.android.pop
Exiles Free
	com.crescentmoongames.exilesfree
FlyingCross
	appinventor.ai_CoCoKasper.Flying_Cross
Gmail
	com.google.android.gm
Goggles
	com.google.android.apps.unveil
Google Voice
	com.google.android.apps.googlevoice
GravityBox [MM]
	com.ceco.marshmallow.gravitybox
Greenify
	com.oasisfeng.greenify
Hangouts
	com.google.android.talk
Hardware Info
	com.dama.hardwareinfo
iFont
	com.kapp.ifont
Imei Tweak
	com.tweaker.imei
Intelli3G
	com.voidvapps.intelli3g
IP Tools
	com.ddm.iptools
IR Remote
	com.freeiruniversalremote
List My Apps
	de.onyxbits.listmyapps
Maps
	com.google.android.apps.maps
MX Player
	com.mxtech.videoplayer.ad
Notepad
	com.callsoft.notes
Nova Launcher
	com.teslacoilsw.launcher
Nova Launcher Prime
	com.teslacoilsw.launcher.prime
OfficeSuite
	com.mobisystems.editor.office_registered
Photon Browser
	com.appsverse.photon
Photos
	com.google.android.apps.photos
PICmicro Database
	it.android.demi.elettronica.db.pic
Pinout
	com.vouilloz_d.android.pinout
Pocket Legends
	sts.pl
QuickShortcutMaker
	com.sika524.android.quickshortcut
Smart Tools
	kr.aboy.tools
SuperSU
	eu.chainfire.supersu
SuperSU Pro
	eu.chainfire.supersu.pro
Swype + Dragon
	com.nuance.swype.dtc
TeamSpeak
	com.teamspeak.ts3client
TeamViewer
	com.teamviewer.teamviewer.market.mobile
Terminal Emulator
	jackpal.androidterm
Titanium Backup
	com.keramidas.TitaniumBackup
Titanium Backup PRO
	com.keramidas.TitaniumBackupPro
Translate
	com.google.android.apps.translate
VirtualAmp
	ix.com.android.VirtualAmp
Where's My Droid
	com.alienmanfc6.wheresmyandroid
WiFi Map
	io.wifimap.wifimap
Xposed Installer
	de.robv.android.xposed.installer
YouTube
	com.google.android.youtube
YouTube AdAway
	ma.wanam.youtubeadaway
YouTube Background Playback
	com.pyler.youtubebackgroundplayback
YouTube Music
	com.google.android.apps.youtube.music
YouTube notification seek bar [L-M]
	com.ssrdroide.youtubenotificationseekbar
Zedge
	net.zedge.android

**Comment by njeri123** [comment]
I have to:

MX Player
ES File Explorer
Office Suite
Photon Browser
Titanium Backup
YouTube AdAway
YouTube Background Playback

Maybe isn't enough to uninstall YT AdAway. Maybe we should a clean way to
remove YT AdAway because my guess is this YT AdAway Mod which broke YT App.

**Comment by njeri123** [comment]
I have the SOLUTION. First disable AdBlocker and after uninstall it. Same with YouTube AdAway. After that go to system\etc and rename "hosts". Don't use AdBlocker apps! You can use AdBlock Browser to surf. I find out that in other apps like OGYoutube i have the same issue, so i don't search the problem in the YT app or in the mod. Have fun.

**Comment by njeri123** [comment]
I have the problem again....
