### ISSUE TITLE
[maybe solved]  issue w/ 11.13.56 not working

### ISSUE THREAD

**Issue by freddie46** [pylerSM/YouTubeBackgroundPlayback#149]
Hi, dunno if this is the right place to write it, but maybe it can somehow of help.
Here's what: I'm on unofficial temasek CM13 on a galaxy Note 3 (hlte), I flashed openGapps mini package. At first YouTube did not work in bg, with no sign of life by BG player.
I tried to update with a newer version from apkmirror but got no results.
Then I removed YouTube from /system partition to /data, then I uninstalled and reinstalled, and it worked.
Now my question is: was it a known issue? It seems strange to me, since until now every version worked on my device, whether it was installed in system or in data.
Sorry for the long post, thanks.

**Comment by humzaibrahim** [comment]
Hi there, 
I have a Oneplus 2 running oxygenos 2.2.1 (based on andorid 5.1.1). is there a way to move Youtube to the data section from system without rooting?
Thanks
