### ISSUE TITLE
Tiny Tweak Required

### ISSUE THREAD

**Issue by Eisa-AlAwadhi** [pylerSM/YouTubeBackgroundPlayback#15]
Hello,
Thank you for the best Xposed Module ever!
Works perfectly on S5 running CM12.

However,
There's this needed tweak because:

The background play notification doesn't show when I press the home button and go to home. The notification shows when I enter YouTube again after pressing the home button.

Will it be possible to show it immediately when the video starts or to show when pressing the home button immediately? And thanks!

Kind regards,
Eisa AlAwadhi

**Comment by pylerSM** [comment]
Download 1.2.

**Comment by Eisa-AlAwadhi** [comment]
Wow it works flawlessly!
