### ISSUE TITLE
Non-rooted devices

### ISSUE THREAD

**Issue by humzaibrahim** [pylerSM/YouTubeBackgroundPlayback#150]
Will this work on non-rooted devices?

**Comment by th3junk13** [comment]
No, this is an Xposed module which cannot be installed without root access.

**Comment by Bec-de-Xorbin** [comment]
Are you sure? I haven't grant it root access and it's working fine.

**Comment by humzaibrahim** [comment]
What YouTube version do you have? Mine doesn't work?

On 5 May 2016, at 1:38 am, Bec-de-Xorbin <notifications@github.com<mailto:notifications@github.com>> wrote:

Are you sure? I haven't grant it root access and it's working fine.
