### ISSUE TITLE
Version 1.3.1 not working

### ISSUE THREAD

**Issue by SoulFier** [pylerSM/YouTubeBackgroundPlayback#16]
I have a Samsug galaxy S3 with Cyanogenmod 11 and the proper version of YouTube installed same fore the background payback app but nothing works. 

PS: It worked before for three to four updates.

**Comment by GijsTimmers** [comment]
What do you mean with 'Nothing works'? Does normal YouTube playback work? What about screen off playback?

**Comment by wilco375** [comment]
I have the exact sme problem. Neither background nor screen off playback work. (In other words, it makes no difference having the module enabled vs disabled) 
I'm running a CM12 based ROM on the Moto G 2013

**Comment by pylerSM** [comment]
So uninstall module please since I can't fix it. Or buy Music Key.

**Comment by wilco375** [comment]
NVM, a reïnstall fixed it

**Comment by GijsTimmers** [comment]
@BmanDesignsCanada 's merged pull request didn't solve it for me; could you please re-open this issue?
