### ISSUE TITLE
Can module build from source be uploaded here?

### ISSUE THREAD

**Issue by th3an7** [pylerSM/YouTubeBackgroundPlayback#160]
It's not really an issue but as in title - can this module be uploaded here in comments so people won't have to wait for updates on Xposed repo? As in changelog in repo - "Support for yt 11.16.62
Sorry for late update - I do not have much time atm!".
I can build apks and attach them here so you can just post it anywhere or upload to Xposed repo...

PS: I don't know how to change apk version build from source to be the next one (ex. on repo there is 
1.8.16 and if I build it in Android Studio it shows 1.5.0-develop) so you may edit this :P

PS2: Just asking for privilege now so it's just text (no files attached). If not, just close or delete this issue.

**Comment by pylerSM** [comment]
Yes, tell me your XDA nick and I can add you as maintainer to Xposed repo.

**Comment by th3an7** [comment]
It's "Th3 Ant". Here is my profile link 
http://forum.xda-developers.com/member.php?u=5185525

**Comment by pylerSM** [comment]
Please try to log in on Xposed repo page.. Probably we need you user id to add you.

**Comment by th3an7** [comment]
Done :)

**Comment by pylerSM** [comment]
You are in! :)

**Comment by th3an7** [comment]
Thanks :D
Well... last APK I bult was not signed (no key store paths etc.) so there shouldn't be a problem with signature mismatches (I guess).
