### ISSUE TITLE
Stable versions (1.8.17 and 1.8.18) install issues

### ISSUE THREAD

**Issue by sharky127** [pylerSM/YouTubeBackgroundPlayback#163]
So the stable issues download fine but refuse to be installed on top of the 1.8.16. Tried directly through Xposed and XDA Labs with no avail. Any one else facing same issues?

Moreover, tried to install the apk manually, and failed once more.

**Comment by th3an7** [comment]
removed... will need more testing... on my side they were installing fine ;P

**Comment by th3an7** [comment]
one more thing... have you tried clean installing (uninstalling old module and then installing new one)?

**Comment by sharky127** [comment]
Okay, removed the module completely, but couldn't install the 1.8.18 one through XDA Labs (error parsing the package). Installed the apk manually and it worked. Thanks for the help!

**Comment by th3an7** [comment]
Yeah, XDA Labs app sometimes gives Parsing error... glad it eventually works :)
