### ISSUE TITLE
New version...

### ISSUE THREAD

**Issue by TheC92** [pylerSM/YouTubeBackgroundPlayback#164]
Do I need to install the new version after deleting the old version?

http://i.imgur.com/iRQb0na.png
http://i.imgur.com/J83vzJE.png

**Comment by sharky127** [comment]
Yeah, had the same issue, just recently closed it.

**Comment by th3an7** [comment]
Installing on top of the old version gives error? Like error while parsing the package or sth? I'll try to check that signature tomorrow.
