### ISSUE TITLE
(Suggestion) Notification X Stops Playback

### ISSUE THREAD

**Issue by abqnm** [pylerSM/YouTubeBackgroundPlayback#17]
First, I want to say thanks for the great module. I like the feature and it works great, and I don't mind that there is a small delay when starting playback, as it seems others have issue with. Thanks for the great work! 

Now, for my suggestion, it would be with the notification. The notification is very much appreciated and very handy, so thanks for that. I would suggest, though, that if a video is playing, tapping the "X" in the upper right of the notification should also stop playback. 

With other music app notifications, tapping the "X" stops playback and dismisses the notification. By having it not stop playback but still dismissing the notification, now the notification is gone and the only way to stop playback is to re-enter YouTube, or dismiss it from the overview (task switcher), closing YouTube completely. 

If this is something you can implement, I feel it would be a great UX change to the notification. It would also mean I don't keep losing the notification with videos still playing and no simple way to control them. I can't get used to the fact that the "X" doesn't stop playback like media players so I keep losing the notification. I believe this minor change would bring the notification more in line with what a traditional music app's notification would be. 

In the alternate, if you are unable or do not wish to implement this change as I have proposed it, could the notification be changed so that it is "ongoing," and therefore cannot be dismissed, until playback has been stopped? At least this will prevent dismissing the notification while playback is still in progress. 

Thanks again and I do hope you consider this suggestion. 

Cheers,
abqnm

**Comment by pylerSM** [comment]
Yes, this is the last unresolved issue.

**Comment by abqnm** [comment]
Fantastic, @pylerSM. Thank you. 

If you are in a country where the Play Store is supported, you should offer a donate package (or packages of different amounts) on the Play Store. I would certainly throw a few $ your way. I always like to support the devs. I just wish some of them didn't accept only PayPal, as they and I have a rocky relationship for typical "PayPal is a terrible company" issues. 

Anyway, thanks again and I look forward to the update one day where this issue is addressed. 

Cheers!

**Comment by pylerSM** [comment]
I have some ideas how to do it. I hope one of them will work.
