### ISSUE TITLE
"App not installed." with 1.8.18

### ISSUE THREAD

**Issue by JustSmall** [pylerSM/YouTubeBackgroundPlayback#170]
Whenever I try to install 1.8.18 the installer or whatever it's called tells me 'App not installed.' and leads me back to the Xposed interface. I do have the latest Youtube version installed and I tried restarting the phone as well, which didn't help.

Thanks in advance.

**Comment by th3an7** [comment]
Did you tried 1.8.19?

**Comment by JustSmall** [comment]
I actually did not, I thought 1.8.18 was the latest so I didn't bother checking for updates elsewhere... Sorry about that.

However, I just tried to install it and got the same message.

**Comment by th3an7** [comment]
Can you please check if this one installs?

https://drive.google.com/file/d/0B8j7vCsf6RXcZGs2YWtDSEFRX0k/view?usp=sharing

**Comment by JustSmall** [comment]
So I tried installing that too and still got the same message.

I then completely uninstalled the previous version and installed the one you linked. This way it works now. Thanks for the help!

**Comment by bingoham** [comment]
How do you Uninstall previous versions?

**Comment by bingoham** [comment]
Never mind I got it

**Comment by carmeloamg** [comment]
I'm having the same isssue since 1.8.18 untill now 1.8.22. I was able to upgrade to the linked one unistalling my previous version but not anymore. I think another installed app is blocking the instalación (probably a google one). May it be possible? Could I fix it? Thanks and regards

**Comment by th3an7** [comment]
I'll try posting signed apk here...

Or you can try disabling checking APK signature in Package Installer. Try using Lucky Patcher - it can patch it to make it always true and disable it completly. This will fix the problem for now and for all apps with different signature. Doing that you could install new versions on top of the old with different signature.

Just tell me if you need new apk or if you patch it with Lucky Patcher

**Comment by carmeloamg** [comment]
Thank you I really appreciate your answer. Disabling the signature verification didn't work (I had tried before) but lucky patcher worked for me. Now succefully runing 1.8.24 from xposed installer download tab. Regards.

**Comment by seanrand** [comment]
Holy shit, @pylerSM, @th3an7 could you guys please finally sort out your package signing? Disabling signature checking with Lucky Patcher is not an acceptable answer. Every time a new (stable branch) version is released, I have to disable signature checking for the install with XInstaller. Thanks for all the work that goes into this, but seriously.

**Comment by th3an7** [comment]
It's already been sorted out. It one from like 3 or 4 versions straight.

**Comment by seanrand** [comment]
Hmm ok, sorry then. I'm pretty sure I got a conflicting signature error when updating from stable 1.8.28 to stable 1.8.29 though.
