### ISSUE TITLE
Stable and Beta branch distinction is ambiguous

### ISSUE THREAD

**Issue by bdemirci** [pylerSM/YouTubeBackgroundPlayback#175]
The latest version(s) write:
From now on, there will be probably 2 different verisons
one with notification visible all the time and
one with notification visible ony when YT is in background.
The one with notification visible will be set as BETA

It is not clear which one the BETA is. It just says, "The one with notification visible will be set as BETA"
Do you mean visible all the time, or visible in the background?

**Comment by th3an7** [comment]
Description has been fixed
