### ISSUE TITLE
YouTube 11.22.56 not supported yet.

### ISSUE THREAD

**Issue by D-a-v-i-d-13** [pylerSM/YouTubeBackgroundPlayback#180]
YouTube 11.22.56 has been released, but is unfortunately not supported yet.
Thanks a lot for your work!

**Comment by lobezno223** [comment]
endorsing this request. 
anyway, best xda module so far.

**Comment by th3an7** [comment]
repo updated... if there is a problem with "App not installed" or something like that - reply here

**Comment by Bec-de-Xorbin** [comment]
11.23.56 is the newest version.

**Comment by imlaius** [comment]
So youtube background works with the newest version but ads are shown again. Will this be fixed?

**Comment by D-a-v-i-d-13** [comment]
There's a separate Xposed module blocking YouTube ads.

**Comment by enes19** [comment]
not working on 11.23.56
lg g2

**Comment by CraigJSmith** [comment]
Working for me on 11.23.56 with a LG Volt 2
