### ISSUE TITLE
Next button working only with playlists

### ISSUE THREAD

**Issue by sarcus** [pylerSM/YouTubeBackgroundPlayback#181]
Hey, I noticed that the next song button is working only when a playlist is on. My request is to make it work with singles too, with the next button playing next suggested song, like in original app.

**Comment by h2559** [comment]
I agree, on a normal video the back and forward buttons dont work, i thought it was a bug until i searched online and read the above post. i tried it again and indeed the back/forward buttons only work on playlists. if you would make them work for all videos that would be great.

**Comment by shaktishekhar** [comment]
yes next previous not working
