### ISSUE TITLE
Not working on s6

### ISSUE THREAD

**Issue by ThtSubieGuy** [pylerSM/YouTubeBackgroundPlayback#188]
I have updated my YouTube to the latest version on Google play and i have updated module and nothing is working.

**Comment by sigv** [comment]
What YouTube version are you using?

**Comment by ThtSubieGuy** [comment]
11.23.56 and the newest version of the module 


Sent from my Sprint Samsung Galaxy S® 6.
-------- Original message --------From: Valter Jansons <notifications@github.com> Date: 6/30/16  1:32 AM  (GMT-07:00) To: pylerSM/YouTubeBackgroundPlayback <YouTubeBackgroundPlayback@noreply.github.com> Cc: ThtSubieGuy <deppe.collin.dba@gmail.com>, Author <author@noreply.github.com> Subject: Re: [pylerSM/YouTubeBackgroundPlayback] Not working on s6 (#188) 
What YouTube version are you using?

**Comment by ThtSubieGuy** [comment]
11.23.56 and the newest version of the module

**Comment by sigv** [comment]
Do you see _Could not enable background playback for the YouTube app. Your installed version of it is not supported._ in the Xposed Installer application's Logs section?

**Comment by ThtSubieGuy** [comment]
No Oh my gosh I'm very sorry. I didn't see that at all. I still don't see it but I'll take your word for it. I just started this whole root ordeal. Thanks I'll just downgrade my YouTube and my module. Thanks so much.

**Comment by sigv** [comment]
No, no! I did not mean it like that! I was asking for you to check if you see that message. The 11.23.56 YouTube app release should be supported by our latest changes in the codebase. Did you build the module yourself or did you download it from Xposed Repository?

**Comment by ThtSubieGuy** [comment]
No I didn't see the message. But i just downgraded my YouTube to 11.22.56 and my module is 1.8.23. I didn't build my own module. I downloaded it from Xposed.

**Comment by sigv** [comment]
Xposed module version 1.8.24 seems to work with YouTube version 11.23.56 on my bullhead (Nexus 5X). I am not sure why it fails for you..

Are you sure you had enabled the module and had rebooted?
