### ISSUE TITLE
11.26.55 version not supported

### ISSUE THREAD

**Issue by enes19** [pylerSM/YouTubeBackgroundPlayback#191]
pls up this apk

it is not work on my lg g2 d802 on 1.8.24 beta

**Comment by th3an7** [comment]
Updated, chceck if it's working

**Comment by enes19** [comment]
still not working

**Comment by th3an7** [comment]
I've just checked and... how is it possible that you have 11.26.55 YT? As far as I know, the latest one is 11.25.55 (as seen on apkmirror.com). If you really have 11.26.55, upload .apk somewhere so we could update the module

**Comment by enes19** [comment]
my nad i have 11.25.55 version apk 
and it is still not work

**Comment by enes19** [comment]
my bad*

**Comment by nessotrin** [comment]
Not working here either, on 11.25.55, Android 6.0 Ressurection Remix, Xposed V84, no notification at all, it's just as if the module wasn't installed, not even the first launch dialogue to explain the background system. I'm using the notification all the time version since the other one is not up to date (Impossible to update as I understood).

**Comment by nessotrin** [comment]
I backed up the APK using titanium backup, here it is, hope it helps !
https://framadrop.org/r/aGtkj8Xpcd#cc7nPVQ7L5n2VyeuRXBAtWqI3gI0Aanj66l+vn+g9Jk=

**Comment by th3an7** [comment]
The one you've linked is the same as the others... I don't know why it's not working. Any logs in Xposed  app or something? You have xposed flashed and the module is enabled I assume... phone was rebooted after module install, right?

**Comment by jgiard6** [comment]
Not working for me either.  On S5, Android 4.4.2, using YouTube 11.25.55.  Just stopped working randomly this morning.  Disabling & renabling hooks did nothing as did uninstalling & reinstalling the module with rebooting.

**Comment by nessotrin** [comment]
Oh, I juste checked the log and I noticed there was no signs of the module, so I checked and it was disabled, my bad ^^'
I had to uninstall the app before updating, I suppose it might be smart to add a little text that warns you to reenable the module if you uninstall.

**Comment by xbiggyl** [comment]
From what I understand the module is updated for version 11.25.55
But I can't find it on xposed

**Comment by jgiard6** [comment]
I was on the stable...migrating over to the beta fixed everything.  Thanks.

**Comment by th3an7** [comment]
@xbiggyl turn on beta channel in Xposed app. Go to Download, tap on the module and swipe to the right to Settings tab. Then choose Beta in "Versions to be shown".

**Comment by Intrainos** [comment]
I'm on YT 11.25.55 (Android 6.0.1 CM13). 1.8.25 is working.
