### ISSUE TITLE
Trick with notification visible only in background is not working anymore

### ISSUE THREAD

**Issue by th3an7** [pylerSM/YouTubeBackgroundPlayback#195]
Just to be sure, can someone please check if changing "e" to "f" (as it could be made before) is still working? I changed it as usual and the module is working only with "e". With "f" it's like it wasn't enabled.

Also - notification design has changed. It's now smaller, there is no video thumbnail and it has "x" button that closes it.

**Comment by ZeynK** [comment]
Any update on this? i actually prefer notification visible only in background, having it show all the time is pointless.

**Comment by th3an7** [comment]
Latest youtube 11.25.59 works again with this trick...
