### ISSUE TITLE
Xposed Repository is only showing Beta build for latest version.

### ISSUE THREAD

**Issue by stevedensmore** [pylerSM/YouTubeBackgroundPlayback#196]
I'm trying to find the latest stable version that doesn't keep the notification on at all times, and supports 11.25.55.

**Comment by th3an7** [comment]
As the one of the issues says... Google has changed notification design and the trick with modifying module code to make notification visible only in background is not working anymore (but we need to look into it more deeply). For now, there is only version with notification visible all the time.
