### ISSUE TITLE
App is not work with YouTube 11.25.55 in cyanogenmod 13 on Moto G XT1069 (TITAN)

### ISSUE THREAD

**Issue by ThiagoBezzy** [pylerSM/YouTubeBackgroundPlayback#197]
This version is not work in moto G with Cyanogenmod 13.

Thanks.

**Comment by Bandithklh** [comment]
Dfhuv

**Comment by Teldix** [comment]
Same Here! Thanks for your support

**Comment by edamazzio** [comment]
Also not working... Resurrection Remix ROM Android 6.0.1 running on OPO (bacon)

**Comment by th3an7** [comment]
Have you enabled module after installing? Xposed is working, phone was rebooted?

**Comment by kovanovic** [comment]
Not working for me either 11.25.55, Cyanogenmod 13, Xiaomi Mi 4C. Installed and enabled and rebooted several times since the last install, nothing helps.

**Comment by HereticWilson** [comment]
Same here on CM13, Oneplus One, xposed v86 sdk23 arm. Go to install, gives a progress bar, then says it was not installed.

**Comment by th3an7** [comment]
@kovanovic Lastest version of module is 1.8.25 BETA (with notification visible all the time) which supports YT 11.25.55

@HereticWilson Uninstall previous one first

**Comment by ThiagoBezzy** [comment]
I upd8 the apk using repositor.
Now, YouTube background work :)

But, the Xposed version is not updated yet.
