### ISSUE TITLE
only works some times and still crash

### ISSUE THREAD

**Issue by markusosx** [pylerSM/YouTubeBackgroundPlayback#2]
Tested on Note 3 android 4.4.2 with latest Youtube version

Here is a log from xposed: 
http://www3.zippyshare.com/v/PrH3XZrx/file.html

**Comment by pylerSM** [comment]
Thanks. At least creen off playback works, or no?

**Comment by markusosx** [comment]
Yes, screen off playback is the only thing that is working without problems :)

**Comment by CBElwood** [comment]
how is this supposed to work?

**Comment by renovatio2** [comment]
Well, you could use other app, go back home etc while video and audio keep going on, on YouTube app. 

Another thing I want to let you know is the notification stays there on KitKat and even If I try to start the video from the panel nothing seems to happen.

**Comment by CBElwood** [comment]
ok thats what I did. It didnt work, but I have a lot of stuff disabled, so Ill give it a try again later. Thanks

**Comment by Vadimn73** [comment]
on galaxy s3 with android 4.1.2 works fine, but on the note 3 with 4.4.2 works with the screen off well, and the background only works if you play playlists....fix this problem please

**Comment by pylerSM** [comment]
New version should fix some problems.

**Comment by markusosx** [comment]
Thanks, Now it works, but i don't have notification in the status-bar

**Comment by pylerSM** [comment]
Maybe. Now enjoy working playback! :) lock and unlock screen also causes notification pop up.

**Comment by newzealandpaul** [comment]
Confirmed this is fixed. Thanks pyler.
