### ISSUE TITLE
does this only consume the bandwidth to play the audio?

### ISSUE THREAD

**Issue by ghost** [pylerSM/YouTubeBackgroundPlayback#20]
This is my biggest question because it should be noted somewhere if it does or doesn't.

I don't want to end up with a $3000 phone bill because I wanted to use YouTube as a radio.

**Comment by pylerSM** [comment]
I dont know, but somebody may check it for you.

**Comment by GijsTimmers** [comment]
Install 3G Watchdog and keep an eye on your data usage.

**Comment by Banayat** [comment]
Yes, it consumes the same bandwidth.
