### ISSUE TITLE
Trouble installing 1.8.27beta

### ISSUE THREAD

**Issue by Ythan** [pylerSM/YouTubeBackgroundPlayback#207]
I'm having trouble installing Youtube Background Playback 1.8.27beta on my Verizon Galaxy S4 (KitKat 4.4.2). My girlfriend is having the same problem on her Verizon Galaxy S5 (Marshmallow 6.0.1) so maybe it's related to TouchWiz?

I update and reboot, but the module doesn't work and Xposed has this line in its log:

```
Loading modules from /mnt/asec/com.pyler.youtubebackgroundplayback-1/pkg.apk
File does not exist
```

However, the file does exist, I can browse to it. If I try running "pkg.apk" it reinstalls Youtube Background Playback, and after a reboot I get the same error in Xposed with a different directory:

```
Loading modules from /mnt/asec/com.pyler.youtubebackgroundplayback-2/pkg.apk
File does not exist
```

If I uninstall, it deletes the directory in /mnt/asec as expected. When I reboot and try the installation again from scratch, I have the same problem I described above.

Any idea how I can get this working?

**Comment by th3an7** [comment]
Can you try moving the whole directory (com.pyler.xxx) to data/app? Maybe
it helps... Also try changing pkg.apk to base.apk

IDK how apps are installing on Samsung devices but normally it should
install everything in data/app folder.
Do you use some kind of App2SD apps?

**Comment by vmorenomarin** [comment]
I have the same problem since several days. I use CM 13 on a Moto G 2014. Neither beta o released versions work.

**Comment by Ythan** [comment]
> Do you use some kind of App2SD apps?

Thank you! Good call, that was exactly the problem. I wanted to install to SD card by default so I had used adb to run
`pm set-install-location 2`

YoutubeBackgroundPlayback installs as expected when I set it back to default by running
`pm set-install-location 0`

So I guess the problem is on my end, however I should mention that I've had my phone configured this way forever and it's only recently that I've started having problems with YoutubeBackgroundPlayback.

> I have the same problem since several days. I use CM 13 on a Moto G 2014. Neither beta o released versions work.

It sounds a lot like you and I are experiencing the same issue. It's interesting that both our phones have external SD cards, and we both began having the problem recently. I think th3an7 is right and it's an incompatibility with running YoutubeBackgroundPlayback off an external SD card. Does your Xposed log have the same error as mine? I don't know the CM default settings, what does it show if you connect with adb and run this?
`pm get-install-location`

**Comment by pylerSM** [comment]
You CANT have Xposed modules on SD card. Xposed cant load them from there.

**Comment by zabeiua** [comment]
Same here. App not installed on 6.0.1

**Comment by th3an7** [comment]
@zabeiua have you tried uninstalling previous version before updating?

**Comment by zabeiua** [comment]
It worked. Problem solved. Thanks, @th3an7

**Comment by vmorenomarin** [comment]
Yes, uninstalling previous version and installing the last version, it works. Thanks by the advise.
