### ISSUE TITLE
Close app from notification

### ISSUE THREAD

**Issue by Enigmo96** [pylerSM/YouTubeBackgroundPlayback#209]
Hi, why don't you put a little "x" in the corner of the notification to completely close the YouTube app (and the notification) running in background? (Maybe it was present some times ago?)

Thanks!

**Comment by IscreaMan** [comment]
Yes, the "X" button in notification panel for closing youtube app is missing. Without this button closing youtube app is much more difficult. It would be great if this close button is back.

Thanks for great module!

**Comment by th3an7** [comment]
The module does not change notification design and its contents... if you want to change something in that - write feedback to Google :)

**Comment by Enigmo96** [comment]
You mean that the notification is in the YouTube app? I thought it was designed by you!

**Comment by th3an7** [comment]
Nope :P Module makes it visible for everyone, not only for those with YT Red subscription :)

**Comment by Enigmo96** [comment]
Oh now I understand..thanks
