### ISSUE TITLE
Notification background

### ISSUE THREAD

**Issue by SkilletDesire** [pylerSM/YouTubeBackgroundPlayback#210]
Hi Notification background color is white and the controls are unseeable.

**Comment by iHelp101** [comment]
The module does not create the notification. The YouTube app creates the notification. This is an issue you have to report to Google/YouTube.

**Comment by wiredroid** [comment]
The pause forward play for background it's all white. So I'm going to say YouTube background player doesn't show correctly. All other notifications are fine.

**Comment by wiredroid** [comment]
![screenshot_20160723-151209](https://cloud.githubusercontent.com/assets/7094162/17075950/6a8a5b02-50e8-11e6-8419-f91804a2e951.png)

**Comment by th3an7** [comment]
Can you change your system theme? Also as @iHelp101 said - module does not change notification design. If you want something fixed in that - write feedback to Google :)

**Comment by Phoenix09** [comment]
You can use [this module](http://repo.xposed.info/module/com.ssrdroide.youtubenotificationseekbar) to theme it when it's updated to support the latest version.
