### ISSUE TITLE
Anyway to extend this to the Youtube Music app?

### ISSUE THREAD

**Issue by Backflipz** [pylerSM/YouTubeBackgroundPlayback#212]
Would be great if you could extend this functionality to the Youtube Music app (https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.music&hl=en)

I feel that it has more options & variety than the standard Youtube 50+ unlimited playlist for music.

Don't know if this is the area to make feature requests like this

Otherwise I'll have to dabble in the code for a couple hours maybe and figure out how xposed and this module works, lol

**Comment by pylerSM** [comment]
Youtube Music does not work in my country, and it is same in Poland, right @th3an7 ? :D

**Comment by th3an7** [comment]
Yup :P
Only way to make it work is to use VPN set to US. I used it some time ago
but now I'm just using normal YT app :D

**Comment by Backflipz** [comment]
Damn, oh well any pointers if I we're to look into it myself?

**Comment by pylerSM** [comment]
VPN works? :D Hmm, it would be funny to hack but... I really dont like to work with obfuscated code #cry

**Comment by th3an7** [comment]
I am looking at it right now and there is one string that is almost the same as in normal YT... I can't find the others though :P

**Comment by destiny2jannat** [comment]
YouTube background module is awesome. .. & thanks for that ... we want you to make youtube music background playback module ... please make it soon .. thanks
