### ISSUE TITLE
YT 11.29.53 code change

### ISSUE THREAD

**Issue by th3an7** [pylerSM/YouTubeBackgroundPlayback#213]
Hi
There is a code change in the latest YouTube version 11.29.53...
Before, two strings where in the same place (so the module was easy to edit - even I could do that XD), now they are separated (so I don't know how to update module :\)

Two strings I am talking about are: 
- "About to stop background service while in a pending state."
- "background_mode"

In the last version they were in qts.class, now they are in two different places (first one is in sie.class, second is in rgs.class)

Now there is a question - can someone tell me how to modify the code so the module could work again?

Thanks :P

**Comment by th3an7** [comment]
Nevermind... I think I've got it :P

**Comment by th3an7** [comment]
OK, I've found out that the class with first string (sie.class) works and YT works in background BUT... notification is visible only in background and not all the time. Also changing method does nothing and it is still in background (before "f" was known for doing that).

**Comment by esgie** [comment]
"rgs", "c", "a", "f" for the first class and the notification shall be
visible all the time ;)

pzdr
es

30 lip 2016 17:27 "Łukasz Ordon" <notifications@github.com> napisał(a):

**Comment by th3an7** [comment]
SHIT... I thought I've already tried this... I AM SO BAD AT MYSELF RIGHT NOW...

Goodbye my friends... I am going to kill myself rn
