### ISSUE TITLE
Support for 29.55? 

### ISSUE THREAD

**Issue by abhijeetramgir** [pylerSM/YouTubeBackgroundPlayback#225]
Support for 29.55??
Thanks a lot!!

**Comment by th3an7** [comment]
It's already been updated - refresh xposed repo
http://repo.xposed.info/module/com.pyler.youtubebackgroundplayback

**Comment by totaltelecom** [comment]
Last I see is update for 29.53. YouTube broke it last night with 29.55. I just flashed an older version YouTube in tibu till it gets updated. Thanks for the great work, Google wants $10 a month for ad free and background playback? I could see a one time $10 payment, but think Google is asking too much.

**Comment by th3an7** [comment]
Look... go to the page I linked before, choose verion and put .apk on your phone (or use adb to install it).

![screenshot_2016-08-16-19-45-20](https://cloud.githubusercontent.com/assets/13398380/17709667/6506964a-63ea-11e6-8176-54ace9470a77.png)
![zrzut ekranu 23](https://cloud.githubusercontent.com/assets/13398380/17709674/6c410d96-63ea-11e6-930c-120394ae247a.png)

**Comment by abhijeetramgir** [comment]
Yea got it,  thanks a lot!!  It's the best android feature

**Comment by totaltelecom** [comment]
Yeah thanks, must be my version of xposed. I'll check the repository from
now on.

**Comment by esgie** [comment]
This problem has been discussed at least four times in the past.
It's some bug in the xposed installer/repo, I found out that it is more
like to happen when there are a lot of different versions of the same
module in repo. It is probably somehow connected with too big xml data is
being sent from the repo so it has to be stripped, hence the most recent
version won't be seen.
Fix:
User should clear the data of xposed installer (and then not forget to tick
all the modules again!).
Developer should delete some previous versions of the module as there are
too many of them and it raises the probability of bug to happen again.

pzdr
es

16 sie 2016 19:50 "Łukasz Ordon" <notifications@github.com> napisał(a):

**Comment by th3an7** [comment]
Well... I won't delete any old version as I am not owner :P

What about that refresh button in Xposed app?
Anyway - Xposed app shows only a few versions and not all of them (there would be a lot of scrolling though). I recommend checking repo page from time to time if there is no recent version in app.

**Comment by esgie** [comment]
Refresh button won't help. Only clearing the data of Xposed installer - and
the bug will happen again in a minute if the dev won't delete unneeded
releases.
As I still have the powers to maintain the repo, I have deleted some old
versions. Hope this help.

pzdr
es

16 sie 2016 19:59 "Łukasz Ordon" <notifications@github.com> napisał(a):

**Comment by totaltelecom** [comment]
Yeah, wow! Holy updates! Data Wipe helped, I have a ton of updates!

Thanks!!

**Comment by pylerSM** [comment]
@rovo89 can you check this repo bug?
