### ISSUE TITLE
Issues with swipe down while in vertical mode

### ISSUE THREAD

**Issue by brusyev** [pylerSM/YouTubeBackgroundPlayback#228]
I am having issues with swipe down to minimize window that is currently playing while in horizontal mode but the volume gesture causes it not to work on first swipe. It would be nice to have an optin to force volume gesture to work only in landscape mode. Galaxy Note 4 running 5.0.1

**Comment by th3an7** [comment]
I think that's not this module... It doesn't add any gestures. It only makes YT work in background :P

**Comment by esgie** [comment]
I think you should contact with the developers of "YouTube swipe to seek"
module

pzdr
es

22 sie 2016 00:41 "brusyev" <notifications@github.com> napisał(a):

**Comment by brusyev** [comment]
Sorry about that. I must have posted in a wrong thread.
