### ISSUE TITLE
Notification problem

### ISSUE THREAD

**Issue by BibleBeliever** [pylerSM/YouTubeBackgroundPlayback#229]
Hello, 

First off, thanks a lot for this great module. Unfortunately, though, I've been having problems for some versions/time now: I can hear the sound, but there's no notification. I'm currently on OxygenOS 3.2.2 (OnePlus 3).

I hope I'm not wasting your time here. Thanks in advance.

**Comment by BibleBeliever** [comment]
P. S.: I uninstalled the old YT notification module and installed the new one and still no notification.

**Comment by th3an7** [comment]
Are you using stable or beta version of the module?
Beta is the one with notification visible all the time.

Stable is the one with notification visible only in background (ex. when
screen is locked).

**Comment by BibleBeliever** [comment]
I'm using the beta version. Let me change it to stable real quick. I'll keep you posted.

**Comment by BibleBeliever** [comment]
Still not working. I'll update my OS tomorrow and I'll let you know what's up. I'm on a custom ROM right now and I'm switching to stock again.

**Comment by BibleBeliever** [comment]
I switched to stock and still nothing. Do you suspect what it is?

**Comment by BibleBeliever** [comment]
Hey, I just realized that notifications for the YouTube app have been blocked sometime in the past. I've now allowed notifications and lo and behold, it's there. 

Sorry for my unwise question.
