### ISSUE TITLE
Read if issues after update to 11.33.58

### ISSUE THREAD

**Issue by Maaximcdonat** [pylerSM/YouTubeBackgroundPlayback#236]
I just updated to newest version (11.33.58 I think, I forgot lol) and it wasn't working for me, after messing around a little in root archive, I did this :
Deinstall updates in settings 
Install 11.33.55 from here : http://www.apkmirror.com/apk/google-inc/youtube/youtube-11-33-55-release/
Install and hear music in background again :) 
Devs: please fix, can't press next / previous in notification panel, it's grayed out. Using alliance ROM on gs5 with latest framework version from arter97

**Comment by th3an7** [comment]
About next and previous - it works only when you are playing playlist. It
doesn't work in autoplay...

**Comment by Maaximcdonat** [comment]
Oh ok, didn't use this feature before, my mistake.

**Comment by th3an7** [comment]
No problem :)

**Comment by th3an7** [comment]
You should install module version 1.8.33. It's updated for YT 11.33.58

**Comment by remeca** [comment]
I thought maybe I had an older version but 1.8.31 is the latest version shown in xposed modules. I've hit the refresh button and no newer versions show up. Is there another way to install it?

**Comment by th3an7** [comment]
You can download .apk here:
http://repo.xposed.info/module/com.pyler.youtubebackgroundplayback

Or try deleting Xposed App data, reenable all modules and restart phone.
Then you should see new versions :)

**Comment by remeca** [comment]
That fixed it, many thanks!

**Comment by davedavis** [comment]
Worked for me too. Thanks @th3an7

**Comment by Voide** [comment]
I have all the updated files for xposed all, framework, and module but I can't background play! I tried everything please help.

**Comment by Captainfsu** [comment]
After updating to the most recent version of Chrome (53.02785124) on Thursday I'm  having issues with YouTube playing (at all)  either through the YouTube app or through Chrome. I can _**only**_ get youtube, whether through the app or chrome, working again if I disable the YouTube Background Module in xposed.
