### ISSUE TITLE
custom xposed version (samsung) installed using twrp 

### ISSUE THREAD

**Issue by Voide** [pylerSM/YouTubeBackgroundPlayback#238]
Hi, I'm using a Samsung Galaxy A5 (2016) running Android 6.0.1 on a stock ROM, and my framework description is "Xposed framework version 85.1 (custom build by wanam / 20160530) is active". I'm using YouTube version 11.33.58 and module version 1.8.33, I've tried everything; clearing app data from all 3 apps (xposed, module, and yt) and I just can't seem to get it to work, I did reboot and made sure I had selected the module before I rebooted, I have no other modules running. Please help thanks.

**Comment by Voide** [comment]
Whenever I watch a video and exit, it behaves the same and stops playback I don't know what to do.

**Comment by Federic095** [comment]
The problem it's that the module has to be updated: YouTube has been update to version 11.33.58 but the module supports until 11.33.55. Or you downgrade to this version or wait for an update of the module

**Comment by th3an7** [comment]
YT 11.33.58 is already supported. Check repo if you don't see new version
in Xposed app

**Comment by Voide** [comment]
In using the newest module version and the newest YouTube version, it still won't work :( (yt 1.33.58 module 1.8.33)

**Comment by dangelization** [comment]
I have been using xposed with this module on my samsung note 5 for almost a year now. Not a single problem.

I have xposed 86.0 custom by wanam installed right now.
Try to see if your xposed works correctly. Install other modules and see if they work.
Both xposed by wanam and systemless xposed by topjohnwu works.
