### ISSUE TITLE
YouTube Background Playback

### ISSUE THREAD

**Issue by Antitype** [pylerSM/YouTubeBackgroundPlayback#24]
Any method to make playback smoother when leaving and entering YouTube? I disabled this module and signed up for a trial of YouTube Music Key because the latest version of YouTube was not supported at the time. After trying YouTube Music Key; playback is really smooth, hardly notice any lag unlike this module. Probably because it has to go through a few different things before background playback resumes. But I still prefer this module since it plays all videos from YouTube. Great work.

**Comment by Antitype** [comment]
Nevermind. I saw your comment on another post. Thank you for your time in developing all these modules.

**Comment by juned393** [comment]
You can use[ pvstar+ apk ](https://wildtricks.com/pvstar-plus-apk-download/)to play youtube music in background...
pvstar+ isnt available on play store..
you can download it from below link...
[https://wildtricks.com/pvstar-plus-apk-download/](https://wildtricks.com/pvstar-plus-apk-download/)
