### ISSUE TITLE
Possible issues with last YT supported version (11.35.60)

### ISSUE THREAD

**Issue by xerta555** [pylerSM/YouTubeBackgroundPlayback#242]
Hello,

For first, huge thanks to dev of this app, its a very good work !

Secondary, I unfortunately a bug with the last version version, YT and YouTubeBackgroundPlayback compatibility chart are respected.
I have install the version to ahve ALL TIME the notification active.
I have make my test:

So i have launch YT and play a music clip (for my exemple), i lets YT app play the video and the song approximativly 10 second and i press the physical button of my phone. At this moment, the song is not stopped so i put my screen ON and I see that a notification is appear (generated by YT app) who see to the user that Youtube Red make run the song until the screen is off.

But with older versions of this app, the new default YT Red fonctionnality not run..

I must link the xposed log or its enough for your to plan a fix for my issue ?

Thanks :)

**Comment by th3an7** [comment]
I don't really understand where is the problem...

The latest module does not work with old version of YouTube?

**Comment by xerta555** [comment]
Not exactly, your last version won't work on my phone withe the supported version.

Apparently, the default module to play mucis with screen off works, and your module won't works.
I would like that your app works and the default YT fonctionnality to be not enable.
