### ISSUE TITLE
Background playback not working on Asus Zenfone 2

### ISSUE THREAD

**Issue by ArijitDas0017** [pylerSM/YouTubeBackgroundPlayback#243]
I havent been able to use the background playback function for quite some time on my Asus Zenfone 2 (Z00AD). I have installed the latest stable version..and have reinstalled the app, but to no avail. Pls help

**Comment by th3an7** [comment]
Did you try the beta version?

What exactly does not work? Notification does not appear?

**Comment by ArijitDas0017** [comment]
Nothing happens when I open an YouTube video. No notifications...nothing. I have checked, but notifications arent blocked for this app.

**Comment by th3an7** [comment]
In stable, notification is visible only when app is in background (press home or lock screen).
In beta, notification should be visible all the time.

Latest module version is 1.8.34 for YouTube 11.35.60. Are you sure you have module enabled in Xposed Installer?

**Comment by ArijitDas0017** [comment]
Yes the module is enabled..and I have rebooted the device, but to no avail

**Comment by th3an7** [comment]
Did you tried installing beta?

**Comment by ArijitDas0017** [comment]
I have installed beta now. Will reboot and then post if something goes the right way

**Comment by ArijitDas0017** [comment]
I rebooted and thankfully, the beta works like a charm. However, I have no idea why the same Stable version doesn't work at all, not even when the app is in background.

**Comment by th3an7** [comment]
Don't know either... Do you use some kind of app killer (ex. Greenify)?

**Comment by ArijitDas0017** [comment]
Yes I do...However this app is exempted from it.
