### ISSUE TITLE
Youtube 

### ISSUE THREAD

**Issue by vipertongn** [pylerSM/YouTubeBackgroundPlayback#244]
ahh... I hit enter while making the title.  Anyways, I'm using the nexus 6p on the Resurrection Remix rom.  I noticed for some reason the xposed mod stopped working and my youtube no longer plays in the background.  I tried uninstalling and reinstalling, followed by a soft reboot.  No luck tho.  Any suggestions in how I can resolve this?

**Comment by th3an7** [comment]
Did you get todays YT app update? Module is not yet updated for 11.38.54...

I'll upload new module version tomorrow (need to test it first) :P

**Comment by vipertongn** [comment]
ahh...that i did XDDD i was thinking about that after i posted this haha. thanks!

**Comment by th3an7** [comment]
Check the repo for new version - should work now :)

**Comment by vipertongn** [comment]
th3an7, thanks so much it worked like a charm 💃

**Comment by Lightfire228** [comment]
You can disable YouTube auto updates from the Play store and wait till an update for the module before installing. That's what I do

**Comment by jkdf2** [comment]
Please close this issue.
