### ISSUE TITLE
Suggestion for QOL improvement (mute media volume on opening YT link) 

### ISSUE THREAD

**Issue by DarkwaterV3** [pylerSM/YouTubeBackgroundPlayback#246]
Dear devs, 

I'd like to suggest you implement an auto-mute option in YT background playback. You see, when you open a YT link unintendedly, normally your would mash Back or Home to fix that. With this xposed module, that's no longer possible, which can lead to unintended discomfort. This option would fix this, with the trade-off being that you'd have to enable sound every time you open a video, which would be worth it to me, personally. 

I hope this makes sense. I'm on mobile. 

Thanks for your time!

**Comment by jkdf2** [comment]
If you open a link accidentally, mash the "volume down" button now.

**Comment by DarkwaterV3** [comment]
That would work, were it not for the fact that if you press Volume Down before the video starts, you're adjusting the ringer/notification volume instead.

**Comment by jkdf2** [comment]
Fair point. Hmm...

**Comment by DarkwaterV3** [comment]
This in turn can be fixed with a quick swipe of the finger on the volume panel that's then come into view. You may need to expand the panel first if that's what you have it set to. 

Seems like there's no real catch-all solution to this. How does YouTube Red do it? I'm not in an eligible country.
