### ISSUE TITLE
YT Videos embedded in other apps play, no notification bar

### ISSUE THREAD

**Issue by Lightfire228** [pylerSM/YouTubeBackgroundPlayback#247]
When a YouTube video playes in another app (namely ifunny), the module causes the video to play in the background; however, there is not a notification bar to stop the audio, nor is the audio playing on YouTube itself. Killing the app (ifunny) in the task manager doesn't stop audio, only playing another video in YouTube stops the audio. 

Disabling only this module causes the problem to be fixed

Nexus 6p
Android: 6.0.1 MTC19X
    Stock ROM, modified boot.img
YT: 11.35.60
YTBP: 1.8.35 visible all the time
Ifunny: 4.6 (4374)

**Comment by Lightfire228** [comment]
Not really fixed, but given 8 months without a reply, you probably want this closed

**Comment by th3an7** [comment]
This probably never be fixed. Module is made for YT app itself, not for
videos in other apps...
