### ISSUE TITLE
playback not working - nexus 5 - 6.0.1 (M4B30X, Oct 2016) rom

### ISSUE THREAD

**Issue by rathiankush123** [pylerSM/YouTubeBackgroundPlayback#249]
this module is **not working** for me.
I have attached the screenshots for reference
I checked the YT app version. it is latest - v11.39.54
the module is also latest one v1.8.35 and it is activated

I have **nexus 5, MM, Build no M4B30X**
It was working for MM ROM version 6.0.1 (MOB30Y).
This October I had an update from google MM version (M4B30X, Oct 2016) ROM and now its not working.

any help would be appreciated

thank you

![screenshot_20161009-033430](https://cloud.githubusercontent.com/assets/22717923/19216306/b3726d3c-8dd3-11e6-89ce-9e0a1d36a829.png)
![screenshot_20161009-033523 1](https://cloud.githubusercontent.com/assets/22717923/19216305/b36f0ef8-8dd3-11e6-8bd8-f3512377d7fb.png)
![screenshot_20161009-033523](https://cloud.githubusercontent.com/assets/22717923/19216307/b378f4ae-8dd3-11e6-85e5-79845e6772ac.png)

**Comment by th3an7** [comment]
Do you use beta or stable? In stable there is no notification when YT is opened (it's visible only in background or on locked screen)

**Comment by rathiankush123** [comment]
I use stable version only
I tried pressing HOME and also LOCKING the device while YT is playing
:(

**Comment by th3an7** [comment]
Try using beta

**Comment by th3an7** [comment]
Oh, one sec... Did you get YT update yesterday? We have to update the
module to make it work again :P

**Comment by rathiankush123** [comment]
yes i did
the YT version i am using is v11.39.54
so ? is it the prob ?

**Comment by th3an7** [comment]
Just wait till we update the module or downgrade your YT app to 11.38.54

**Comment by th3an7** [comment]
Module updated - check xposed repo :)

**Comment by rathiankush123** [comment]
yay !! working fine now 👍  tnx buddy
keep up the good work
