### ISSUE TITLE
DASH-Playback issue

### ISSUE THREAD

**Issue by Syl0s** [pylerSM/YouTubeBackgroundPlayback#25]
Hi,
the current version 1.3.4 has fixed for me that a) background playback didn't work, after it broke in a previous version and b) that it didn't continue playing videos consecutively in a playlist, before the background playback had broken.

However, there's now a new issue.

I've observed it and came to the conclusion that it must be connected to DASH-playback.

You're probably familiar with it, but DASH basically splits up the video file into several smaller parts, which are then loaded in after another when needed,
as opposed to non-DASH, where it just loads the entire video in one go.

Now for me, once YouTube is playing in the background,
it usually plays until it hits one of those marks, where it should continue playing the next part,
which it then doesn't, because it hasn't loaded in that part previously.
Instead, it seems to simply go into a buffering state (as displayed by the notification),
but never causes any internet traffic, so just doesn't load anything.
(It neither does load anything shortly before that mark comes, which is the point where it should normally do that, and does, when playing in foreground.)

So, for fixing this, you'd either have to somehow manage that the YouTube-app stays active enough to load in those parts,
or simply downright disable DASH-playback.

I suppose, the latter should be doable with XPosed,
but I'll have to leave that up to you.

And, in case any of that is helpful to you:
I'm using version 1.3.4 of your app, YouTube version 10.10.52, on a Nexus 4 with CyanogenMod 11 M12.

**Comment by pylerSM** [comment]
Sorry, I have no idea about your problem. Nobody else told me so. It plays ok.After buffering is 100%, playback always continues.

Many people will blame me if I disable "dash". Some users must wait for ages for full video loading. Definitely no go. Anti-youtube behaviour.

**Comment by Syl0s** [comment]
Yeah, I was expecting that. Somehow my YouTube seems to be very special. A real shame, but if it's only me, then there's really no point in possibly breaking other functionality. Do you think, it's hard to create an XPosed-module, which simply disables DASH and does nothing else? If not, I might look into writing one myself...

**Comment by pylerSM** [comment]
Try clearing app data firstly.

Hard to say whether hard or not, maybe its just one config/boolean field or method. Obfuscation makes things hard to do.

**Comment by Syl0s** [comment]
Clearing app data did not help. Still the same behaviour...


But yeah, I also presume, that it's just one boolean, as you can find plugins for Desktop browsers, which disable DASH.
And also 3rd party apps, which implement non-DASH playback, so it's probably just a matter of telling the server "I want this video, in 720p, with no DASH-playback, ...".



Then I'll just have to see, how hard to understand XPosed is, and if I can figure out what variable that is...

**Comment by kubbur** [comment]
Ó I'm battling the same problem, any solution?

**Comment by Syl0s** [comment]
So far not really, no, sorry. I still have to get into that XPosed-stuff and I'm only just now getting some freetime to do so. Also, this project is currently still clearly over my capabilities. So, unless XPosed turns out to be extremely easy and I at random happen to find the right thing in YouTube's source code, I really wouldn't hope for anything to come from me.

**Comment by kubbur** [comment]
http://apkdler.com/apk/download_apk?apk=com.android2014.poptube
this was a bit hard to find, it's the last version before they were forced to change the app, something about apk licence agreement, cheers and thank for the quick response
