### ISSUE TITLE
YouTube 11.39.56

### ISSUE THREAD

**Issue by seanwlk** [pylerSM/YouTubeBackgroundPlayback#253]
Version still not supported or I'm bugged? I run COS 13.1.2 on OnePlus One. Closed framework works for the other modules.

**Comment by th3an7** [comment]
There should be support for YT 11.39.56...
Always check repo if Xposed app doesn't shows the latest version

http://repo.xposed.info/module/com.pyler.youtubebackgroundplayback

**Comment by seanwlk** [comment]
Xposed application is still pointing to 1.8.35. Downloaded from the repo thanks.
