### ISSUE TITLE
yt 10.11 and future versions

### ISSUE THREAD

**Issue by esgie** [pylerSM/YouTubeBackgroundPlayback#26]
New yt version is out. Not compatibile with latest version of module.
Btw today i have received an update for the other module, youtube adaway by wanam. In the descripton there is an info that he has implemented some "brute force" method so now all past and future versions of yt should work with the module. Maybe you can implement something like that too?
Thank you for your time.

**Comment by pylerSM** [comment]
Maybe. I am now lazy to do it. :D
I will update module for YT10.11 in a few days.

**Comment by esgie** [comment]
10.12.53 is out
quick info for you so you can make a quick update (hope ill be helpful):
build 101253134
cym -> cyc
j -> j
v -> v
Recompiled for myself, works like a charm.

**Comment by pylerSM** [comment]
Useful info! Thx. Update in a few minutes

**Comment by esgie** [comment]
Ah and the x86 build: 101253172

**Comment by esgie** [comment]
Info for new version (10.13.xx) to ease you in updating the module ;)
Builds (armv7a/x86): 101354134 and 101354172
cyc -> cyb
j -> j
v -> x
and also FIELD_PLAYBACK_CONTROL has changed its name this time...
i -> h
Again recompiled for myself, works fine.

**Comment by pylerSM** [comment]
Thank you very much!

In the future, If you want, I can add you as second developer in Xposed repo so you can publish updates :)

**Comment by esgie** [comment]
We'll talk about it right after the Easter ;)
Happy holiday
