### ISSUE TITLE
Closes

### ISSUE THREAD

**Issue by Droidking18** [pylerSM/YouTubeBackgroundPlayback#262]
It closes on its own after a few songs, if I go out of YouTube. If I lock the screen while it's on YouTube, the bug doesn't occur. It's very annoying

**Comment by Droidking18** [comment]
I'm on the latest version of YouTube, and latest version of the module (I updated last night to the experiential release). This version seems to be working a lot better. If it continues happening I'll send a log.

**Comment by sigv** [comment]
There was a fix in the 2.x experimental releases aimed at older versions of the Xposed framwork. If the issue reappears, please open a ticket. I am closing this one then.

**Comment by Droidking18** [comment]
No, it's still happening. I can't get a log until Friday. It seems pretty random, but when I open SnapChat it usually closes

**Comment by th3an7** [comment]
Do you use some kind of app killer like greenify? Also, how much RAM does
your device have? Maybe system is closing it due to not having enough free
RAM?

**Comment by Droidking18** [comment]
I used to use an app killer, but stopped because I thought that was the
reason. I checked my RAM usage, but that doesn't seem to be the issue. My
device has 1.3 Gb of RAM, so I'm not sure what the issue is. It seems the
new 2.0.1 update has made it less frequent though, but it still happens. By
the way, I'm running CM 13, if that helps.
