### ISSUE TITLE
There is a small problem.

### ISSUE THREAD

**Issue by BlackGhost12** [pylerSM/YouTubeBackgroundPlayback#265]
![screenshot_20161109-041527](https://cloud.githubusercontent.com/assets/19236621/20123866/f7f7be66-a62a-11e6-8fc3-3fc88b90e71f.png)

The picture in the notification panel is too small. The old man was very good. 😊

**Comment by sargijeh** [comment]
Are you using N-ify? @blackghost12

**Comment by BlackGhost12** [comment]
Yes.

**Comment by sargijeh** [comment]
@blackghost12 that's the cause :)
I use N-ify and Music and Youtube is like this :)

**Comment by BlackGhost12** [comment]
@sargijeh Okay. Thank you.
