### ISSUE TITLE
version 11.43.54 not working :)

### ISSUE THREAD

**Issue by pleespammail** [pylerSM/YouTubeBackgroundPlayback#266]

**Comment by th3an7** [comment]
Try using new experimental version - we are testing it but you should not have any problems with it :)
If you will install it, you wouldn't have to update the module everytime when new YT version is available... it should work automatically when we update our github sources :)

**Comment by pleespammail** [comment]
thx for the quick response!

i tried using the exp version on the prior yt version (11.43.52), but yt wouldnt load at all. so i switched back to the non-exp version. 

is the plan to ultimately transition to the exp version st we wont have to continue dling new versions?

**Comment by th3an7** [comment]
Probably yes...
BTW: Is there any error if YT is not opening? Or is it showing something
like "cannot connect to server"? If you are opening YouTube right after
reboot while on mobile internet (LTE, 3G), it sometimes shows that info -
you have to wait minute or 2 and it should work again (or connect to wifi)

**Comment by pleespammail** [comment]
lemme dl the exp version again, update to the latest yt version, then report back on exactly wut the error is.

fyi i am on android 4.4.2 verizon note 3.

**Comment by pleespammail** [comment]
well dont i look silly... updated to latest yt (11.43.54), switched to 2.0.1 yt bckgrnd playbck vrsn... everything working smooth as silk.

much thx for all the awesome work... fantastic mod...  :)

**Comment by th3an7** [comment]
Good to hear you've sorted it out :)

**Comment by pleespammail** [comment]
thx, sorry for the wasted time :)
