### ISSUE TITLE
Embedded YouTube player

### ISSUE THREAD

**Issue by Navixer** [pylerSM/YouTubeBackgroundPlayback#268]
The module successfully plays an embedded video on the background but provides no control over it so it can't be stopped until the video is finished. I'm not talking about browsers players', I'm talking about the one works with YouTube's embedded player. In my case those are the YouTube links on Relay, Reddit app. I'm using the latest experimental version, 2.01.

**Comment by sunbriel** [comment]
Same issue, but with Slide (Reddit app) Video Plugin. If I open a YT video with it and close it before it ends, the audio will just keep playing in the background with no way to stop it until the video ends.

**Comment by E66666666** [comment]
Workaround for me: Pressing pause on the video before closing will stop the audio.

**Comment by bennyhillthebest** [comment]
With 1.8.39 that had the notification only visible when the app was in background the embedded videos closed when the back button was tapped, as they should have. Is it possible to have two versions again?
