### ISSUE TITLE
Themable notification

### ISSUE THREAD

**Issue by Fraught** [pylerSM/YouTubeBackgroundPlayback#27]
I'm running CM12 on my M8, and thus I've gone through a lot of themes, trying to get that perfect look. However, throughout all of the themes I've tried, I've noticed that the Youtube notification always stays the same dull grey colour, while everything else gets automatically themed (including persistent notifications, like PowerAmp).

Is this an issue with Youtube itself (as I heard you can...apparently have background playback with Google Play Music All Access?) or with the module? 

In any case, is there a reason it doesn't get changed to the applied theme, like all other notifications? It being the only grey notification is a bit of an eyesore.

**Comment by pylerSM** [comment]
This is normal notification from youtube, made by google devs. Try asking theme creator directly about this since I cannot help you with this issue.

**Comment by Fraught** [comment]
Hmm, well, I guess it can't be helped then. It's odd that they made it that way, though, because EVERY other app's notification themes itself accordingly (as I reckon most of them just have a transparent background?).

Oh, also, there's no theme creator to ask. It's not the themes' fault, because I've tried about 15 themes, and none of them change the YT notification. I guess I could contact some of them and ask if there's a way for the theme to sort of...overload it.
