### ISSUE TITLE
Module isn't working with YouTube 11.43.54

### ISSUE THREAD

**Issue by umjediqualquer** [pylerSM/YouTubeBackgroundPlayback#270]
I clean flashed the latest CM13 nightly on my Moto G 2014 (13.0-20161107-NIGHTLY-titan), and installed Xposed right after. Everything works, except this module. I'm not sure if it's related to YouTube version, but it's not working anymore. YouTube will just stop if I minimize it, and uninstalling and reinstalling the module doesn't work. Is there any logs I can attach to help solving this issue? Thanks!

**Comment by th3an7** [comment]
Try experimental version - should work without problems :)

**Comment by thejcode24** [comment]
Not working for me as well.. tried uninstalling and downloading the experimental version but did not work

**Comment by manuelomass** [comment]
Same problem for me... Youtube 11.43. 54 on rooted oneplus 3 running freedom OS... Was working fine till before youtube updated  :(

**Comment by bungabear** [comment]
Also not working my phone. I'm using Youtube 11.43.54.
So I use Firefox browser temporarily. This browser can play video in background or screen-off state include Youtube. 
But it doesn't show any controller/information for background play.
I think Firefox is easy way to listen to music for any devices

**Comment by co5mo** [comment]
will we get experimental version that shows the notif only when app in background as stable rls before? thanks

**Comment by th3an7** [comment]
@co5mo that is the plan... we are just testing it if it's actually working for others... I can post apk here that works like stable before :P

**Comment by co5mo** [comment]
thanks! amazing work guys! just worried about my futurer Pixel purchase :) and that it doesnt have xposed YET

**Comment by co5mo** [comment]
maybe not the right place to ask this but wouldn't you be able to revive this module for marshmallow https://github.com/Eun/RememberIME
thanks

**Comment by thejcode24** [comment]
Thanks so much! I am trying to get into contributing to open source projects on github. Any tips for a newbie and any way I can help with yours? Thanks again

**Comment by abhijeetvramgir** [comment]
Any help for this issue?

**Comment by haldi4803** [comment]
Indeed v2.0.1 does work with YouTube 11.43.54.
Why isnt this Version showing up in xposed repo yet?

**Comment by th3an7** [comment]
@haldi4803 if you are talking about this apk I've linked some posts
earlier, it points to my fork with changed sources and it should be
connected to owner's branch...
I really should push commit with modified json for only background
notification... and as it's not my module, I need to have @PylerSM
agreement for posting modified apk :P

For now, just use apk from here or from xposed repo :)

**Comment by manuelomass** [comment]
@haldi4803..thank you very much !didn't realize there was another newer version of the module available.. Downloaded 2.0.1 and works now... Link for other's reference : https://m.reddit.com/r/xposed/comments/5efpiy/helpyoutube_background_playback_wont_work/?compact=true

**Comment by NovaViper** [comment]
I have the same problem too on my Samsung S6 edge running Android 6.0 on the zremegade v7.0 ROM, my YouTube version is 11.43.54. I haven't tried the experimental version yet (but will try later on soon). It doesn't work for me on the latest stable build though.

**Comment by NovaViper** [comment]
The experimental works for me!

**Comment by djtocanyc** [comment]
Try to download older version of youtube 11.41.54
