### ISSUE TITLE
I'm on 6.0.1 and experimental build of youtube background playback. Phone doesn't boot up when activating the module

### ISSUE THREAD

**Issue by abhijeetvramgir** [pylerSM/YouTubeBackgroundPlayback#272]
I'm on CyanogenMod 6.0.1 and youtube background playback latest experimental build. The phone doesn't boot up when I activate the module and restart
Any help?

**Comment by jkdf2** [comment]
Your likelihood of getting help with this increases if you provide a logcat around the time you experience an issue.

**Comment by NovaViper** [comment]
The experimental version works!

**Comment by djtocanyc** [comment]
Try to download older version of youtube 11.41.54
