### ISSUE TITLE
Question regarding experimental version && Stable version not working with latest YT app

### ISSUE THREAD

**Issue by jasontree** [pylerSM/YouTubeBackgroundPlayback#279]
Could you please **clarify**-
         " No more apk updates - everything is magically done, when YT app is killed and opened"

does that mean YT app wont update if module is activated? or something else.. newbie here so pardon if question is too novice.
Regarding stable version:
Stable version is not working on Youtube app v 11.45.59, ROM: CM13
I would try the experimental version after the clarification.
Thanks :-)

**Comment by th3an7** [comment]
"No more apk updates" - you don't have to download new module version everytime when YT is updated (like it was before). Since experimental version, we just need to update our sources (here, on github) but we don't need to post new apk on Xposed repo. Go ahead and try experimental 2.0.1 - it's working like stable (notification is visible all the time)

**Comment by gene-pavlovsky** [comment]
How does that work, by the way? Does the experimental module fetch some interpreted (JS?) sources from git?

**Comment by sigv** [comment]
It fetches a file containing the method hooks relevant for each of the supported YouTube versions and then simply applies it.

**Comment by sigv** [comment]
Oh, and regarding updates, the YouTube app can be updated individually at any time. The method hooks are checked and applied each time the YouTube package is loaded. That happens for example if you close the app and swipe it out from recents and then reopen it.

**Comment by gene-pavlovsky** [comment]
Thanks, which file is that? Curious to take a look (programmer myself, not Android though).

**Comment by th3an7** [comment]
@gene-pavlovsky Methods are in `YouTubeBackgroundPlayback/assets/hooks-1.json` file. The rest of the code is in `YouTubeBackgroundPlayback/java/com/pyler/youtubebackgroundplayback/YouTubeBackgroundPlayback.java` file. 

File with methods is updated most of the times within 24h from new YT app is being released (and uploaded ex. on [apkmirror.com](http://apkmirror.com)). Everytime module gets updated, there is a commit named with latest YT app version... ex. if the latest version of youtube is 11.47.55 and the module supports it, there should be a commit titled with this version ([Like this](https://github.com/pylerSM/YouTubeBackgroundPlayback/commit/09828f7a0f7737b2bb21c9f7c97ac90edd88fbd3))

**Comment by gene-pavlovsky** [comment]
That's a great idea with the JSON file and serving it straight from github. And thanks for the detailed explanation, all clear now.
