### ISSUE TITLE
not working anymore. 

### ISSUE THREAD

**Issue by njjassal** [pylerSM/YouTubeBackgroundPlayback#28]
Module isn't working on YouTube 10.11.55. Please fix. Thanks.

**Comment by siarheistar** [comment]
Hi, module doesn't work for me as well on yt 10.11.55 .

**Comment by pylerSM** [comment]
Yes, sadly :( I didnt expect that they change another name - this time a specific method name. Bad :/ Another thing to check when there is a new YT update 

Adding support for new YT versions starts to be a challenge.

**Comment by pylerSM** [comment]
I have fix. Release later this day.

**Comment by herny66** [comment]
YouTube 10.12.53....if you can upgrade to this version....tnx

**Comment by pylerSM** [comment]
Wow... This is becoming crazy! Every few days a new update.

No, I will not do it today, maybe in Monday. 

(BTW, I started to hate it.. too frequent updates with almost nothing useful.. too bad we can't use some brute force method (something automatic). I was thinking about supporting only 1/2 version per months, we will see. I don't want abandon this but it will still take more and more time.. I will have only one option.)

**Comment by TheOnlyRealTGS** [comment]
I can confirm this too.

**Comment by abdelkarim0070** [comment]
I like u app so i downgraded my youtube app to previous version but the problem u removed all old versions. Plz put all version so we can enjoy ur app

**Comment by pylerSM** [comment]
Why? I dont have them. Latest module version still works with older versions (or.. it should)

**Comment by siarheistar** [comment]
V. 1.3.6 working ok now. Thank you for quick fix.
