### ISSUE TITLE
Why is not update coming?

### ISSUE THREAD

**Issue by BlackGhost12** [pylerSM/YouTubeBackgroundPlayback#285]
Youtube was very updated. But there's still no update for the module. I'm not upgrading the YouTube version.

**Comment by th3an7** [comment]
Use experimental 2.0.1 :)

**Comment by BlackGhost12** [comment]
@th3an7

Okey. Sorry. Now I understand.

**Comment by th3an7** [comment]
It's OK. Hope you'll solve your problem :)

**Comment by sigv** [comment]
As a side note, we should probably release the experimental as stable so that people know they should switch 😉

**Comment by th3an7** [comment]
Fixed that :D

**Comment by sigv** [comment]
Awesome!
