### ISSUE TITLE
Should probably update the module summary

### ISSUE THREAD

**Issue by anthonyspano** [pylerSM/YouTubeBackgroundPlayback#292]
When I installed this module, it was not working at all for me. Even after clearing the app data and restarting the phone, it still didn't work. I read some of the tickets here on github, and some solutions said to try the experimental version. Now, I usually try to avoid nightly builds, so it never crossed my mind. The stable wasn't working so I said what the hell, why not. And it works! So I guess that version isn't compatible with some versions of android? Anyways, I thought I would recommend updating the module description to say if the stable doesn't work, try the experimental.

**Comment by sigv** [comment]
@th3an7 You think it is time to push the `experimental` as `stable`? Doesn't seem anyone is having issues with it other than that legacy API issue we had at the start of pushing the `experimental` that got patched right away.

**Comment by th3an7** [comment]
Well... It was already set as beta...
Anyway - I've set to stable as you wanted me to do so :)

**Comment by sigv** [comment]
Thanks!
