### ISSUE TITLE
Nougat

### ISSUE THREAD

**Issue by tornisyourdaddy** [pylerSM/YouTubeBackgroundPlayback#293]
Hello Guys
Since Xposed is not working with Nougat so far, and Lucky Patcher is making my phone crash ,
I was wondering if there is a way to Patch youtube and add the Playback mod manually ?

Thanks

**Comment by Kronopt** [comment]
I don't think that's possible.
YouTubeBackgroundPlayback relies on Xposed to work.

**Comment by tornisyourdaddy** [comment]
Since we can patch it with Lucky Patcher and Busybox, i don't think it NEEDS Xposed, That's why I asked.

http://android.wonderhowto.com/how-to/enable-youtube-background-playback-for-free-android-nougat-0175606/

**Comment by Kronopt** [comment]
That's outside the realm of this issue tracker.
YouTubeBackgroundPlayback in particular needs Xposed.

As for other means to enable youtube background playback, a quick search yielded (besides this app) a bunch of paid services/apps (like youtube red), lucky patcher and this not so friendly [method](http://www.androidauthority.com/play-youtube-in-the-background-with-this-trick-680915/).
You could also try to contact Lucky Patcher's developer about your phone crashes.

If you want to use YouTubeBackgroundPlayback, either downgrade android or wait for a nougat compatible version of Xposed

**Comment by esgie** [comment]
I will briefly respond as I am also the creator of that Lucky Patcher's
patch (grubbas is my other nickname).

It is possible to rebuild patched Youtube.apk even via Lucky Patcher
itself. But it will be impossible to login inside the app due to non-Google
signature.

pzdr
es

11.01.2017 9:25 PM "Kronopt" <notifications@github.com> napisał(a):

**Comment by th3an7** [comment]
@esgie Wow, I didn't know it is possible...

I just checked and it's working fine on latest YT app :D
Now, you're officially my God - please, teach me my master XD

**Comment by th3an7** [comment]
Little bit OT but is it also possible to add others quality options? Ex. my
Xperia M2 supports only 480p... I'd like to have 720p for 60 fps videos but
without Xposed it's not possible ATM... (I've been using App Settings
module to change app DPI for 720p... everything was smaller but it was
working :P)

Is it possible to do so with LP or do I have to change DPI in build.prop to
make it work again?

**Comment by Hacker432** [comment]
@esgie
Hi
Sorry to write to you here but I would like to inform you that your patch for YouTube background in lucky patcher doesn't work anymore with latest YouTube versions
(Tested on YouTube 12.15.55)

**Comment by esgie** [comment]
https://drive.google.com/file/d/0B2TnsPjj6dl4SzZBSkFXZ2h5QUE/view?usp=drivesdk

Please replace the file in Lucky Patcher data directory.
(/sdcard/Android/data/*.LACK/files/LuckyPatcher for default)
Kill LP and restart. Patch will now work.
PS its ready from a long time but the LP dev is... kinda hard in
communication.

pzdr
es

2 maj 2017 20:40 "Alexander" <notifications@github.com> napisał(a):

**Comment by Hacker432** [comment]
@esgie
Thank you very much, it works now :)

**Comment by hisfauetas** [comment]
@esgie
The google drive link you provide no longer works,
can you give another one please, thank you.

**Comment by gfokkema** [comment]
@esgie After replacing the files patching finishes successfully.
When starting youtube and then backgrounding, playback works for a few minutes or so.
Then playback suddenly stops, and background plaback won't work anymore, even after restarting or reapplying the patches.
Any suggestions?

PS: Thanks for making this possible in the first place! :)

**Comment by raulpetru** [comment]
@esgie your patch works! Mind to explain how you did get the data for the pattern and build the patch? I'd like to update it myself if it won't work in the future. Also how patching with Lucky Patcher still keeps the apps signature valid?

**Comment by TheSpartaPT** [comment]
OGYoutube look it up

_Sent from my Ulefone Gemini Pro using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Hacker432** [comment]
@TheSpartaPT OGYoutube sucks

**Comment by TechExhibeo** [comment]
Well, I think OGYoutube is discontinued officially by developer.
