### ISSUE TITLE
Media skip buttons are greyed out.

### ISSUE THREAD

**Issue by alexzkter** [pylerSM/YouTubeBackgroundPlayback#294]
Hi,

I've been a long time user of Xposed modules, one of which being PBMC to map physical keys to any action. I remember being able to change songs even with the screen turned off. But some day certain funny guy working for Google disabled the ability to do so by making their app immune to keyevents 87 and 88!!  
I think that's why the media next/previous buttons are disabled on the notification panel from your great module.

This is not exactly a request since I'm aware that if it were an easy thing to do it would've been already done...but I'm curious about it, really, is there a way to make the YouTube app sensitive to the aforementioned keyevents ? Would it consist of modifying the app itself (difficult/impossible unless you're a "hacker") or...would it be an extra Xposed module for example ??

Thanks for reading.

**Comment by th3an7** [comment]
The buttons are working only when using a playlist. I also don't know why Google didn't make them available outside of queues :P
We probably need to spam their product support forum to make them look at it...
