### ISSUE TITLE
YouTube acts like it's in the background when in the app

### ISSUE THREAD

**Issue by SirUltimateBass** [pylerSM/YouTubeBackgroundPlayback#297]
I'll get straight to the point. Update 2.0.1 shows the notification just like beta, but it also causes autoplay to be instant when you're in the app. Is there any code that can be modified so that the notification is only visible when YT is in the background? I personally keep autoplay enabled so music will automatically play when YT is in the background. But I haven't updated to 2.0.1 because the notification stays active when in the app which causes autoplay to start after I'm finished watching a video.[whilst in the app] Just asking if there's any code that can be modified to fix this issue. Any and all help is greatly appreciated

**Comment by th3an7** [comment]
Actually there is - if you want to make notification visible only in background, build new module apk with changed link to json file to this one [https://raw.githubusercontent.com/th3an7/YouTubeBackgroundPlayback/th3an7-BACKGROUND-ONLY/assets/hooks-1.json](url)

It's json from my fork and (as branch name says) it makes notification visible only in background (at least it should :P)

**Comment by SirUltimateBass** [comment]
@th3an7 Alright, I've recompiled the apk multiple times but to avail. As soon as I attempt to install it, I'm greeted with the wonderful "App not installed". I really don't mean to put more work on you, but is there a possibility that you can recompile it?

**Comment by th3an7** [comment]
Oops, my bad, sorry... Forgot to tell you that you would probably have
signature mismatch. Have you tried uninstalling old version before
installing that newly compiled by you? Try that first - if it won't work,
let me know so I can build it myself :P

**Comment by SirUltimateBass** [comment]
Yes, I have tried that, multiple times actually

**Comment by SirUltimateBass** [comment]
But no success

**Comment by th3an7** [comment]
Try this one then - https://drive.google.com/file/d/0B8j7vCsf6RXcaUhlU09FRENOYVk/view?usp=sharing

**Comment by SirUltimateBass** [comment]
Thanks man, I owe you one!
