### ISSUE TITLE
backround playback issues + other

### ISSUE THREAD

**Issue by lgg2w** [pylerSM/YouTubeBackgroundPlayback#3]
With screen off it works, however it uses a lot of cpu when opening youtube app, reloads video previews, notification bar stutters when opening from there.
Backround playback does not work. 
Lg G2 4.4.2.

**Comment by Vagelis1608** [comment]
I can confirm this.

**Comment by marcinsu** [comment]
Ok, on my android 4.4.4, background playing works.
My steps:
1. Open youtube playlist.
2. Off screen and on again, then you can see youtube in notification drawer.
3. Press home hardware or software button to leave youtube app.
4. Click on next button from youtube notification, after that you will see play button.
5. Play and voilà :)

**Comment by Bandithklh** [comment]
Dhigmkxg
