### ISSUE TITLE
Lock screen background doesn't reset after closing YouTube

### ISSUE THREAD

**Issue by alseambusher** [pylerSM/YouTubeBackgroundPlayback#30]
Background of the lock screen is set according to the video playing. However this stays even after closing YouTube. Desired behavior would be to reset the background once the YouTube app is closed.

OS: CM12 Lollipop
Device: Nexus 4

**Comment by pylerSM** [comment]
Yes, but no idea how to fix.

**Comment by ThatKawaiiGuy** [comment]
@pylerSM
You can't remove the feature to change the background? Or maybe you can save the object of what the previous lockscreen image was, and then once the user had closed the app, reassign the object to the lockscreen again? 

Just trying think stuff up.

**Comment by pylerSM** [comment]
If it wasn't obfuscated (reading code is very difficult, almost impossible), I would (try to) do it. But since code is obfuscated like hell, I will not spend days or weeks on it. Sorry.

**Comment by ThatKawaiiGuy** [comment]
@pylerSM don't worry about it, you've provided a great module regardless. I'll try to look for anything that can assist.
