### ISSUE TITLE
why so similar?

### ISSUE THREAD

**Issue by hybridsong** [pylerSM/YouTubeBackgroundPlayback#301]
so why the ic_launcher.png have a similar shape to a paw with baidu? making me anxious is baidu that is potentially harm to computer equipment etc...

**Comment by rebane2001** [comment]
It's just a coincidence, you don't get anxious when you see a real dog's paw in real life, why here?

**Comment by esgie** [comment]
That is why you are welcome to compile from source.

pzdr
es

2 lut 2017 11:15 "Hybrid Song" <notifications@github.com> napisał(a):

**Comment by th3an7** [comment]
AFAIK that paw is taken from actual Google apps. Google introduced something called "Dogfood" which is basically test/unpublished/slightly modified app build. Dogfood's logo is that little paw - that is why it is used in module logo :P

Anyway - module is not even shown in launcher so why do you have problem with that? Just recompile module from source with changed logo as @esgie suggested :P
