### ISSUE TITLE
Youtube red settings keep popping up. 

### ISSUE THREAD

**Issue by Radioplayer1997** [pylerSM/YouTubeBackgroundPlayback#303]
When I put YouTube in the background, the "background play" notification from YouTube red keeps appearing. Any ideas?

**Comment by Radioplayer1997** [comment]
This is on the most recent YouTube version 12.03.57

**Comment by NovaViper** [comment]
I have the same issue aswell

**Comment by SirUltimateBass** [comment]
While the notification is still in your notifications, open YouTube and then click the notification and accept whatever it says. It shouldn't pop back up again unless you clear YT's data. Post back here if that solved the issue.

**Comment by Radioplayer1997** [comment]
It stop doing it after a while, but before it randomly stopped; nothing fixed it. I did what you said, I cleared youtubes data, nothing fixed it... But like I said, after a while, it stop doing it.

**Comment by SirUltimateBass** [comment]
*Facepalm* No, you don't clear YT's data. You click on the notification when you're in the app. When you clear the data, it'll pop back up and bug you again. So, *don't clear the data!*

**Comment by Radioplayer1997** [comment]
Yes i know this, but I tired this to see if it would only do it once and not everytime. No ANYTHING I did made it still pop up.
