### ISSUE TITLE
Background play of Offline saved videos sometime doesn't work

### ISSUE THREAD

**Issue by SandPox** [pylerSM/YouTubeBackgroundPlayback#306]
As the title said, sometime I play offline saved video without network then background play or lock screen while it's playing then it will pause the video.
I need to exit YouTube app, turn on the network, go to YouTube apps, play the Offline saved video.. once the offline saved video is playing then I can turn off the network and background play other video normally but if I exit the YouTube app then I must do that workaround again.

**Comment by blackmetall95** [comment]
Having the same issue. 
In the older Beta builds where the notification is visible all the time I can play offline videos in the background. 
Post 2.0 I have to connect to the internet before I can have background playback, which is annoying as I do not have mobile data. Additionally if I accidentally close the notification with the X icon, I'll have to reconnect to the internet to re-enable.

Would greatly appreciate it if this was fixed.
