### ISSUE TITLE
stop working with 12.07.61

### ISSUE THREAD

**Issue by p5ik0** [pylerSM/YouTubeBackgroundPlayback#307]
Hello, today I have update the YouTube app with the last one (12.07.61) locale IT and the module had stopped working. Any idea to solve problem?

**Comment by th3an7** [comment]
Module sources updated - should work again in a while :)

**Comment by p5ik0** [comment]
Tnx!

**Comment by SirUltimateBass** [comment]
@th3an7  The APK you sent me a while back still works with YT 12.05.53 and in case it doesn't work with 12.07.61, I have found a way to easily edit the hooks.json with an APK editor on my phone. If you need any extra help with updating the hooks.json file, let me know and I'll get to work on it

**Comment by th3an7** [comment]
@SirUltimateBass you're talking about APK that's shows notification only in background? It works because I am updating them both at the same time :)
If you want to update .json files, just create new commit with changes :D

**Comment by SirUltimateBass** [comment]
@th3an7 You're the man, thanks!!
