### ISSUE TITLE
Not working- unfortunate phase

### ISSUE THREAD

**Issue by ConnerJSP** [pylerSM/YouTubeBackgroundPlayback#311]
The module no longer allows for background playback, the video stops like normal. With the recent updates I assume it's just the natural phasing out of these types of things. Not even sure a log would help in this circumstance. If so let me know!

**Comment by ConnerJSP** [comment]
Sorry, should've mentioned this occurred on the 12.10.58 release. Hadn't any problems before now.

**Comment by th3an7** [comment]
I'll try to update it :)
Should be working again in max. 1h...
