### ISSUE TITLE
Add support for Youtube Music?

### ISSUE THREAD

**Issue by Bonfaaaa** [pylerSM/YouTubeBackgroundPlayback#312]
I love this module, and this will better with youtube music background playback :D

**Comment by th3an7** [comment]
@esgie made custom patch for Lucky Patcher that works with Youtube Music... can't test it if it's still working because YT Music is not available in Poland...

But you should give it a try :)

**Comment by Bonfaaaa** [comment]
custom patch works :O
sorry for waste of time and thanks
i live in italy and i use a VPN :D
