### ISSUE TITLE
Asking a question

### ISSUE THREAD

**Issue by asdsadsadsa** [pylerSM/YouTubeBackgroundPlayback#313]
Hello guys, because i don`t have that much 3g data.
I want to ask: I open youtube app and play my music playlist then i lock the phone and the music continious to play thanks to that gereat app, so what kind of data does it download- only the audio stream=>(data economy) OR like a regular youtube video with sound + picture/video=>(more data consuming).

**Comment by Lightfire228** [comment]
You could download music from YouTube using DVDVideoSoft. Although that removes the ability to have random playlists. 

There's also a setting in YT that restricts videos to 480p on 3G

**Comment by PwnicornDev** [comment]
While running in background, only audio is downloaded.
