### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by shamsud** [pylerSM/YouTubeBackgroundPlayback#318]
Youtube v12.15.55 not working anymore. 
Is this me only or anybody else.

**Comment by th3an7** [comment]
Upload apk of YouTube app so I can update the module - there is no updated
YouTube .apk on apkmirror.com yet and I am getting them from Play Store
very late :P

**Comment by pm2kjiagm** [comment]
Here it is:
http://www.mediafire.com/file/j0424dk5v0h7u6s/YouTube_12.15.55.apk

**Comment by th3an7** [comment]
Sorry it took me so long :P

Should be updated in a minute - remember to kill YT app completely :)

**Comment by pm2kjiagm** [comment]
Now it works. Thanks a lot!

**Comment by shamsud** [comment]
Yeah its working. 
Thanks bro
