### ISSUE TITLE
stopped working V1.3.8

### ISSUE THREAD

**Issue by lisa977** [pylerSM/YouTubeBackgroundPlayback#32]
Not working with the latest V1.3.8 -YT 10.13.54 . notification bar showing ! .when  you click on ! mark (there was a problem while playing ,touch to retry )  mo matter what i do, i get the same error  .
I hope you will find a fix soon .
Thanks in advance .

**Comment by herny66** [comment]
I confirm the same error...tnx

**Comment by pylerSM** [comment]
I didnt test it myself, I just compiled it with required data from @esgie.

**Comment by esgie** [comment]
For me it's working nice
see screenshot: http://i59.tinypic.com/qqd46b.png

**Comment by pylerSM** [comment]
Thanks for confirmation

**Comment by herny66** [comment]
us 2:1...another positive testimony
bye

**Comment by xlollomanx** [comment]
Didn't work for me: if you switch off the screen with YouTube app opened it work, instead if you minimize YouTube it gave the error previously described.

**Comment by esgie** [comment]
there is indeed something wrong and sometimes exclamation mark appears instead of play/pause button.
Guess that is caused by referring to FIELD_PLAYBACK_CONTROL[id] before declaring that the id index is id = getVersionIndex(versionCode);

**Comment by pylerSM** [comment]
Okey, re-declared.

**Comment by herny66** [comment]
1.3.9 still the same error... exclamation mark appears instead of play/pause button.

**Comment by pylerSM** [comment]
Then this project ends.

**Comment by herny66** [comment]
Sin...is a module that deserves

**Comment by pylerSM** [comment]
Okey, I forgot "/s" :D I will have time to fix on day after tomorrow.

**Comment by esgie** [comment]
Try this test version
(built basing on genuine module v1.3.7 with smali code modifications, won't work on previous ytube versions AT ALL, different signature than the dev's so it might require complete uninstalling previous version):
http://www55.zippyshare.com/v/7RVo6awr/file.html

**Comment by herny66** [comment]
I uninstalled version 1.3.9.,reboot, installed the 1.3.9test1,reboot and now everything works fine!
tnx

**Comment by pylerSM** [comment]
Ok, but we need provide fix for all. Send pull request or show me know how.

**Comment by esgie** [comment]
Ok I found the bug. It was my fault.
Looked for some methods in a wrong place.
FIELD_PLAYBACK_CONTROL should remain "i" as in previous builds, so array is not really needed.
My test module (should now work with all supported youtube versions):
http://www51.zippyshare.com/v/62KhHGkp/file.html
Also created a pull request with code changes. I'm a newbie to "real" developing (more interested in reverse engineering) so I'm getting familiar with github and I'll try to propose changes thru Pull Request in the future.
Sorry again!!!

**Comment by esgie** [comment]
I confirm that the newest official update for the module is working perfectly, again :)

**Comment by herny66** [comment]
YES,is working perfectly...grazie
