### ISSUE TITLE
Youtube lucky patcher patch for 12.17

### ISSUE THREAD

**Issue by abhijeetramgir** [pylerSM/YouTubeBackgroundPlayback#320]
I have youtube version 12.17 . The patch in lucky patcher is not working, any help?
Thanks

**Comment by th3an7** [comment]
Check out this if you haven't done that yet - https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/293#issuecomment-298825442

**Comment by abhijeetramgir** [comment]
I tried that, it still didn't work, 
I replaced the file and applied the patch
Thanks
