### ISSUE TITLE
App does not work on YouTube 12.21.57

### ISSUE THREAD

**Issue by kurci2** [pylerSM/YouTubeBackgroundPlayback#325]
Just noticed that playback stops when I minimise YouTube app version 12.21.57.
I have tried killing the app and even restarting my phone.
I am using YouTube Background Playback 2.0.2

**Comment by kurci2** [comment]
I am using YouTube Background Playback 2.0.2

**Comment by th3an7** [comment]
I'll update it later... just noticed that this version is new and was just posted on apkmirror...

**Comment by th3an7** [comment]
It should work again :)

**Comment by kurci2** [comment]
And it does! Thank you 😊!
