### ISSUE TITLE
Questions about update process

### ISSUE THREAD

**Issue by HomeDipo** [pylerSM/YouTubeBackgroundPlayback#326]
Hello,

I am a big fan of your modules and I wanted to get into the coding myself. There are some modules I really love, but the developers have given up on them and I want to update it in their place, heck maybe even make a new one myself. I know you are busy, but even if it's just something small to push me in the right direction, I wanted to know how you know what to fix in a module that attaches to other apps? For example, when youtube updates and you have to update the module, how do you know what part you need to fix? With that information, I may be able to update other forgotten modules.
Thanks in advance!

**Comment by th3an7** [comment]
I am updating module like this:
- Decompile .apk of YouTube app after it gets updated by using apktool
- Convert .dex files to .jar
- Open converted .jar files and search for changed classes

The easiest method to find changes is just to ctrl+f already known code
(from previous update for example)...

But everything is changed depending on how the module you want to update is
build and how does it work :)

**Comment by HomeDipo** [comment]
Thank you for the quick response!
If I am understanding this correctly, regardless of how far apart the app versions are (for example Youtube 1.0 vs Youtube 5.0) you look for the differences and see what part of the module needs to be changed to fit into the new app? Though I did not make these modules I am trying to update is there a good way to go about this or is this just something that you get used to over time?

**Comment by iHelp101** [comment]
I have resurrected a few modules and wanted to chime in. To start you have to decompile the last working version of the app that was working with the module. With that you get the base of what is in the class, how the method is structured, etc. You then know what you need to look for in the newer versions of the app. 

You will eventually reach a point where an app completely changes and breaks a hook you had. This is where things get difficult and you have to hunt for new hooks. Certain apps are easier to find hooks for. Snapchat for example is a very tricky app to find hooks for, while Instagram in my opinion is quite simple.

**Comment by HomeDipo** [comment]
Thanks for the input!
It's funny that you mentioned Snapchat because the module I wanted to revive is for Snapchat. So I definitely have my work cut out for me but maybe I'll get lucky finding these hooks. Do you guys recommend any specific programs that help make this process a little easier?

**Comment by iHelp101** [comment]
I actually have a partially working version of SnapPrefs. The biggest issue with Snapchat is they removed one of the stories models used (To get stories images/videos). The snaps hooks still work from my testing. So with that you have to find a new hooks that will work for stories.

**Comment by HomeDipo** [comment]
Wow, that is perfect. Snapprefs is the first module I wanted to update. So everything works but saving stories?

**Comment by iHelp101** [comment]
My goal for SnapPrefs was only to get downloading working. I have no idea about the friends, location spoofing, and most of the other features. SnapPrefs last time I checked had close if not over 200 hooks. Some are going to be broken and need completely revamped (Stories is one of them). In my opinion is a very tricky module to start with. You might want to start with something that is not so locked down to start learning.

**Comment by HomeDipo** [comment]
Ya, you are probably right about that. But to be honest the stealth download button is the major thing I wanted to be updated as well. I never really used the other features much besides the auto save text and infinite time for viewing pictures/videos. Do you have any recommendations for easier modules to practice with?
