### ISSUE TITLE
App doesn't work on YT 12.23.57

### ISSUE THREAD

**Issue by Lyodster** [pylerSM/YouTubeBackgroundPlayback#328]
Took an update to YouTube app last night and background no longer works

**Comment by bubobih** [comment]
Yap i can confirm that its not working

**Comment by th3an7** [comment]
Yes, I am aware of that... new YT app has just been uploaded to apkmirror. It should be working again in max 2h :)

**Comment by th3an7** [comment]
It's should be working again :)

**Comment by bubobih** [comment]
Download?

**Comment by th3an7** [comment]
There is no need of downloading anything... Use 2.0.2

**Comment by LiorHaim** [comment]
@th3an7 - seems to stopped working after the last update to 12.23.60
Can you check?

**Comment by th3an7** [comment]
@Lior can you please post new apk? I don't see it on apkmirror yet...

**Comment by LiorHaim** [comment]
@th3an7 sure:
https://ufile.io/cqelu

If there's any other way I can help just let me know

**Comment by th3an7** [comment]
@LiorHaim can you check if it's working now? Force close YouTube and start it again :)

**Comment by LiorHaim** [comment]
@th3an7 works like a charm :) 
Thank you for the quick reply and fix!
