### ISSUE TITLE
No backward compatibility

### ISSUE THREAD

**Issue by Cypher01** [pylerSM/YouTubeBackgroundPlayback#329]
v2.0.2 doesn't work with YouTube <12.19.* anymore. The YouTube version should be checked and the old code should stay for backward compatibility.
(I intentionally use an older YouTube version)

**Comment by th3an7** [comment]
But why tho? 2.0.1 and 2.0.2 are exactly the same. There is no change in code apart from pointing to the second .json file...

**Comment by Cypher01** [comment]
Are you sure? I didn't study the source code exactly, but I realized that I get Ads with v2.0.2, but not with v2.0.1.

**Comment by th3an7** [comment]
Yes I am sure... I've updated it myself and apart from changing direct link
from old .json to the new one, there is nothing else changed. Your ads may
be because of other module/app...

This module does nothing more apart from adding background playback. It
does not integrate in ads - so it does not add them nor remove them...

**Comment by sigv** [comment]
The [hooks-2.json](https://github.com/pylerSM/YouTubeBackgroundPlayback/blob/master/assets/hooks-2.json) file does not have the versions that the [hooks-1.json](https://github.com/pylerSM/YouTubeBackgroundPlayback/blob/master/assets/hooks-1.json) has. I will try and get around to feeding in two JSON files so that we can do the `<= 12.17.54` versions the old file has.

@Cypher01, in the meantime, keep using the 2.0.1.

**Comment by sigv** [comment]
Pushed 20eb10ef895a2821eecc1d5c2bc366a5b88dc866 but I don't have any devices running on anything older than N right now and I do not want to mess around with testing this on an emulator, so @th3an7 will have to test it out.

**Comment by sigv** [comment]
I was planning on going the route of reading in two JSON files, but the main issue I faced was deciding how to deal with the `fallback` key of the JSONs. Most notably, whether differences in those should be handled in some fancy way or just one of them should be picked or whatever else should happen. So instead, we have one massive JSON which has all the multipliers and then under them the version codes the way they were prior to this change.

**Comment by th3an7** [comment]
Me neither... I have 7.1.2... where is that guy who wanted backwards
compatibility? Let him test it... I can build new apk but can't test it :P

**Comment by th3an7** [comment]
@Cypher01 can you please test if this works?
https://drive.google.com/file/d/0B8j7vCsf6RXcNFpGdXU0ZUxweFE/view?usp=sharing

Ideally it would be if you could test this in both YouTube app versions - old one which is working on 2.0.1 and latest one which is working on 2.0.2

~~Also, if this apk for some reason cannot be installed (system shows errors or sth), try uninstalling previous module version (I may or may not fucked up apk signature... again)~~

**Comment by Cypher01** [comment]
@th3an7 I'm going to test it on Genymotion, when I have time. Is this based on the actual state of your fork?

**Comment by th3an7** [comment]
This apk is build with changes that @sigv pushed...

Also my fork is just a copy of this one and this one is a master - modules apks are made from sources from this fork...
My fork has only one extra branch with modified json file that can make playback controls visible only when app is in background and not all the time. But apart from that, it's exact the same :)

**Comment by sigv** [comment]
Might want to do a rebuild which includes 4a4c1cb87305ca39ef021952be5e17ac30e12d52 for testing since I realized today that I forgot to traverse into the multiplier keys of the `hooks-3.json` file when I wrote the code yesterday. 🙂

**Comment by sigv** [comment]
And 685a5e5932408e90c089d796a00786949cb30a98.. _sigh_

**Comment by th3an7** [comment]
OK, so here it is - [updated apk with latest changes](https://drive.google.com/file/d/0B8j7vCsf6RXcUG9faFdvY0VkcDQ/view?usp=sharing)

**Comment by Phoenix09** [comment]
@th3an7: works

**Comment by th3an7** [comment]
So if it works, I'm adding that apk to xposed repo
