### ISSUE TITLE
Version 1.3.9 won't work on 4.4.2

### ISSUE THREAD

**Issue by wimaxgn2** [pylerSM/YouTubeBackgroundPlayback#33]
I already installed the YouTube latest version. I Have GT-N7100 running with 4.4.2.
Tried to Unistall reinstall..

**Comment by pylerSM** [comment]
Reinstallation wont work. Method/field/class name was again changed.

**Comment by wimaxgn2** [comment]
I see..If I will install the older version of YouTube. .will it work? By the way thank you for the reply :)

**Comment by esgie** [comment]
Recent build of the module supports the newest yt. Update the module, reboot, everything should work good.

**Comment by wimaxgn2** [comment]
Just updated the module to 1.4 today but still doesn't work. When my screen is off YouTube stops.  :)

**Comment by esgie** [comment]
Does notification show just after you start the movie? It should.
Are you sure you have enabled the module in xposed settings and rebooted?

**Comment by wimaxgn2** [comment]
No notification. I have enabled the module in xposed then rebooted my phone.

**Comment by wimaxgn2** [comment]
Maybe this could help https://www.dropbox.com/s/u4ddd2lwextx1j6/ytube.txt?dl=0  
I tried to save cat log to save this file

**Comment by esgie** [comment]
What I have found in log is that:
"This YouTube version is not supported yet."
Please install this apk:
http://www.apkmirror.com/apk/google-inc/youtube/youtube-10-13-54-android-apk-download/
Reboot and test.

**Comment by wimaxgn2** [comment]
Wow... it's now working thank you so much. I just wonder about the  YouTube app that was previously installed is the latest from Google play..

**Comment by esgie** [comment]
Me too.
Maybe there are some parallel builds for different dpi sizes (as in Google Drive or Google Play Services app) so the module need to be modified to support a whole range of build numbers and not only hardcoded, exact ones?
Can you uninstall the youtube which you have recently installed, reinstall an update from the store and upload the apk file somewhere? Or at least check the exact build number (you can do it via i.e. Titanium Backup by clicking the Youtube on app list, it should be something like 101354134)?

**Comment by wimaxgn2** [comment]
I already reinstall the update from the store
Here is the screen shot..
https://www.dropbox.com/s/ehxrh07xyzqsqoe/Screenshot_2015-04-09-21-36-21.png?dl=0

**Comment by wimaxgn2** [comment]
both version:10.13.54
build#:101354134
from playstore
build#:101354132

**Comment by esgie** [comment]
Yeah so they DO make various builds for various devices. Gosh.
http://www66.zippyshare.com/v/K6nqaBHP/file.html
I have compiled a test build that checks only first few digits of the version (i.e. 1013).
This approach may be also better for minor updates (for example from 10.11.53 to 10.11.54) as the obfuscation usually do not change between them so there will be no need of updating the module if so).
Please test it with both youtube versions. Thank you.
If everything is ok i will pull a request to the dev.

**Comment by wimaxgn2** [comment]
Hi sorry for the late reply.
both YouTube version works on your moded Module. :)

**Comment by esgie** [comment]
thanks for feedback, I have sent a commit proposal to pyler.

**Comment by wimaxgn2** [comment]
No problem. . Thank you too
