### ISSUE TITLE
No playback control via notification

### ISSUE THREAD

**Issue by V1an** [pylerSM/YouTubeBackgroundPlayback#330]
I there, just installed this module, background works perfectly, but I don't have the playback control via notification.

Xiaomi Note 4 (Global Version)
Android 6.0.1 MMB29M
MIUI 8.2 | Stable 8.2.5.0(MCFMIDL)

Anyway thanks for the work, much much appreciated

**Comment by th3an7** [comment]
What's your module and YT app versions?

**Comment by V1an** [comment]
YT : 12.21.57
module : 2.0.2
Xposed Framework 87 (MIUI edition 20161126)

**Comment by th3an7** [comment]
Are you sure your OS is not blocking YT notifications?
Post logcat or sth :)

**Comment by V1an** [comment]
Oh right, The YT notifications were disable, thanks :)
Sry for the false issue.
Thanks again for the module
