### ISSUE TITLE
Playback error with this specific song ?

### ISSUE THREAD

**Issue by truff215** [pylerSM/YouTubeBackgroundPlayback#331]
When I play specifically the following song, and go into background (home, tasks, or lock), it stops and youtube reports a playback error message like the image below.

https://www.youtube.com/watch?v=Vg4MCemVfq0

notification:
![bcvbvcb](https://user-images.githubusercontent.com/7253541/27511522-9fef93ec-5926-11e7-9d9e-6a9a3e078c93.jpg)

youtube video:
![fbfdbdf](https://user-images.githubusercontent.com/7253541/27511523-a17969f4-5926-11e7-9146-dc3688683d3b.jpg)

Running 2.0.2 with YT 12.23.60
It was also happening with 6 month old versions (hence why I updated, because I thought it was broken, but no luck).

Never seen this issue before, works perfectly with every other video/song, and it has done so for years so far. Just this song in particular... there could be others I guess.

**Comment by th3an7** [comment]
Hmm, just checked it and it also shows me that error...
Maybe Google/owner blocked background playback for that specific video...
Since every other video is playing fine in background, that may not be a
problem with module but with video itself...

**Comment by truff215** [comment]
Thanks for answering.

> Maybe Google/owner blocked background playback for that specific video...

I didn't know that was even possible.

> Since every other video is playing fine in background, that may not be a problem with module but with video itself...

I thought the same, but since I know nothing about how this module works, I figured reporting here was worth a shot.

Anyhow, if you feel like this is out of the range of this module, feel free to close this issue.
