### ISSUE TITLE
previous/next track not working

### ISSUE THREAD

**Issue by megabugman** [pylerSM/YouTubeBackgroundPlayback#333]
i'm using android 6.0.1, yt 12.23.60 abd ytbp 2.0.4 previous/next track buttons are greyed out and do not work.
issue 2, sometimes the playback stops all of the sudden.
anyone else experiencing this issues?

**Comment by th3an7** [comment]
Next/previous buttons are grayed out when you don't use playlist (so only autoplay is enabled) - that's not an issue with module but with Google not enabling that option...

About sudden stops - are you using some kind of app like Greenify? If you don't have much RAM on your device, system will kill YouTube and playback will stop by itself.

**Comment by megabugman** [comment]
I use autoplay and I never use playlist. In a previous Version of YT & YTBP buttons used to work, skipping Videos was possible without opening the YT APP.
Now with the current versions inside YT in list mode (small video on top) Next/previous buttons work, also in full screen mode. Pressing then home button then swipe down Next/previous buttons are greyed out, only close and Pause works. So ATM i need to open up YT to move to next/previous track. Also when screen is locked only Pause/play and close button is shown no Next/previous buttons, but that may be a complete different thing/enhancenment/issue.

Regarding the close issue, i dont use greenify but various other xposed modules. YTBP seems not to crash it simply stops and the YTBP view in background is gone. 

Thanks for your support.

**Comment by megabugman** [comment]
I am not sure if you are able to reproduce the issue. I noticed the buttons are not geyed out if a channels contains a playlist. After selecting a different Video after searching I mean a sole video the buttons are greyed out. I hope you get what I mean. Issue reproced as stated above in yt 12.13.53.

**Comment by megabugman** [comment]
ok, so apparently in a channel when selecting "VIDEOS" tab buttons are greyed out when swipe down and when screen locked buttons are missing. 

when selecting "PLAYLISTS" buttons work as expected also when screen is locked.

so in yt app directly buttons work as expected no matter if VIDEOS were selected.
