### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by dw24** [pylerSM/YouTubeBackgroundPlayback#338]
I copile it into an apk and install it but it doesn't work :(

**Comment by th3an7** [comment]
Do you have Xposed installed? What's your YouTube app version?

**Comment by dw24** [comment]
Yes, I have xposed. My youtube version is 12.34.54

**Comment by th3an7** [comment]
Try the one I left in https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/336

**Comment by dw24** [comment]
Doesn't work either :(

**Comment by dw24** [comment]
Yeah, what logs you want me to post?

**Comment by th3an7** [comment]
I think Xposed logs should do the work

**Comment by dw24** [comment]
![screenshot_20170903-201141](https://user-images.githubusercontent.com/2127009/30007764-286f4d58-90e4-11e7-8186-c2ac93989a72.png)
![screenshot_20170903-201112](https://user-images.githubusercontent.com/2127009/30007765-28701f26-90e4-11e7-8a32-e6f594b7f200.png)

There's no logs :/

**Comment by th3an7** [comment]
Can you post a screenshot of a main page of Xposed app? That where it says "Xposed Framework installed" etc.?

**Comment by dw24** [comment]
This one? 
![screenshot_20170903-201919](https://user-images.githubusercontent.com/2127009/30007819-3924393c-90e5-11e7-95eb-6c5b08ba9ad1.png)

**Comment by th3an7** [comment]
Something like this
![Xposed](http://www.appki.com.pl/wp-content/uploads/2015/03/xposed-framework-3.jpg)

**Comment by dw24** [comment]
![screenshot_20170903-202518](https://user-images.githubusercontent.com/2127009/30007853-127269ca-90e6-11e7-91d7-576c4cc9da53.png)
Here, but I used this framework on my phone and the module worked there

**Comment by th3an7** [comment]
Have you flashed framework .zip?

**Comment by dw24** [comment]
Yeah, it's an experimental framework for sdk version 23 (marshmallow) so manual flashing is the only way.

**Comment by th3an7** [comment]
And you've rebooted your device after flashing, installing and enabling apk?

If yes, then I don't know why it's not working...

**Comment by dw24** [comment]
Yeah, I did

**Comment by Eva850** [comment]
@dw24 You are using wrong Xposed Installer. This version is for Android 4.4 and older. For 5.0 and newer use this:
https//forum.xda-developers.com/attachment.php?attachmentid=3921508&d=1477916609
or this:
https://forum.xda-developers.com/devdb/project/dl/?id=26586&task=get
