### ISSUE TITLE
Dose not work

### ISSUE THREAD

**Issue by fawzy46** [pylerSM/YouTubeBackgroundPlayback#339]
Dose not work with last update 12.34.55

**Comment by th3an7** [comment]
Did you force closed YouTube/rebooted device? Check logs.

**Comment by fawzy46** [comment]
Yes I have rebooted my phone but dose not work,do you need xposed logs ??

**Comment by th3an7** [comment]
Yes, please. They should help for now.a

**Comment by fawzy46** [comment]
https://drive.google.com/file/d/0Bz9tTgInjOvlMm5aLU5JVTMyRTg/view?usp=drivesdk

Thx for the fast response

**Comment by th3an7** [comment]
Can you try disabling ad away? Also, is it whole log? I can't see anything
related to YTBP module. Maybe it's drive on phone not showing it. I will
check it again later.

**Comment by fawzy46** [comment]
I don't think the ad away is the proplem because I didn't update it and YTBP was working well before update youtube  but I will try to disable it and see what will happen and I will check the log again

**Comment by Gustorn** [comment]
I just want to add that it does not work for me either anymore. The Xposed logs are similarly useless:

```
09-07 16:52:03.029 I/Xposed  (  330): -----------------
09-07 16:52:03.029 I/Xposed  (  330): Starting Xposed version 87.1 (custom build by dkcldark / 20161129), compiled for SDK 21
09-07 16:52:03.029 I/Xposed  (  330): Device: GT-I9515 (samsung), Android version 5.0.1 (SDK 21)
09-07 16:52:03.029 I/Xposed  (  330): ROM: Built.with.SuperRs.Kitchen
09-07 16:52:03.029 I/Xposed  (  330): Build fingerprint: samsung/jfveltexx/jfvelte:5.0.1/LRX22C/I9515XXU1BQD2:user/release-keys
09-07 16:52:03.029 I/Xposed  (  330): Platform: armeabi-v7a, 32-bit binary, system server: yes
09-07 16:52:03.029 I/Xposed  (  330): SELinux enabled: yes, enforcing: yes
09-07 16:52:03.059 I/Xposed  (  330): -----------------
09-07 16:52:03.059 I/Xposed  (  330): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-07 16:52:03.469 I/Xposed  (  330): Detected ART runtime
09-07 16:52:03.489 I/Xposed  (  330): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-07 16:52:05.041 I/Xposed  (  330): Loading modules from /data/app/com.pyler.youtubebackgroundplayback-2/base.apk
09-07 16:52:05.071 I/Xposed  (  330):   Loading class com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback
09-07 16:52:05.091 I/Xposed  (  330): Loading modules from /data/app/ma.wanam.xposedlollipop-1/base.apk
09-07 16:52:05.121 I/Xposed  (  330):   Loading class ma.wanam.xposedlollipop.Xposed
```

I installed the version posted in #336 by @th3an7. I have also rebooted, force stopped YT and tried clearing application caches both in the OS and from the recovery menu. Relevant versions:

YouTube: 12.34.55
YT Background Playback: 2.0.4

**Comment by dakotagrvtt** [comment]
So far the only thing that has worked for me is to go down to a different version. Currently using 12.21.57 and no problems so far.

**Comment by th3an7** [comment]
Does the module work with the previous version of YT? I mean with 12.34.54?

If the answer is yes, then they indeed changed version naming and we need to find a fix for that.

The previous versions were named as XXXXXXXXXX (10 numbers), now they probably started to naming it as XX.XX.XX (as we can see it with-in the app). This may become a problem...

I can't recall if module writes something to logcat, but you can check it :P

**Comment by th3an7** [comment]
Can you check if it's working now? Apparently I've put wrong classes...

Seems like I shouldn't do anything at 4AM :P

**Comment by Gustorn** [comment]
Yup, working fine now. Thanks for the quick fix

**Comment by fawzy46** [comment]
It's working fine thx

**Comment by fawzy46** [comment]
Should I close the issue now??

**Comment by th3an7** [comment]
No need, I will do it :)

Glad it works again :P
