### ISSUE TITLE
Latest YT update 12.37.59 doesn't work 

### ISSUE THREAD

**Issue by LiorHaim** [pylerSM/YouTubeBackgroundPlayback#345]
12.37.59 not working on background.
Tried stopping the app and restart it, still doesn't work.
I guess something changed at YouTube's apk and needs your help :-)

**Comment by th3an7** [comment]
Check now... should work again - remember to reboot or FC YT :P

**Comment by LiorHaim** [comment]
You're awesome, as always. Working great, thanks!
