### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by malitech** [pylerSM/YouTubeBackgroundPlayback#347]
Do I have to build this every time? It stopped working after update. Now I have to build it again.

**Comment by th3an7** [comment]
Which version of YT do you have?

If the hooks are updated, you will just need to reboot or FC YT app - no need of rebuilding module's apk each time

**Comment by malitech** [comment]
12.39.60
I force stopped youtube several times and it still didn't work, rebooted many times, cleared data, cache of youtube.

**Comment by th3an7** [comment]
In your source code, there should be a direct link to a .json file (should look like https://raw.githubusercontent.com/pylerSM/YouTubeBackgroundPlayback/master/assets/hooks-3.json)
Maybe that's the problem?

Also you can check logcat and Xposed logs - they should tell you what's wrong

**Comment by malitech** [comment]
I just downloaded from this repo and imported in android studio and built it and it worked. I haven't changed anything.

There's nothing in xposed logs. I'm sure it will work if I build it again. Maybe something is blocking the raw.githubusercontent.com

I'll find out. Thanks for the help. : )

I get this during build:
Error:(4) Error: "app_name" is not translated in "cs" (Czech), "hu" (Hungarian), "ko" (Korean), "ru" (Russian), "sk" (Slovak), "uk" (Ukrainian) [MissingTranslation]

**Comment by th3an7** [comment]
That's nothing important - it just informs you there is no translations... but since the module doesn't have any UI, you can just ignore that error :)

**Comment by malitech** [comment]
Great, thanks

**Comment by SDMU** [comment]
@th3an7 in 12.39.60  I am not able to find "playability status is null" . I am following what you showed in the video . Is that outdated ?

**Comment by th3an7** [comment]
@SDMU unfortunately, yes... the G has changed YT app code a little... that class doesn't have any strings you can search for to make updates faster :P 

But the module is updated to work with that version so you just need to build .apk or find it somewhere on this repo :)
