### ISSUE TITLE
12.39.60 doesn't work

### ISSUE THREAD

**Issue by ArchidGM** [pylerSM/YouTubeBackgroundPlayback#348]
I try to change the assets in hooks-3 but it doesnt work too.

And how do you know what assets you need to use in every version, Where are you taking them, I'm sorry, I'm new.

**Comment by th3an7** [comment]
Why you want to change them? They are always the same - the content is always exact as the previous one - the only change is the class' name...

If you're building .apk on your PC and you want to have your own hooks, you need to change direct link in module source code. It should point to your .json file - if you won't change the URL, the hooks will be downloaded from this repo (if they are updated for current YT app)

**Comment by ArchidGM** [comment]
Hi, i try to change the assets because it doesn't work when i build the repo, sorry if i don't explain me well.
-I started to change the assets because I thought I could make it work but it was not.

**Comment by th3an7** [comment]
Are you using Android Studio to build an .apk? Does it show any error or you just installing module's apk and it "doesn't work"?

Do you have Xposed Framework installed, enabled module and rebooted device?
Check logcat/xposed logs - they should tell you what's wrong.

**Comment by ArchidGM** [comment]
Android Studio error:

////////
InvalidVirtualFileAccessException: Accessing invalid virtual file: file://E:/Angel/Escritorio/YouTubeBackgroundPlayback-master/build/generated/source/r/debug/com/pyler/youtubebackgroundplayback/R.java; original:32168; found:31843
////////

**Comment by th3an7** [comment]
https://stackoverflow.com/questions/42548968/android-studio-invalidvirtualfileaccessexception-accessing-invalid-virtual-fi

**Comment by ArchidGM** [comment]
I already fix the problem with Android Studio, when I compile I do not have any errors but when installing the apk and restart it still does not work.
My xposed works fine but YTB does not work.

Log Xposed attach
[xposed_error_20171013_163531.log](https://github.com/pylerSM/YouTubeBackgroundPlayback/files/1384063/xposed_error_20171013_163531.log)

**Comment by th3an7** [comment]
Can you temporarily disable Adaway?

Also, check logcat...

**Comment by ArchidGM** [comment]
Already disable YoutubeAdaway and restart but it still does not work

**Comment by th3an7** [comment]
Have you tried using one of .apk posted in https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/336 ?

**Comment by ArchidGM** [comment]
Yes but i think is curropt because i can't open it :(

**Comment by SDMU** [comment]
@th3an7 I am following the method you show in the video . I found the classes corresponding to background mode and audio policy but I cannot find the playability status is null . I don't understand what to look for in zho.class

**Comment by th3an7** [comment]
Nothing... you just need to find the class that looks the same as the
previous one :P

There should be more info how to find that one class easier somewhere on
this repo... probably by @esgie - he uses IDA Pro to find that class :P

**Comment by SDMU** [comment]
I see , thanks !

**Comment by r00tcracker** [comment]
Hey @th3an7 I am kinda new to this, and I am building the APK in Android Studio (I left a comment for you on your Youtube video on how to change the classes, Leonardo :) )
So when you say this 
"If you're building .apk on your PC and you want to have your own hooks, you need to change direct link in module source code. It should point to your .json file - if you won't change the URL, the hooks will be downloaded from this repo (if they are updated for current YT app)"

Does that mean modify this line 
public static final String HOOKS_DOWNLOAD_URL = "https://raw.githubusercontent.com/pylerSM/YouTubeBackgroundPlayback/master/assets/hooks-3.json";

To whatever my directory with the modified JSON file is right?
Thanks for all your help

**Comment by th3an7** [comment]
Yes but you must upload it somewhere where it's possible to read it's
content (possibly some sort of FTP server or your own GitHub fork)

If you'll input your local path (something like C:/XXX/ etc.) it won't work
because all hooks are downloaded remotely when opening YT app.

**Comment by r00tcracker** [comment]
Gotcha @th3an7 
Thanks :)

**Comment by r00tcracker** [comment]
@th3an7 Sorry man, I don't know where to ask this.
Is this module compatible with the official Xposed for Nougat?
Thanks

**Comment by th3an7** [comment]
@r00tcracker apparently it does (https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/336#issuecomment-335034163)

**Comment by VladMano** [comment]
Did anyone try with 12.40.60 though?

**Comment by r00tcracker** [comment]
@VladMano Yeah, I created a fork from here and updated it for 12.40.60.
If you can't wait for @th3an7 to update, you can get it from here. (you will need to compile the APK, and this is pointing to my fork.
https://github.com/r00tcracker/YouTubeBackgroundPlayback
Hope this is ok @th3an7 ,if not , please delete this reply :)
