### ISSUE TITLE
Notification not dismissable using swipe

### ISSUE THREAD

**Issue by TimoVer** [pylerSM/YouTubeBackgroundPlayback#35]
Hi PylerSM! 

First off, love this module! But just had one request: is it possible to make the notification dismissable by swiping (maybe only when the video is paused or something). Is kinda annoying that the notification only disappears (in my case)  when the youtube app is closed. 

Thanks!

**Comment by deaddysBoy** [comment]
You can close it with the little x in the right upper corner...

**Comment by TimoVer** [comment]
My apologies, didn't see this X button directly ;). Thank you!
