### ISSUE TITLE
Won't dowbload

### ISSUE THREAD

**Issue by rcolitz** [pylerSM/YouTubeBackgroundPlayback#350]

**Comment by rcolitz** [comment]
I can't get it to download at all all 3 versions, alpha, beta, or stable won't download. I have a Samsung galaxy on5 (SM-G550T1). I noticed that lucky patcher is unable to successfully patch it for background play as well.

**Comment by th3an7** [comment]
Check this https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/342#issuecomment-340016238
