### ISSUE TITLE
Will you update version 2.0.4?

### ISSUE THREAD

**Issue by BlackGhost12** [pylerSM/YouTubeBackgroundPlayback#358]
Because version 13.01.52 does not work at all except YouTube.

**Comment by th3an7** [comment]
What you mean it's not working?
Did you install latest version from https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/336#issuecomment-361030649?

**Comment by BlackGhost12** [comment]
It worked when I restarted the device. Hassle free on new YouTube versions.

**Comment by th3an7** [comment]
Your question is now answered I guess :D 

Check #357
