### ISSUE TITLE
crashes on Android 7.0

### ISSUE THREAD

**Issue by 7ala** [pylerSM/YouTubeBackgroundPlayback#363]
after I updated YouTube to 13.33.54 last night it crashes when I send it to background even when the video is paused, but it works well when I disable the the background playback module from exposed modules list.

**Comment by th3an7** [comment]
I've changed one letter... can you check if it still crashes?
Reboot and force close YT app

**Comment by 7ala** [comment]
idk how did you do that 🤔, I mean I didn't download any update just enabled it again and rebooted and it's working very well 😅😅, thanks.

**Comment by th3an7** [comment]
As I said... I've changed one letter as it can be seen in https://github.com/pylerSM/YouTubeBackgroundPlayback/commit/00d5017c42f089ca2294de274e3f2091cc9ed333 commit...

Seems like this fixed the issure... at least i hope so :)
