### ISSUE TITLE
13.35.51 Not working

### ISSUE THREAD

**Issue by BibleBeliever** [pylerSM/YouTubeBackgroundPlayback#364]
Hi. I really hope this is just me, but the latest YT version isn't playing in the background.

**Comment by th3an7** [comment]
Haven't updated it yet...

Will do it later today

**Comment by BibleBeliever** [comment]
Thanks a million, sir. I super-appreciate your hard work. This is the first
time this happened in a long time, though. That's why I'm here.

God bless you
