### ISSUE TITLE
Create a release page for YTBP

### ISSUE THREAD

**Issue by KoziLord** [pylerSM/YouTubeBackgroundPlayback#366]
Currently to download the current version of YTBP you have to look for the link in the issue #357 [containing the downloads](https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/357#issuecomment-379087066).
A release page should make it easier to find the current build.

**Comment by th3an7** [comment]
That's the problem... It was removed from Xposed repo not on purpose...
I, myself, don't want to make whole repo disappear for distributing apk
file or something...

But if you want you can check my fork if that's what you looking for...

**Comment by KoziLord** [comment]
I see, I guess this issue can be closed then.
