### ISSUE TITLE
 Please tell me the role of these json files

### ISSUE THREAD

**Issue by ohyeah521** [pylerSM/YouTubeBackgroundPlayback#372]
Hello, I am a developer. What is the difference between asking these json files?

hooks-1.json           // what about this?
hooks-2.json             // what about this?     
hooks-3-41.json      // android4.4+
hooks-3.json             // android 5.0+

**Comment by th3an7** [comment]
Those are hooka files with all classes that should be modified by Xposed
Framework

Those 2 first are old files that were used when module wasn't being updated
remotely...

First one is super old so it can be skipped...
Second one is for version 5.0+ that was used in previous versions and it
still could be used so I am keeping it updated just in case...
Third and forth are current hooks for Android 5.0+ and Android 4.2+ - they
are separate because classes in those versions are different from each
other.

**Comment by ohyeah521** [comment]
Thank you, I know, this is the new configuration of YT 142350 version, I am not familiar with the usage of GitHub, submit it here.
## hooks-3-41.json
-----------------------------------------------------
    "142350": [
            { "class_name": "ahnf", "method_name": "m", "parameter_types": [], "actions": [
                { "name": "set_field_boolean_before_method", "field_name": "k.b", "value": true }
            ] },
            { "class_name": "dyk", "method_name": "f", "parameter_types": [], "actions": [
                { "name": "return_string", "value": "on" }
            ] },
            { "class_name": "aixs", "method_name": "d", "parameter_types": [ "atmi" ], "actions": [
                { "name": "return_boolean", "value": true }
            ] }
        ]
-----------------------------------------------------

## hooks-3.json
-----------------------------------------------------
    "142350": [
            { "class_name": "ahsi", "method_name": "m", "parameter_types": [], "actions": [
                { "name": "set_field_boolean_before_method", "field_name": "k.b", "value": true }
            ] },
            { "class_name": "dwu", "method_name": "f", "parameter_types": [], "actions": [
                { "name": "return_string", "value": "on" }
            ] },
            { "class_name": "ajcv", "method_name": "d", "parameter_types": [ "atro" ], "actions": [
                { "name": "return_boolean", "value": true }
            ] }
        ]
-----------------------------------------------------

**Comment by th3an7** [comment]
Thanks :D
I've added those hooks - should work again
