### ISSUE TITLE
A little doubt.

### ISSUE THREAD

**Issue by ohyeah521** [pylerSM/YouTubeBackgroundPlayback#385]
Hook-3.json has two fields, x1000 and x10000, what is the difference between the two?

**Comment by th3an7** [comment]
It's the multiplier for YouTube app code version - ex. 14.33.55 arm64-v8a,
nodpi, Android 5.0+ code version is 1433563400 = 143355 * 10000...

It just "skips" cpu + dpi number differences and leaves main YouTube
version number

**Comment by ohyeah521** [comment]
@th3an7  Thank you, I understand.
