### ISSUE TITLE
Screen off playing not working 

### ISSUE THREAD

**Issue by pasomnica** [pylerSM/YouTubeBackgroundPlayback#4]
I tried both supported versions, 10.03.5 and 10.04.5 but none of them work. 

Yt started playing song, I turned screen off and playback immediately stopped. After I turn screen back on, playing window displays "There was a problem while playing. Touch to retry" message. 

No notification in drawer, anything. Module properly enabled in Xposed Installer. 

Acer Liquid Z500, stock 4.4.2, MT6582

**Comment by pasomnica** [comment]
Same behavior with 1.0.2 and 10.05.6

**Comment by pylerSM** [comment]
Interesting. I don't know why it works some (for me yes) and for others not. 
I may unpublish module and keep it for myself only.

**Comment by pylerSM** [comment]
Today I once again spent some time to find issue.. Not successful, but I still have ideas. Unpublishing is the last thing to do if eveything fails.

**Comment by octoshrimpy** [comment]
Galaxy nexus user here. It doesn't appear to work, although the first time the screen got turned off, it stuttered for a few seconds, then stopped. I'm willing to be a guinea pig for you if you want, would love to wee this module working.

**Comment by renovatio2** [comment]
Thanks, i'm following you!

2015-02-08 20:07 GMT+01:00 pyler <notifications@github.com>:

**Comment by pasomnica** [comment]
I'm here to help with anything. If you need logs or something, just tell me. I'm willing to help because this module has so much potential.

**Comment by octoshrimpy** [comment]
Just saw a music-like notification with a YouTube video on there. Tapped on play, nothing happened. Tapped on the icon, it took me to YouTube. Cannot replicate the notification.

**Comment by Chance4ever** [comment]
Working just fine on my note 4.   Thanks

**Comment by jacobyo7** [comment]
I have the same issue than the autor on my Xperia Z1 compact running stock 4.4.4 Sony Rom, but it work just find whit my chinese tablet (onda v989 running 4.4.4 stock onda Rom)

Thank you by the way, it is gonna be useful on my tab.

**Comment by pasomnica** [comment]
@pylerSM Today, screen off playback suddenly started working. Not sure what was the reason, I just moved app to /system, nothing more. My first thought was Greenify, but it was not it.

Still, after going to homescreen, playback stopped after like two seconds, then notification stay like this.
http://i.imgur.com/FmI8Yxb.png

Finally, at least I can use one of those features, thank you so much!

**Comment by marcinsu** [comment]
Ok, on my android 4.4.4, background playing works.
My steps:
1. Open youtube playlist.
2.  Off screen and on again, then you can see youtube in notification drawer.
3. Press home hardware or software button to leave youtube app.
4. Click on next button from youtube notification, after that you will see play button.
5. Play and voilà :)

**Comment by pasomnica** [comment]
@pylerSM Okay, I've found the reason. AcDisplay has a feature called Active Mode, where it turns screen on based on proximity sensor or when notification arrived from any kind of service. 

Right after my sensor starts shining red (I hope all sensors are doing this), YT playback stopped. Disabling this feature makes screen off playback back working. 

I'm not sure if you can do anything about this, but I'll sure write to dev about this.

**Comment by pylerSM** [comment]
ok, so solved.
