### ISSUE TITLE
yt 10.14.56

### ISSUE THREAD

**Issue by herny66** [pylerSM/YouTubeBackgroundPlayback#40]
new version
 without haste, just to warn...tnx

**Comment by TheOnlyRealTGS** [comment]
Using 1.4.2 and it doesn't work with this version.

**Comment by herny66** [comment]
new yt 10.15.54 ...will never end :D

**Comment by esgie** [comment]
Pulled the source code commit to the dev already.
Guess he will compile and update the module in the nearest future ;)

**Comment by pylerSM** [comment]
Will merge soon.

But, after this summer, I doubt I will be able to maintain it as I should. So in the summer I hope I can move project to esgie or someone who can maintain it quite well.

**Comment by esgie** [comment]
Guess i can handle it. We'll get back to the subject when needed.

**Comment by TheOnlyRealTGS** [comment]
Seems like it works! You can close this.

**Comment by herny66** [comment]
new yt 10.16.53...

**Comment by pylerSM** [comment]
@esgie , what is your nick on XDA? to add you as another dev in repo.

**Comment by esgie** [comment]
It's... esgie ;)
