### ISSUE TITLE
YouTube crashes with Android 5.1, Xposed Super Alpha and YBP module

### ISSUE THREAD

**Issue by dekefake** [pylerSM/YouTubeBackgroundPlayback#41]
Logcat 
I/System.out( 5791): YouTube MDX: MDX video stage moved to NEW
I/System.out( 5791): YouTube MDX: MDX video player state moved to UNSTARTED
I/System.out( 5791): YouTube MDX: MDX ad player state moved to UNSTARTED
D/PowerManagerService(  911): acquireWakeLock: ignoring request from com.google.android.gms
D/PowerManagerService(  911): acquireWakeLock: ignoring request from com.google.android.gms
D/PowerManagerService(  911): acquireWakeLock: ignoring request from com.google.android.gms
I/ThermalEngine(  253): TM Id 'VDD_DIG_SWMODE_MONITOR-TSENS8' Sensor 'tsens_tz_sensor8' - alarm raised 1 at 86.0 degC
D/PowerManagerService(  911): acquireWakeLock: ignoring request from com.google.android.gms
D/PowerManagerService(  911): acquireWakeLock: ignoring request from com.google.android.gms
D/PowerManagerService(  911): acquireWakeLock: ignoring request from com.google.android.gms
D/PowerManagerService(  911): acquireWakeLock: ignoring request from com.google.android.gms
D/PowerManagerService(  911): acquireWakeLock: ignoring request from com.google.android.gms
D/AndroidRuntime( 5791): Shutting down VM
E/AndroidRuntime( 5791): FATAL EXCEPTION: main
E/AndroidRuntime( 5791): Process: com.google.android.youtube, PID: 5791
E/AndroidRuntime( 5791): java.lang.RuntimeException: Unable to instantiate service com.google.android.apps.youtube.core.player.BackgroundPlayerService: java.lang.IllegalArgumentException: Wrong number of arguments; expected 1, got 0
E/AndroidRuntime( 5791):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2762)
E/AndroidRuntime( 5791):        at android.app.ActivityThread.access$1800(ActivityThread.java:154)
E/AndroidRuntime( 5791):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1389)
E/AndroidRuntime( 5791):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5791):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 5791):        at android.app.ActivityThread.main(ActivityThread.java:5274)
E/AndroidRuntime( 5791):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5791):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5791):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 5791):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 5791):        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
E/AndroidRuntime( 5791): Caused by: java.lang.IllegalArgumentException: Wrong number of arguments; expected 1, got 0
E/AndroidRuntime( 5791):        at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime( 5791):        at java.lang.Class.newInstance(Class.java:1606)
E/AndroidRuntime( 5791):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2759)
E/AndroidRuntime( 5791):        ... 10 more

**Comment by esgie** [comment]
Working well with both 4.x and 5.0.x.
Seems like xposed for 5.1 super alpha issue. Afaik a lot of modules is not working with it atm.
Guess you'll have to wait for more stable xposed for 5.1 or downgrade your android...

**Comment by dekefake** [comment]
Okok no problem. I will wait ;)

**Comment by cruzrincon** [comment]
Not crashing forma me, but not working on 5.1 súper alpha either. Will wait

**Comment by pylerSM** [comment]
I dont support other than stable Xposed releases.
