### ISSUE TITLE
I built the app with gradlew, what do i do next?

### ISSUE THREAD

**Issue by rgeorge04** [pylerSM/YouTubeBackgroundPlayback#424]
i managed to build the app succesefully
![image](https://user-images.githubusercontent.com/44336301/117209381-ed54fb00-adfe-11eb-8004-3b1b216f4933.png)

but what do i do next? how do i make it a module for edxposed?

![image](https://user-images.githubusercontent.com/44336301/117209226-bf6fb680-adfe-11eb-8910-b66f297a7ec7.png)

**Comment by th3an7** [comment]
It should just generate .apk file you need to install - check "build" folder

Alternatively if you just want module .apk without any changes, you can find pre-built one on my fork (either in releases or in artefacts)

**Comment by rgeorge04** [comment]
> It should just generate .apk file you need to install - check "build" folder
> 
> Alternatively if you just want module .apk without any changes, you can find pre-built one on my fork (either in releases or in artefacts)

i checked the build folder but didnt find any apk. Also i ran gradlre check command and it gives me this error 
![image](https://user-images.githubusercontent.com/44336301/117280441-45c1e200-ae6b-11eb-81f8-1de44273d5f4.png)
i don't understand it, what annotations?

**Comment by rgeorge04** [comment]
> > It should just generate .apk file you need to install - check "build" folder
> > Alternatively if you just want module .apk without any changes, you can find pre-built one on my fork (either in releases or in artefacts)
> 
> i checked the build folder but didnt find any apk. Also i ran gradlre check command and it gives me this error
> ![image](https://user-images.githubusercontent.com/44336301/117280441-45c1e200-ae6b-11eb-81f8-1de44273d5f4.png)
> i don't understand it, what annotations?

nevermind i fixed the issue
i installed the app from pc using the command installDebugAndroidTest, i can see the app in apps manager, but dont know how to actually make it work

**Comment by rgeorge04** [comment]
> > > It should just generate .apk file you need to install - check "build" folder
> > > Alternatively if you just want module .apk without any changes, you can find pre-built one on my fork (either in releases or in artefacts)
> > 
> > 
> > i checked the build folder but didnt find any apk. Also i ran gradlre check command and it gives me this error
> > ![image](https://user-images.githubusercontent.com/44336301/117280441-45c1e200-ae6b-11eb-81f8-1de44273d5f4.png)
> > i don't understand it, what annotations?
> 
> nevermind i fixed the issue
> i installed the app from pc using the command installDebugAndroidTest, i can see the app in apps manager, but dont know how to actually make it work

nevermind i found the solution, i had to activate it as an edxposed module, i can close the quiestion now
