### ISSUE TITLE
Youtube Background was working fine, but today i checked it out and its not wroking anymore

### ISSUE THREAD

**Issue by rgeorge04** [pylerSM/YouTubeBackgroundPlayback#425]
I installed the app using gradlew and it was working fine at first, but now its simply not working anymore. i don't know what happened. Please help me. If you need additional information tell me where to look for it and i will show you. Thanks

edit: the app is version 2.0.5

**Comment by th3an7** [comment]
If you've recently updated YouTube app (or you have auto-updates on), that's probably why module stopped working - hooks (classes) must be updated for each new version of YT app...
Either downgrade to last working version (which would be 16.16.38), update hooks yourself or wait until someone makes PR...

If you didn't update anything, check Xposed logs (or EdXposed or whatever else you're using) - it should say why it doesn't work


If new YT version was just released, let me know what's the new version number is and I'll try to update classes

**Comment by rgeorge04** [comment]
> If you've recently updated YouTube app (or you have auto-updates on), that's probably why module stopped working - hooks (classes) must be updated for each new version of YT app...
> Either downgrade to last working version (which would be 16.16.38), update hooks yourself or wait until someone makes PR...
> 
> If you didn't update anything, check Xposed logs (or EdXposed or whatever else you're using) - it should say why it doesn't work
> 
> If new YT version was just released, let me know what's the new version number is and I'll try to update classes

youtube was last time updated on 29 april, but i installed the module 3 days ago aka 6 may. So i don't know whats the cause.
either wasy i dont know how to downgrade the youtube version through google play,
but i am interested how to update the classes of the module.

**Comment by th3an7** [comment]
What's the YT app version tho? Also check logs - it will tell you why it doesn't work (either "can't find class `xxx`" or something like that or it will say something else)

For updating classes - if you have IDA Pro (dunno if it works with free version... probably only .idc scripts) you can check my fork with [IDA-Script branch](https://github.com/th3an7/YouTubeBackgroundPlayback/tree/IDA-Script) - it should help

**Comment by rgeorge04** [comment]
> What's the YT app version tho? Also check logs - it will tell you why it doesn't work (either "can't find class `xxx`" or something like that or it will say something else)
> 
> For updating classes - if you have IDA Pro (dunno if it works with free version... probably only .idc scripts) you can check my fork with [IDA-Script branch](https://github.com/th3an7/YouTubeBackgroundPlayback/tree/IDA-Script) - it should help

i tried to disable DISABLE_FLAG_SECURE module but it didn't help
here is the log, maybe you can decipher it
https://drive.google.com/file/d/13PFDtb6SZNUzTNxvI019RGlFTRcSWtbX/view?usp=drivesdk

**Comment by th3an7** [comment]
Hmm... There is nothing on there apart from which modules are loaded...

What about logcat? Do you know how to check logcat logs? Maybe those will say more

I still don't know which YouTube version you're using - is it 16.16.38 or newer/older?

**Comment by rgeorge04** [comment]
> Hmm... There is nothing on there apart from which modules are loaded...
> 
> What about logcat? Do you know how to check logcat logs? Maybe those will say more
> 
> I still don't know which YouTube version you're using - is it 16.16.38 or newer/older?

my youtube version is 16.17.36
how do i find logcats?

**Comment by th3an7** [comment]
See? You should check that at first - your YT app version is newer than the latest supported one by the module, that's want it doesn't work...

I'll try to update hooks later today

**Comment by th3an7** [comment]
Hooks updated - force close YT app and it should work again

I recommend disabling auto-updates in Play Store to avoid issues again :P
