### ISSUE TITLE
Please make a hook for version 16.25.37

### ISSUE THREAD

**Issue by rgeorge04** [pylerSM/YouTubeBackgroundPlayback#428]

**Comment by th3an7** [comment]
[Added](https://github.com/pylerSM/YouTubeBackgroundPlayback/commit/48c6c30c825ddcbafbecbfccae3125e3ea5affea) - let me know if it works...

Remember to force close YT app or restart device to apply new hooks

**Comment by rgeorge04** [comment]
> [Added](https://github.com/pylerSM/YouTubeBackgroundPlayback/commit/48c6c30c825ddcbafbecbfccae3125e3ea5affea) - let me know if it works...
> 
> Remember to force close YT app or restart device to apply new hooks

yes it works ,thanks a lot :D

**Comment by th3an7** [comment]
No problem :D

Gonna close this issue then - if there are any issues, just reopen :P

**Comment by rgeorge04** [comment]
also had to point out that this build doesn't work out of the box, if you just run gradlew build, it will return an error like this one https://stackoverflow.com/questions/32149220/androidstudio-sdk-directory-does-not-exists 
i have to manually create local.properties and add that line for it to work 
sdk.dir = C\:\\Users\\USER\\AppData\\Local\\Android\\sdk
at least if you specify this in readme...

**Comment by th3an7** [comment]
If you just want pre-build .apk, you can download it from GitHub Actions from my fork - it's exactly the same as it uses hooks from this very repo - I've just set automatic builds

https://github.com/th3an7/YouTubeBackgroundPlayback/actions

Those are debug builds - they are not signed with any keys, but they are safe to install. If you're using them, you don't have to install new versions everytime it gets build - latest one should be enough as all of them are exact same and should use same hooks
