### ISSUE TITLE
YouTube app not responding for a few seconds when it comes to the foreground

### ISSUE THREAD

**Issue by errmalt** [pylerSM/YouTubeBackgroundPlayback#48]
when I have this module enabled, the YouTube app gets stuck for literally a few seconds whenever I switch to it. the video is stuck and the UI does not respond at all, for example scrolling through the comments is impossible. the audio does play though, even while the rest of the app is stuck.

**Comment by errmalt** [comment]
the same thing happens while opening youtube videos from other apps

**Comment by errmalt** [comment]
sorry for triple posting. I can't edit posts with the mobile client. what I I mean in the last post is that when I click on a youtube link inside a browser, or feedly, or any other app and that app opens YouTube using an intent, the YouTube app is also stuck for a few seconds in that scenario.

this is on a note 3 n9005 with stock 4.3

tell me if you need any more info like logcat output for example.

**Comment by silverrants** [comment]
Having the same problem. Videos often freeze with unresponsive UI. Running stock Verizon LG G3.

**Comment by silverrants** [comment]
No audio for me though. Video doesn't load at all. Had to uninstall.

**Comment by ds84182** [comment]
Same thing happening here on my Moto X 2013 running 4.4.4. I found it very annoying so I also had to uninstall.

**Comment by ds84182** [comment]
Same thing happening here on my Moto X 2013 running 4.4.4. I found it very annoying so I also had to uninstall.

**Comment by esgie** [comment]
Do you guys maybe use Flat Style Colored Bars module?
I had some lags in yt app recently neverthless if the YouTubeBackgroundPlayback was enabled or disabled.
I was investigating the problem and the probable cause was FSCB module which causes disturbing yt lags after some recent updates. The problem is discussed in the module thread on xda. Anyway, after disabling it I experience no lags or freezees.

**Comment by errmalt** [comment]
No, it's definitely this YouTube module in my case.
