### ISSUE TITLE
How to set this app up in general (...NO FUNCTION, maybe because of wrong handling)? 

### ISSUE THREAD

**Issue by jojo1969** [pylerSM/YouTubeBackgroundPlayback#49]
I installed  the latest apk (v1.46) on a Samsung Galaxy S3 (i-9300) running CM11 (Snapshot 11-20141115) with YT (v10.18.55). 
However after the installation, I do neither see any selectable icon of the app, nor did the behavior of YT change at all and the app itself is visible in Apps.Downloaded but not listed as "active".

Sorry for maybe asking a silly question but what else is required to start the "app" properly up? Am I supposed to start YT via the icon of the app or is all the magic done (automatically) in the background?

Anyway thanks for the great work that you guys have been doing - obviously the app is running fine on other devices (...with maybe smarter users).

Thank  you very much and keep going!

**Comment by esgie** [comment]
This app is a xposed framework module.
See here: http://repo.xposed.info/module/de.robv.android.xposed.installer
You have to install xposed framework first then enable this module via xposed installer app.

**Comment by jojo1969** [comment]
Thank you very much!!!!! ....got it, did it and it just works ;)
