### ISSUE TITLE
support 10.02.3

### ISSUE THREAD

**Issue by litlnicky** [pylerSM/YouTubeBackgroundPlayback#5]
hi any chance u could add support for youtube version 10.02.3 ? its just i use black youtube from team blackout and thats their latest,,everything is working fine on latest stock  youtube, background playback and app switching loll, its friggin awesome !!!!!! big thanks

**Comment by pylerSM** [comment]
Soon.

**Comment by nickyvalentino** [comment]
thanku!!!!!!!!
