### ISSUE TITLE
last 2-3  updates not installing :(

### ISSUE THREAD

**Issue by moly82** [pylerSM/YouTubeBackgroundPlayback#50]
hi, I'm stuck with version 1.4.4 because all next updates i tried to install couldn't be installed ("there is already a package with the same name installed and signature in conflic " error message, see attachment: https://www.dropbox.com/s/g7cep25n2g9ns3e/Screenshot_2015-05-23-20-10-07.png?dl=0 )

all previous versions could be installed just fine... ;)

lp 5.0.2 xposed alpha4

all other modules are installing/updating/working fine ;)

thanks in advance bye!

**Comment by esgie** [comment]
You just have to uninstall 1.4.4 first then install the update! There was a clear info about that in 1.4.5 update description!
The reason of the above is that the original dev, pyler, passed this project to me and I use my own signature to sign the app. So there is a signature mismatch between <=1.4.4 and >=1.4.5.
Further updates shall install without any issues or uninstalling.

**Comment by moly82** [comment]
sorry mate, didn't see that info.. my bad!!! :((

will try immediately thanks a lot for the fast reply!! :)
