### ISSUE TITLE
1.5.0 semi-functional on Slimcat 4.4.2

### ISSUE THREAD

**Issue by TeamFail** [pylerSM/YouTubeBackgroundPlayback#51]
I'm not entirely sure what's causing it, but background playback does work, only if I turn off the screen while running the YouTube app. If I switch from the app, the video pauses, and getting it to start from the notification shade doesn't seem to work. The video will resume once I pull up the app again though.

I just upgraded from my stock rom just the other day, which was 4.2.2, and it worked properly on that, so I'm wondering if it's the OS change that's causing issues, or if it's the ROM itself. If you want, I can grab a logcat while running a video for you if there's any important output that you can make use of.

As well, I probably won't make a merge request because I'm unsure as to how it works here yet, but I whipped up a French translation (It's not my first language, but I've learned enough in the past and I still need some practice every now and then) for you:

app_name: Lecture de Fond YouTube
app_description: Activer lecture de fond en YouTube

**Comment by AxelRyder** [comment]
I have the exact same issue here, although I'm on Slimkat 4.4.4.

I can try to help if you need me to do anything.

**Comment by RelaxedMind** [comment]
Same issue here, and I think this cause force closefor Chrome.
Htc Amaze 4G - 4.0.4 Eclipse Remix Rom

**Comment by TeamFail** [comment]
I decided to play around with some settings in SetCPU to see if that could rectify the issue, and it didn't, unfortunately. Has anyone found some kind of fix for this issue?

**Comment by AxelRyder** [comment]
I hope the developer(s) are looking into this!

**Comment by RelaxedMind** [comment]
After update still nit works

**Comment by TeamFail** [comment]
I can also say the same, upgrading to 1.4.8 doesn't fix the issue.

**Comment by AxelRyder** [comment]
Same here, still does not work with 1.4.8.

**Comment by spudnub** [comment]
Yeah it sounds like the same issue. I'm running 4.4.2 on a phantom media box

**Comment by TeamFail** [comment]
YouTube 10.21.58 downloaded to my phone today, and while the module didn't break, I'm still having this issue.

**Comment by TeamFail** [comment]
I'm wondering if someone is looking at this, or if anyone needs a logcat to solve this issue. I can gladly provide a logcat if it's needed.

**Comment by AxelRyder** [comment]
I really hope :/

**Comment by TeamFail** [comment]
Installed the past few updates to this, but still not having any luck whatsoever with this.

**Comment by TeamFail** [comment]
Thought I'd also mention that I tested this on a CyanogenMod 11 device (Nexus 7 2012, 4.4.4) and it seems to be working, but it still is not working on my phone. I still have not been able to identify the source of the issue.

Do you need a logcat from us, or is there something else you may need from us to attempt to rectify this issue...?

**Comment by spudnub** [comment]
hey guys. after reading teamfails comment about it working fine on his nexus 7 I spoofed my device into thinking my device is a nexus 10 through the build.prop editor and everything works as it should. big fucking shoutout to all the support everyone has recieved from the devs.

**Comment by TeamFail** [comment]
I'll give that a try once 10.25.57 is supported and let you know how it goes. Since my phone is using a ROM that is based in Europe, that may be what's breaking compatibility.

**Comment by AxelRyder** [comment]
@spudnub So I understand that I need to edit the /system/build.prop to do it, but do you have the specific lines that I should change?

**Comment by esgie** [comment]
Did you guys try 1.6.0 which has been released recently, along with YouTube app version 10.37.xx ? A lot of compatibility issues has been fixed and the module is working much better now.

**Comment by AxelRyder** [comment]
Wow it actually works for me now with 1.6.0, thanks @esgie (and thanks to the developpers!)

**Comment by TeamFail** [comment]
Yeah, it seems to now be working for me now, although I did have to update my outdated YouTube app to the latest version for it to work. I don't have the phone with SlimKat on it right now - it's out for repairs (again), but I do presume that it works. If it doesn't (Although from what I'm seeing it does), I'll file a new issue.
