### ISSUE TITLE
lollipop 5.1.0 support

### ISSUE THREAD

**Issue by dmatora** [pylerSM/YouTubeBackgroundPlayback#52]
not working for me, running
- cynogenmod 12.1 (5.1.0)
- youtube 10.18.55
- xposed-sdk22-arm-20150514
- on galaxy s5 mini (sm-g800f)
what could be an issue?

**Comment by esgie** [comment]
Don't have an idea as it works flawlessy for me on OnePlus One at Android 5.1.1_r3 (also I use the same xposed build as yours).
Let me remind that this module does nothing more than enable in-built youtube app feature. So it's probably some incompatibility between experimental google implementation and rom.
Of course you have enabled the module and rebooted? :)

**Comment by dmatora** [comment]
Not sure what was wrong, after another reboot it now works flawlessly.
