### ISSUE TITLE
Stays paused while in background

### ISSUE THREAD

**Issue by spudnub** [pylerSM/YouTubeBackgroundPlayback#55]
It loads up fine in youtube but returning to the homescreen caues it to pause. When I pull down the notification bar and hit play nothing happens.

http://pastebin.com/RjK0U91N

**Comment by AxelRyder** [comment]
I think it's the same as us here:
https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/51

**Comment by sanaehachi** [comment]
Ok, this is the solution for me.
Pull down notification and next or previous to play
