### ISSUE TITLE
Version 1.4.7 isn't working for Youtube 10.21.58

### ISSUE THREAD

**Issue by TarcisioAlves** [pylerSM/YouTubeBackgroundPlayback#57]
What happened?

**Comment by esgie** [comment]
You forgot to update module to 1.4.8. It's available since some time.

**Comment by TarcisioAlves** [comment]
I can't see it on Xposed. It shows up for me that the last version is the 1.4.7. My Xposed is set up to notify me for new versions of the modules. 
Where can I find the new version?
Thank you very much @esgie!

**Comment by TarcisioAlves** [comment]
I found the new version in the xposed repository website. 
Sorry about the obvious question, but why isn't the new version inside the xposed app. I can't see the new version there, I just can see it in the website. 
Thanks again.

**Comment by esgie** [comment]
Weird. Did you try to click the refresh button in the xposed installer in the top right corner of the screen?
1.4.8 has been released as usual, through stable channel, can't see a reason why you can't see the update ;(

**Comment by TarcisioAlves** [comment]
Yes, I did. It's really weird. Just to let others know, I'm using Xposed for Lollipop.
If you find out the solution, please let me know. If I do, I will comment here.

**Comment by ricebus** [comment]
Doesn't seem to work with 1.4.8 as well

**Comment by ricebus** [comment]
After further testing it seems like upgrading the app didn't work but a full uninatall +reinstall worked.

**Comment by fda77** [comment]
This is a bug of Xposed Installer. Fix:delete the 2 database files in the cache/ path inside the app's dir
