### ISSUE TITLE
version 1.5.0 and also previous versions

### ISSUE THREAD

**Issue by janarp** [pylerSM/YouTubeBackgroundPlayback#58]
When I want to listen in background music stop on half track every song is like that

**Comment by esgie** [comment]
I am really unable to reproduce this error, as well as other ones - still, everything is working fine on my config.
I will refer to the original dev, pyler tomorrow, maybe he'll be able to sort some things out.

**Comment by janarp** [comment]
Thanks ... Hope u guys sort it out :p
