### ISSUE TITLE
Viral Pop-Up Player Support

### ISSUE THREAD

**Issue by ghost** [pylerSM/YouTubeBackgroundPlayback#59]
Hey at first: Thanks for the nice framework! YouTube is really shitty right now on Lollipop, so I was wondering if you could kinda "port" Background Playback to Viral... Keep on developing! :)

**Comment by PwnicornDev** [comment]
This will not be possible, since Viral is an entirely different application.
This module really doesn't do much by itself, it just enables a feature that is already implemented but normally inaccessible in the YouTube app.

**Comment by Eisa-AlAwadhi** [comment]
This is achievable if you desire by downloading another Xposed Module called Awesome Pop-up Video and Awesome Pop-up Video - YouTube Module.

i hope I was able to help

**Comment by martynbm** [comment]
Git clone
