### ISSUE TITLE
Screen off playback issue & background playback not working

### ISSUE THREAD

**Issue by Eisa-AlAwadhi** [pylerSM/YouTubeBackgroundPlayback#6]
Hello,
Thanks for this amazing module firstly.

Sadly, I am not able to use the screen ofd playback because of AcDisplay. Maybe, there's some sort of conflict that makes screen off playback stops if AcDisplay is running.

The other thing is that Background playback doesn't work at all for me: I don't even get a notification.

I'm running Android 4.4.2 using Galaxy S5 (SM-G900F)

If there's anything I can provide to help fix the issue please let me know. This is one of the most interesting modules ever.

Thanks again!

**Comment by pylerSM** [comment]
About AcDisplay, read this: https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/4
Background playback should work with latest module version.

**Comment by catalinthejoker** [comment]
Screen off works for me but background does not. As soon as i put the app in the background everything stops

**Comment by Eisa-AlAwadhi** [comment]
Sadly, I can't confirm if this will solve the issue because I've flashed another ROM. 

However, I have flashed cm12 on SM-G900F and I can confirm that this module fully supports Lollipop! Screen off playback and Background playback are fully functional! Thanks for the best module in exposed!
