### ISSUE TITLE
Worked on Lollipop, doesn't work anymore 

### ISSUE THREAD

**Issue by rafaeldamasceno** [pylerSM/YouTubeBackgroundPlayback#60]
Hi, I have a vegetahd with 5.0 and this module doesn't work well anymore... Back on 4.4.2 everything worked fine all the time, now I get a lot of issues.  Sometimes it plays the song from the beginning on background, the buttons on the notification never work, and if I go back to the app the video breaks and I have to restart it. Anything I can send to help? (some logs or Info)

**Comment by pylerSM** [comment]
Reason: Not small changes in YT app. Not sure if possible to fix.

**Comment by cizaquita** [comment]
I have the same problem, do not work, no notification no background :(
Lollipop 5.1
Youtube 10.34.57
Thanks for your work developing this.

Grettings

**Comment by cizaquita** [comment]
Sorry doble post, i downgraded Youtube to 10.33.xx and now it works :D
