### ISSUE TITLE
Video restarts when exiting app

### ISSUE THREAD

**Issue by jacklefrost** [pylerSM/YouTubeBackgroundPlayback#61]
Not ideal when listening to albums on YouTube and switching apps

**Comment by spudnub** [comment]
sounds like you need to manage how you use the app better. maybe put it in the background right away and it wouldnt be such a bother. why would you wait till your half way through an album to put it in the background anyway... just do that to begin with

**Comment by jeetsingh30** [comment]
Will this issue be resolved??

**Comment by pb1051** [comment]
I agree with jacklefrost. 

When I have finished watching a video (the video has stopped playback) and I exit to the homescreen the video begins to play from the start again. This is not how the app should function. It should realize that the video has completed playback and not begin playing again on exit.

**Comment by breakingspell** [comment]
Finally got around to setting up xposed on 5.1 for this extension, and yeah, any time you exit Youtube while a video is playing, the extension will kick in and play the video in the background, but it starts it from the beginning. 
Locking the screen while Youtube is in the foreground does not restart the video, so I've been using it that way, but it would be nice to see this addressed. Re-entering the Youtube app picks up where the background player left off, but when minimizing Youtube, the video will start from the beginning.

**Comment by pb1051** [comment]
The way to fix it is downgrade YouTube to 10.21.xx

**Comment by NTWarrior** [comment]
The background playback of OGYouTube 1.0 (based on 10.31.55) still works without restarting the video. I turned off its own background playback and installed this module since the notifications are better, but I went back to the OGYouTube version because the restarts were annoying.
