### ISSUE TITLE
Not working on 10.25.57

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [pylerSM/YouTubeBackgroundPlayback#63]
Using 1.5

**Comment by spudnub** [comment]
Wow man how lazy are you? Thanks for all the information you've provided. It sounds like it doesn't work for you because you don't deserve it.

**Comment by TheStig04** [comment]
I signed up for github to help you out since apparentley some people here are fucking dicks.

 Here's what I did to get mine working. Google YouTube 10.25.55 apk and find a downlaod. Go to the playstore and click uninstall to uninstall the updates then uncheck autoupdate. Install the .55 apk you downloaded and the background thing should work.

**Comment by TheOnlyRealTGS** [comment]
I don't think any other information is needed? I simply made this ticket to let the author know it's not working (at all) on the latest YouTube version. I like to keep things simple.
And thanks @TheStig04 sounds like your solution is to downgrade?

**Comment by TheStig04** [comment]
Yeah down grade YT to 10.25.55 and it should work. Be sure uninstall any YT updates otherwise the downgraded version won't install, and uncheck auto update in the playstore.

**Comment by TheOnlyRealTGS** [comment]
Okay. I've never been a fan of unofficial apks so I'll probably wait until my current is supported. Just unchecked auto updates to prevent this in the future.

**Comment by spudnub** [comment]
They literally just updated YouTube and you come on here complaining about it not working. Stop and think for a second about why that may be? And why would you downgrade not using an official apk? Another off putting thing to say as EVERY version EVER put out has been an official apk.

**Comment by TheOnlyRealTGS** [comment]
> They literally just updated YouTube and you come on here complaining about it not working. Stop and think for a second about why that may be? 

I never complained about anything. I simply informed the author that it wasn't working. I posted this ticket because 1.5 states that it's compatible with 10.25.57 which it isn't.

>And why would you downgrade not using an official apk? 

That's not what I said, I said I'm not a fan of _unofficial_ apks. I don't know a source where you can get official apks for YouTube other than play store.

**Comment by kurtextrem** [comment]
Apkmirror.com is legit,  created by AndroidPolice

**Comment by vel2000** [comment]
Downloaded  YouTube 10.25.55 (Both different APK), but background playback doesn't work anyway.
When pressing the home button, Youtube stops immediately.
Running Android 4.4.2 on a Minix X8 Android box.

**Comment by TheOnlyRealTGS** [comment]
>Apkmirror.com is legit, created by AndroidPolice

I does look legit, but I can't be sure?

**Comment by kurtextrem** [comment]
You apparently don't know androidpolice.com , look it up, search for any google app (play store)  and check the dl links. Goes right to apkmirror.

**Comment by TheOnlyRealTGS** [comment]
I think the name sounds familiar, I may have heard it before. And okay, thanks for info!

**Comment by TheOnlyRealTGS** [comment]
Closing this, new YouTube version online
