### ISSUE TITLE
How to playback with 10.25.57 in background

### ISSUE THREAD

**Issue by bhendilun** [pylerSM/YouTubeBackgroundPlayback#66]
When the video starts playing and home screen is pressed, audio stops immediately, pulling down on the notification bar automatically starts the music again (although from the beginning, no problem since we just minimized it under 5 seconds ago), and pause/play functionality works too. Can turn the screen on/off also. Going back to the Youtube app will cause the music/video to stop, so don't do it until you're ready to change tracks.

Downgrading to 10.21.57 fixes this, but still have to pull on notification bar sometimes; video doesnt restart from beginning on this version

**Comment by rdarioc** [comment]
Which module version you used when you made those tests? And which android version?
