### ISSUE TITLE
Works, but pauses after 20-25 seconds

### ISSUE THREAD

**Issue by vinistois** [pylerSM/YouTubeBackgroundPlayback#69]
1+1 on Lollipop 5.1.1_r8 (Exodus Rom)
YouTube 10.21.58 (staying on old version according to instructions)
Module 1.5.3

Works, but the playback pauses after about 25 seconds.  When I pull down, the pause button is going in a circle as if it was buffering.  Tried to force the screen to stay on to see if something was going to sleep, still does the same thing.  To get it to start again, you have to skip to the next video in the playlist.  Verified that the same tracks work with no buffering when I stay in the YT app. 

Also when playing back a playlist (nonstop music mix) when the track ends, it does not proceed to the next track, you have to hit it manually.

**Comment by Shadetail** [comment]
This exact same thing is happening to me as well on nexus 6, android 5.1.1 LMY47Z, Youtube 10.21.58 using module 1.5.2

**Comment by mmccollow** [comment]
Same thing here using YouTube 10.31.55 on CloudyG3 2.5 with module version 1.5.3. Changelog says it should support 10.31.xx. It plays until it hits the end of the buffer, then stops with the spinner animation and never buffers the next segment of the video.

**Comment by jtw111** [comment]
Same issue here. Except for me, it happens after longer than 20-25 seconds; it's a couple minutes. This glitch makes this module not even usable unless you like only listening to half of a video.

**Comment by SuperSandro2000** [comment]
Same over here. S5 international Cyanogenmod 12.1 Nighlies

**Comment by ckojam** [comment]
Same here. Using LG G4. Xposed 3.0 Alpha 4
