### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by tassoschry** [pylerSM/YouTubeBackgroundPlayback#7]
Hello,

Nexus 5 user here, running Frank v.13 (http://forum.xda-developers.com/google-nexus-5/development/l-android-lpv-dev-n5-enhanced-t2856934) on franco kernel r.71.
Both the background and screen off playback work great for me.
Wanted to thank you and make some suggestions.
First of all, there's this small pause (delay) like 5 seconds or so between the moment i press home button and the moment the audio starts playing again. It would be great if the transmission from fore to background was smoother.
Second, can't seem to play playlists. What i mean is, after the first song is done playing and the screen is off, the second one doesn't start automatically, only by pressing the next button.
Anyways, great module and thanks for your awesome effort!

**Comment by pylerSM** [comment]
Firstly, Thanks!

1, This small pause can't be removed. We need to "restart" audio playing when app is moved to background. Without this, there will be no background playback.
2, I dont't know about this, I won't waste time with it.

**Comment by Syl0s** [comment]
I have the same issue with playlists not autoplaying, when in background and am on a Nexus 4 with CyanogenMod, if that helps.
I mean, maybe it's an issue on Nexus-devices, as that seems to be the most common denominator.
But I don't understand enough about your module to know, if that could even play any role...

**Comment by octoshrimpy** [comment]
Love the new update, works beautifully! :D a quick heads up though, when tapping on a notification that switches apps (like hangouts) YouTube doesn't pause, but there is also no notification until I switch back to YouTube. :)

**Comment by Syl0s** [comment]
The playlist-issue seems to be resolved as of version 1.3.4. At least, it works for me, alongside YouTube-version 10.10.52. Maybe check, if it works for you, too, now.

**Comment by tassoschry** [comment]
Yes, it seems to be resolved a while now. 2 or 3 updates back i think fixed the issue for me. Latest module version and latest YouTube version running.
