### ISSUE TITLE
[Feature] Add a button to turn on

### ISSUE THREAD

**Issue by sandrosdj** [pylerSM/YouTubeBackgroundPlayback#70]
Add a button to the player itself (youtube app) to turn on background playback mode.

So when I click on a video, it should play only in foreground mode, except when I tap the BG playback button to turn on backgroud playback.

**Comment by lukigno95** [comment]
Quote

**Comment by PwnicornDev** [comment]
This is not feasible, since all the module does is enabling a function that's already built it the YouTube app. The only way I could think of would be to try and enable the corresponding options in the settings of the app, which would probably lead to new problems.
