### ISSUE TITLE
YouTube 10.40.58 DOES NOT work

### ISSUE THREAD

**Issue by miladmaz12** [pylerSM/YouTubeBackgroundPlayback#76]
https://www.apkmirror.com/apk/google-inc/youtube/youtube-10-40-58-android-4-0-3-5-1-1-android-apk-download/

Note: This is a different build. The last YT was 10.40.56

**Comment by clownfish44** [comment]
I have also noticed that this version YouTube does not work. Recommendation to you make a backup of YouTube before you update with titanium backup.

**Comment by miladmaz12** [comment]
This is now supported

**Comment by miladmaz12** [comment]
https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/72#issuecomment-148493553

**Comment by iHelp101** [comment]
My bad I pointed the hooks update in the wrong issue. The updated hooks are below. I tested them and they appear working for me. 

Class 1: kys -> kyr
Class 2: iqq -> iqp

**Comment by miladmaz12** [comment]
@esgie ^^^^

**Comment by esgie** [comment]
Yup already included in the new version.
"!" does show on Lollipop 5.1 and some player exception is shown in the logcat.
Everything is fine (!) on Touchwiz-KitKat 4.4.
As @pylerSM said somewhere it might be something about restarting playback.

@iHelp101 can you build your own version and check if it works? And then check if the newest one from the repo (1.6.4) works, too? That would be really helpful!

**Comment by iHelp101** [comment]
Alright, did you ever find a correlation with Cyanogenmod based ROMs and the playback issue? Or are you experiencing the issue on a manufacturer/stock based ROM aswell?

**Comment by miladmaz12** [comment]
@iHelp101 Yeah I am using Cyanogenmod

**Comment by esgie** [comment]
I am experiencing the issue on OPO running (unofficial) Cyanogenmod 12.1.
The issue is not present on Samsung tablet @Touchwiz kitkat.
It was present on OPO only for 10.40.56 also. I have tested it widely in the other topic so it is not mistake.
10.36-10.39 working fine on both devices.
I don't have truly time to analyze logcat atm. It is something about codec losing sync in player.
I feel that it is somehow related to used software or configuration.
I do not have other testing devices by hand right now.

**Comment by clownfish44** [comment]
I am on an official cm12s on an OPO

**Comment by esgie** [comment]
http://pastebin.com/hHCaYaq0
Logcat

**Comment by iHelp101** [comment]
I am trying to find the fail point in the Youtube app. Something had to change (! icon is usually audio related) that makes audio get released for some reason. As a reminder we are using a feature that is still beta testing, so I am wondering if maybe it is broken currently.

**Comment by TeamFail** [comment]
I'm running Slimkat 4.4.2 and am having issues with this as well. Did you want a logcat from my OS as well?

**Comment by miladmaz12** [comment]
I just update to 10.40.58 and it works for me. I am closing this issue
