### ISSUE TITLE
YouTube 10.40.58 new problems

### ISSUE THREAD

**Issue by clownfish44** [pylerSM/YouTubeBackgroundPlayback#78]
YouTube playback errors when screen off or switching out of youtube v1.6.4

**Comment by GustavoWiesner** [comment]
When I leave the application in the background, the song stops. This happens with most of the songs I listen to.

**Comment by clownfish44** [comment]
I have played with it manytimes and the song never stops but in this version i have playback issues

**Comment by GustavoWiesner** [comment]
Recently, problems have been completed and the application to work excellently.

**Comment by ashrafsazali** [comment]
I just downloaded it. When play video and press home button it will stop working. Only works when video is playing n i lock the phone.

**Comment by clownfish44** [comment]
I have the exact same problem. Anyone have ideas? You can back date youtube download it from here https://www.apkmirror.com/apk/google-inc/youtube/youtube-10-39-54-nodpi-android-apk-download/ but keep youtube background playback v1.6.4

**Comment by ashrafsazali** [comment]
It works. Thanks a lot for the help

**Comment by clownfish44** [comment]
Your welcome! 
![image](https://cloud.githubusercontent.com/assets/15145228/10613553/abe31dfe-7723-11e5-8e94-215d4441dfa1.png)

**Comment by WtfJoke** [comment]
I got the same issue. When I hit the home button the audio stops. If I open the video it says: Problems while playing, Click to reload

**Comment by beatschubser** [comment]
Just wanted to leave a big THANK YOU for your module. One of the main reasons I still have a rooted phone.

**Comment by davex2012** [comment]
Still problem in version 1.6.5 Youtube Version 10.40.58 Note 3 N9005 Aryamod 7.4. Here log may help you.

**Comment by AuroraWright** [comment]
https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/80 I think your solution is here.

**Comment by davex2012** [comment]
Work fine with headphone but without headphone don't work.

**Comment by AuroraWright** [comment]
@davex2012 With my workaround it always works. I opened a new issue to give it more visibility.
