### ISSUE TITLE
Background Playback only works with headphones [workaround inside]

### ISSUE THREAD

**Issue by AuroraWright** [pylerSM/YouTubeBackgroundPlayback#80]
It seems YouTube introduced a settings dialog for background playback (visible to YouTube Red subscribers) which has 3 options: "On" "On with headphones and external speakers" "Off".
Default is "On with headphones and external speakers", so when using this module an error will be shown when trying to use background playback _without_ headphones.
Luckily this setting can be easily toggled with root. Kill YouTube, go to /data/data/com.google.android.youtube/shared_prefs, open youtube.xml (CM's built-in file manager works, but any root file manager should work). Look for this string http://pastebin.com/uxfKE11e (it should have "on_if_hh" as value). If it exists, carefully change on_if_hh to on.
If it doesn't, create it.
Save. It works now :)

**Comment by davex2012** [comment]
Yeah but I've no problem with headphone. Only problem with without headphone.

**Comment by AuroraWright** [comment]
That's precisely what this fixes. By default, background playback only works with headphones.

**Comment by davex2012** [comment]
Can't find the string either.

**Comment by AuroraWright** [comment]
OK, just did it on my brother's phone. For some reason he hadn't this string either. I just created it (copy and paste a different string, change its name to background_audio_policy and put *on* as value (the text between the <>s)

**Comment by davex2012** [comment]
Well can't find either.

**Comment by esgie** [comment]
@AuroraWright nice finding.
http://www73.zippyshare.com/v/ujBgxVZD/file.html
Can you test this build? This may provide a fix for broken playback without headphones.
YouTube 10.43.58 ONLY.

**Comment by davex2012** [comment]
Just tested and now background playback don't work. 😢

**Comment by esgie** [comment]
Did you update to 10.43.58?

**Comment by esgie** [comment]
XposedHelpers.findAndHookMethod("azl", lpparam.classLoader,"d",XC_MethodReplacement.returnConstant("on"))
I have added code above to return always "on" as the setting value

**Comment by davex2012** [comment]
It's working now ☺ 👍.  Many thanks.

**Comment by AuroraWright** [comment]
Yeah, I confirm it works :)

**Comment by alex100395** [comment]
How do we apply the code? ;o

**Comment by esgie** [comment]
You don't have to. New build released with support for yt 10.40 and 10.43 with the bug fixed.
Thanks to @AuroraWright for his finding!!!

**Comment by alex100395** [comment]
Its not working when i minimize youtube. I get a ! On the notification player :(

**Comment by AuroraWright** [comment]
@esgie "her" :P

**Comment by alex100395** [comment]
Ok its working with the 40.58 version thnx ;)

**Comment by esgie** [comment]
@AuroraWright I apologize. Really appreciate your help ;)
