### ISSUE TITLE
Newest You Tube version  10.43.58

### ISSUE THREAD

**Issue by Tim3tripp3r** [pylerSM/YouTubeBackgroundPlayback#82]
I know that you just realised a 1.66 version for previous You Tube versions but I am wondering if another update is in the mix for latest You Tube version 10.43.58 as the 1.66 doesn't function above the stated versions in the release notes.

**Comment by esgie** [comment]
1.6.6 IS compatibile with YouTube 10.43.58 so feel free to update!
I have mispelled "58" in the release notes.
Fixed already!
