### ISSUE TITLE
Marshmallow support

### ISSUE THREAD

**Issue by andreglud** [pylerSM/YouTubeBackgroundPlayback#86]
Doesn't seem to work on marshmallow on version 10.43.60

**Comment by tomgacz** [comment]
yes, dont work on xposed framework v77, nexus 4, minimalOS based on cm, 6.0 marshmallow

**Comment by abhijeetramgir** [comment]
Yes, doesn't work on 10.43.60, marshmallow, cm13

**Comment by Skyloud** [comment]
Yes, it only works in 10.40.58 or later.
So I installed this version of Youtube:
http://www.apkmirror.com/apk/google-inc/youtube/youtube-10-40-58-480dpi-android-4-0-3-5-1-1-android-apk-download/
And it worked.
Print: http://imgur.com/4XT2irw

**Comment by andreglud** [comment]
Are there any difference on that version compaired to the current?

**Comment by Skyloud** [comment]
No I think, both have google cardboard support (the lastest "new" update of youtube).

**Comment by esgie** [comment]
Guys,
10.43.62 is supported!
Grab it here:
http://www.apkmirror.com/?s=Youtube&post_type=apps_post

**Comment by tomgacz** [comment]
esgie, we cant install this youtube version - its only to max 5.1... we need version for 6.0+

**Comment by esgie** [comment]
10.45.52 has been released.
Unfortunately there was some major code changes and it needs a further investigation,
@iHelp101 
Your help is priceless - can you help this time? :)
The first hook should has below values I guess:
"lns", "b", "f", "e"
But atm I cannot really find the proper way of enabling the second hook - the code in the class "jff" seems to changed ENTIRELY.
And I keep getting "audio error" only :(

**Comment by esgie** [comment]
@andreglud 
@Skyloud 
Can you test below build against 10.43.60 on Marshmallow:
http://www17.zippyshare.com/v/bBmVLNYF/file.html

Note that 10.45.52 which has been released today is NOT YET supported!!!

**Comment by tomgacz** [comment]
@esgie working! thanks :) nexus 4, minimalOS based on cm, android 6.0 marshmallow
