### ISSUE TITLE
Support for yt 10.45.52

### ISSUE THREAD

**Issue by esgie** [pylerSM/YouTubeBackgroundPlayback#88]
10.45.52 has been released.
Unfortunately there was some major code changes and it needs a further investigation,
@iHelp101 
@pylerSM 
Your help is priceless - can you help this time? :)
The first hook should have below values I guess:
"lns", "b", "f", "e"
But atm I cannot really find the proper way of enabling the second hook - the code in the class "jff" seems to changed ENTIRELY.
And I keep getting "audio error" only :(

**Comment by clownfish44** [comment]
Sure hope that this is resolved soon as I like to be on the latest version of YouTube

**Comment by esgie** [comment]
The changes had been withdrawn with 10.47. So issue shall be closed.
