### ISSUE TITLE
Not working 10.43.60

### ISSUE THREAD

**Issue by Poorchop** [pylerSM/YouTubeBackgroundPlayback#89]
I'm using KitKat 4.4.4 and the latest release isn't working for me after updating from 1.6.7. I reverted back to 1.6.7 and it's working perfectly with the same Youtube version, 10.43.60.

While 1.6.8 was installed, I tried disabling, rebooting, re-enabling, and rebooting a few times but with no success.

**Comment by brbsix** [comment]
I am having the same issue with YouTube Background Playback 1.6.8 and YouTube 10.43.60 on Android 4.4.2. I also had to revert back to YTBP 1.6.7.

**Comment by sonejizrelax** [comment]
Exactly the same. I'm currently using 1.6.7. A fix would be very helpful

**Comment by sonejizrelax** [comment]
Forgot to mention I'm on 5.1.1

**Comment by esgie** [comment]
Please downgrade to 1.6.7
1.6.8 is marshmallow only.

**Comment by Poorchop** [comment]
Is there still going to be support for KitKat and Lollipop going forward or should we stick to the current Youtube version + current module version until we are able to upgrade to Marshmallow?

**Comment by esgie** [comment]
It depends on future YouTube app releases.
10.43.60 for 6.0 and 5.1- builds were inconsistent, they required different hooks.
We'll see.

**Comment by palxex** [comment]
1.7.2 still have the problem(10.43.60 on 5.0.2),  downgrade to 1.6.7 works for me.

**Comment by esgie** [comment]
As I said:
YouTube 10.43.60 had been released in two different versions: for Android 6.0 ONLY and for Android 5.1.1 or lower ONLY. So, if you want to use 10.43.60 with Android 5.1.1 or lower you have to stay with module version 1.6.7.
Otherwise please just update your YouTube app to 10.47.54.
