### ISSUE TITLE
not work for me

### ISSUE THREAD

**Issue by djkev** [pylerSM/YouTubeBackgroundPlayback#9]
does not work with lollipop ?? or am I doing wrong someone can help me or should I set ??

**Comment by upstreammiami** [comment]
Yea it was working fine but after the update it stopped

**Comment by djkev** [comment]
I spend the same ??

**Comment by upstreammiami** [comment]
What

**Comment by KunamiPT** [comment]
When installing v1.1.1 on OnePlus One, I got: "X App not installed"

**Comment by kirito96** [comment]
not working on galaxy s3 sgh i-747m well it plays when the screen is off but you can't exit youtube and it is still playing

**Comment by pylerSM** [comment]
Youtube version? Android version?

**Comment by kirito96** [comment]
Android 4.4.2 and YouTube version 10.05.6
