### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by panda82** [pylerSM/YouTubeBackgroundPlayback#94]
Not working on youtube 10.47.54 KK 4.4.4

**Comment by battetop20474** [comment]
not working on youtube 10.47.54 lp zenfone2 551

**Comment by panda82** [comment]
Mine is samsung s2 I9100

**Comment by esgie** [comment]
Where did you get version 10.47.54?
I cannot see it neither on the Play Store nor apkmkrror.

**Comment by panda82** [comment]
From playstore

**Comment by esgie** [comment]
Still no update for me at the moment ; (
I'll update the module as soon as i'll get the apk of newest youtube.

**Comment by panda82** [comment]
http://s000.tinyupload.com/index.php?file_id=82189535898052523179

**Comment by esgie** [comment]
Hey thanks.
The update will be ready in no more than half an hour (I nope).

**Comment by panda82** [comment]
Try this link, if first one doesnt download correct:

http://www.fileconvoy.com/dfl.php?id=gbb458e7d2849eaa99997569533a903b92e8ee1ec1

**Comment by panda82** [comment]
Working the update. Thanks!
