### ISSUE TITLE
Not Working version 1.7.2

### ISSUE THREAD

**Issue by rulax13k** [pylerSM/YouTubeBackgroundPlayback#95]
installed via latest xposed version as of December 9th 
you tube does not keep playing when i press the lock/off button & suggests to join/install you tube red

**Comment by esgie** [comment]
I assume you use module version 1.7.2?
Which YouTube version do you use? I recommend updating to 10.47.54.
Did you check the module in the modules list and then reboot?

**Comment by rulax13k** [comment]
yes its 1.7.2
i used this program before many times,  im on youtube version 10.43.60
i will update  and retry
thank you for replying

**Comment by rulax13k** [comment]
Worked , Thank you

**Comment by esgie** [comment]
Ah
If you are on Lollipop and use version 10.43.60 please
- downgrade the module to 1.6.7 
OR
- update the YouTube to 10.47.54
