### ISSUE TITLE
Now working 10.47.55

### ISSUE THREAD

**Issue by panda82** [pylerSM/YouTubeBackgroundPlayback#97]
Hi. Youtube realesed new version. 
Here is apk of yt 10.47.55: 

http://www.fileconvoy.com/dfl.php?id=g36fd997a214c803999975912187425aa6d5ff059a

**Comment by zaheer9869** [comment]
Don't know if this will help 
on Android 4.4 ..module 1.6.7 - Youtube 10.43.58 - Works

**Comment by buts101** [comment]
not working

**Comment by panda82** [comment]
I have posted the apk it for the developer to release a patch.

**Comment by esgie** [comment]
1.7.3 update is available since yesterday
