### ISSUE TITLE
Force highest quality by default 

### ISSUE THREAD

**Issue by terrorist96** [pylerSM/YouTubeBackgroundPlayback#99]
Hi there. I'm looking for a way to have youtube automatically select the highest available stream quality. As it currently stands, I frequently have to tap the video, tap the menu button, tap the quality button, then tap the highest offered quality. I know this may be out of the purview of this module, but if it's not too difficult, could it be added, or perhaps a separate module that would do this? Thanks for reading.

**Comment by esgie** [comment]
There was once a module called YourTube by GermainZ which was what you are
looking for.
Unfortunately it's no longer maintained.
We may analyze the issue (contact the dev of that module or check if this
is opensource to use the code), but not earlier than after xmas ;)
19 gru 2015 02:55 "terrorist96" <notifications@github.com> napisał(a):

**Comment by terrorist96** [comment]
Yeah, I did see GermainZ's module, and it hasn't been maintained, which is why I'm asking you. :) 
It's no rush. I'm more than thankful that you're gonna look into it. :smile:
